(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.HEAD4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHAHQgDgCAAgFQAAgDADgEQADgDAEAAQAEAAAEADQADAEAAADQAAAFgDACQgEADgEAAQgEAAgDgDg");
	this.shape.setTransform(140.65,45.15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AALAxIAAgJIALAAQADAAAAgEIAAgyQAAgYgUAAQgNAAgIAMQgIAMAAATIAAAfQAAABAAABQABAAAAABQAAABABAAQAAAAABAAIAMAAIAAAJIgtAAIAAgJIAMAAQADAAAAgEIAAhEQAAgFgDAAIgMAAIAAgKIAIAAQAOAAAIgBIAAAaQAKgbAYAAQAeABAAAhIAAAzQAAABAAABQABAAAAABQAAABABAAQAAAAABAAIAMAAIAAAJg");
	this.shape_1.setTransform(132.025,41.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgnAsQgJgIAAgLQAAgQARgIQAQgIAigDIAAgFQAAgOgHgFQgGgGgMAAQgRAAgIAIQAHADAAAGQAAAEgDAEQgDACgEAAQgLAAAAgLQAAgMAMgHQAMgGARgBQATAAAJAIQAJAJAAARIAAAzQAAABABABQAAAAAAABQAAABABAAQAAAAABAAIANAAIAAAJIgbAAQgCgIgBgMQgFAKgKAHQgJAFgNAAQgNAAgIgGgAgUAFQgMAHAAALQgBAIAGAFQAFAFAJgBQANAAAKgJQAIgKABgQIAAgHQgcACgLAFg");
	this.shape_2.setTransform(120.15,41.15);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWBDIAAgJIANAAQADAAAAgEIAAhoQAAgFgDAAIgNAAIAAgKIAJAAQANAAAIgBIAAB4QAAABAAAAQAAABAAABQABAAAAABQABAAAAAAIANAAIAAAJg");
	this.shape_3.setTransform(110.975,39.275);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgyBCIAAgJIAOAAQACAAAAgEIAAhoQAAgFgCAAIgOAAIAAgKIA0AAQAxAAAAAnQAAAUgMAIQgMAKgZAAIgUAAIAAAqQAAAEACAAIAOAAIAAAJgAgSABIAUAAQARAAAIgGQAHgHABgPQgBgPgHgHQgIgHgRAAIgUAAg");
	this.shape_4.setTransform(101.75,39.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AALBDIAAgJIAMAAQAAAAABAAQAAgBAAAAQABgBAAgBQAAAAAAgBIAAg0QAAgWgUAAQgMAAgJAMQgIALAAAUIAAAfQAAABAAAAQAAABABABQAAAAAAABQABAAABAAIALAAIAAAJIgtAAIAAgJIAOAAQAAAAABAAQAAgBAAAAQABgBAAgBQAAAAAAgBIAAhoQAAgFgCAAIgOAAIAAgKIAJAAQAOAAAIgBIAAA8QAKgZAXAAQAfAAAAAgIAAA1QAAABAAAAQAAABABABQAAAAAAABQABAAAAAAIANAAIAAAJg");
	this.shape_5.setTransform(83.95,39.275);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgFA3QgGgGAAgOIAAg+IgPAAIAAgIIAKgBQAHgBABgGIABgRIAKAAIAAAXIAXAAIAAAKIgXAAIAAA+QAAAJADAEQADADAIAAQAFAAAFgCIAAAKQgGACgIAAQgNAAgFgGg");
	this.shape_6.setTransform(74.125,40.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgWBDIAAgJIANAAQADAAAAgEIAAhoQAAgFgDAAIgNAAIAAgKIAJAAQANAAAIgBIAAB4QAAABAAAAQAAABAAABQABAAAAABQABAAAAAAIANAAIAAAJg");
	this.shape_7.setTransform(67.575,39.275);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgnAsQgJgIAAgLQAAgQARgIQAQgIAigDIAAgFQAAgOgHgFQgGgGgMAAQgRAAgIAIQAHADAAAGQAAAEgDAEQgDACgEAAQgLAAAAgLQAAgMAMgHQALgGASgBQATAAAJAIQAJAJAAARIAAAzQAAABABABQAAAAAAABQAAABABAAQAAAAABAAIANAAIAAAJIgbAAQgCgIgBgMQgFAKgKAHQgJAFgNAAQgNAAgIgGgAgUAFQgMAHAAALQgBAIAGAFQAFAFAJgBQANAAAKgJQAIgKABgQIAAgHQgcACgLAFg");
	this.shape_8.setTransform(58.95,41.15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AghAlQgNgOAAgXQAAgVAOgOQANgOAVgBQAUABANANQAMANAAAVIAAAEIhNAAQAAARAJALQAJALAPAAQAbAAAGgZIAKAEQgEANgKAJQgMAJgRgBQgWAAgOgNgAAfgGQAAgQgHgJQgIgJgOAAQgOAAgIAJQgJAJgBAQIA9AAIAAAAg");
	this.shape_9.setTransform(47.275,41.15);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AATBCIAAgJIANAAQADAAAAgEIAAgyIhFAAIAAAyQAAAEADAAIANAAIAAAJIgvAAIAAgJIANAAQADAAAAgEIAAhoQAAgFgDAAIgNAAIAAgKIAvAAIAAAKIgNAAQgDAAAAAFIAAAuIBFAAIAAguQAAgFgDAAIgNAAIAAgKIAvAAIAAAKIgNAAQgDAAAAAFIAABoQAAAEADAAIANAAIAAAJg");
	this.shape_10.setTransform(34.175,39.35);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AALAxIAAgJIALAAQADAAAAgEIAAgyQAAgYgUAAQgNAAgIAMQgIAMAAATIAAAfQAAABAAABQABAAAAABQAAABABAAQAAAAABAAIAMAAIAAAJIgtAAIAAgJIAMAAQADAAAAgEIAAhEQAAgFgDAAIgMAAIAAgKIAIAAQAOAAAIgBIAAAaQAKgbAYAAQAeABAAAhIAAAzQAAABAAABQABAAAAABQAAABABAAQAAAAABAAIAMAAIAAAJg");
	this.shape_11.setTransform(14.825,41.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgiAlQgOgOAAgXQAAgVAOgOQAOgOAUgBQAWABANAOQAOAOAAAVQAAAXgOAOQgNANgWAAQgVAAgNgNgAgYgdQgJAKAAATIAAABQAAATAJAKQAJALAPAAQAQAAAJgLQAJgKAAgTIAAgBQAAgTgJgKQgJgLgQAAQgPAAgJALg");
	this.shape_12.setTransform(2.575,41.15);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag1A1QAAgQAZgGQgTgCAAgPQAAgNAQgEQgOgKAAgSQAAgOALgLQAMgKASAAQATABALAKQAEgSANAAQAFAAADADQADACAAAEQAAAEgDADQgCACgEAAQgGABgCgHQgEAEgCAIQAFAHAAALQAAAQgLAKQgMAIgSAAQgKAAgJgDQgLACAAAIQAAAKAPAAIAmAAQAeAAAAAXQAAAPgOAJQgPAHgYAAQgwAAAAgVgAgoAzQAAAPAkABQAogBAAgTQAAgIgFgCQgFgEgMAAIggAAQgWAFAAANgAgXgyQgHAHAAAMIAAABQAAAMAGAHQAHAGANABQALgBAHgGQAHgHAAgMIAAgBQAAgMgHgHQgHgHgLAAQgMAAgHAHg");
	this.shape_13.setTransform(-8.875,42.75);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AghAlQgNgOAAgXQAAgVAOgOQANgOAVgBQAUABANANQAMANAAAVIAAAEIhNAAQAAARAJALQAJALAPAAQAbAAAGgZIAKAEQgEANgKAJQgMAJgRgBQgWAAgOgNgAAfgGQAAgQgHgJQgIgJgOAAQgOAAgIAJQgJAJgBAQIA9AAIAAAAg");
	this.shape_14.setTransform(-20.425,41.15);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AglAxIAAgJIAMAAQABAAAAAAQABAAAAgBQAAgBABAAQAAgBAAgBIAAhEQAAgFgDAAIgNAAIAAgKIAJAAQANAAAIgBIAAAXQAHgYATAAQAKABAGAFQAFAGAAAHQAAAOgMABQgEgBgCgCQgDgCAAgEQAAgHAIgBQgCgHgIAAQgMAAgFAMQgGALAAASIAAAiQAAAEADAAIAMAAIAAAJg");
	this.shape_15.setTransform(-30.775,41.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AguAyQgSgTAAgeQAAgfATgTQASgSAcgBQAcABASASQASATAAAfQAAAegSATQgSASgdAAQgcAAgSgSgAgigqQgOAPAAAaIAAADQAAAaAOAQQANAPAVgBQAXABANgPQANgQAAgaIAAgDQAAgagNgPQgOgPgWAAQgVAAgNAPg");
	this.shape_16.setTransform(-43.025,39.35);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AghAlQgNgOAAgXQAAgVAOgOQANgOAVgBQAUABANANQAMANAAAVIAAAEIhNAAQAAARAJALQAJALAPAAQAbAAAGgZIAKAEQgEANgKAJQgMAJgRgBQgWAAgOgNgAAfgGQAAgQgHgJQgIgJgOAAQgOAAgIAJQgJAJgBAQIA9AAIAAAAg");
	this.shape_17.setTransform(-61.775,41.15);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AALBDIAAgJIALAAQABAAABAAQAAgBAAAAQABgBAAgBQAAAAAAgBIAAg0QAAgWgUAAQgMAAgJAMQgIALAAAUIAAAfQAAABAAAAQAAABABABQAAAAAAABQABAAAAAAIAMAAIAAAJIgtAAIAAgJIAOAAQAAAAABAAQAAgBAAAAQABgBAAgBQAAAAAAgBIAAhoQAAgFgCAAIgOAAIAAgKIAJAAQAPAAAHgBIAAA8QAKgZAYAAQAeAAAAAgIAAA1QAAABAAAAQAAABABABQAAAAAAABQABAAAAAAIAOAAIAAAJg");
	this.shape_18.setTransform(-73.7,39.275);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgFA3QgGgGAAgOIAAg+IgPAAIAAgIIAKgBQAHgBABgGIABgRIAKAAIAAAXIAXAAIAAAKIgXAAIAAA+QAAAJADAEQADADAIAAQAFAAAFgCIAAAKQgGACgIAAQgNAAgFgGg");
	this.shape_19.setTransform(-83.525,40.075);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAmAxIAAgJIAMAAQAAAAABAAQAAAAAAgBQABgBAAAAQAAgBAAgBIAAgvQAAgOgFgHQgEgGgLAAQgZAAAAAlIAAAlQABABAAABQAAAAAAABQAAABABAAQAAAAABAAIANAAIAAAJIgrAAIAAgJIALAAQABAAAAAAQABAAAAgBQAAgBAAAAQAAgBAAgBIAAgyQAAgYgUAAQgYAAAAAlIAAAlQAAABAAABQAAAAABABQAAABAAAAQABAAABAAIALAAIAAAJIgtAAIAAgJIANAAQADAAAAgEIAAhEQAAgFgDAAIgNAAIAAgKIAJAAQAOAAAHgBIAAATQAJgTAVgBQAWAAAGAYQAIgYAWAAQAfAAAAAlIAAAwQAAAEADAAIAMAAIAAAJg");
	this.shape_20.setTransform(-101.55,41.05);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgiAlQgOgOAAgXQAAgVAOgOQAOgOAUgBQAWABANAOQAOAOAAAVQAAAXgOAOQgNANgWAAQgVAAgNgNgAgYgdQgJAKAAATIAAABQAAATAJAKQAJALAPAAQAQAAAJgLQAJgKAAgTIAAgBQAAgTgJgKQgJgLgQAAQgPAAgJALg");
	this.shape_21.setTransform(-116.525,41.15);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AglAxIAAgJIAMAAQABAAAAAAQABAAAAgBQAAgBABAAQAAgBAAgBIAAhEQAAgFgDAAIgNAAIAAgKIAJAAQANAAAIgBIAAAXQAHgYATAAQAKABAGAFQAFAGAAAHQAAAOgMABQgEgBgCgCQgDgCAAgEQAAgHAIgBQgCgHgIAAQgMAAgFAMQgGALAAASIAAAiQAAAEADAAIAMAAIAAAJg");
	this.shape_22.setTransform(-127.075,41.05);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgZBEIAAgJIALAAQABAAAAAAQABgBAAAAQAAgBAAgBQAAAAAAgBIAAhJIgOAAIAAgKIAOAAIAAgMQAAgbAYAAQAKAAAFADIAAAKQgFgDgGAAQgIAAgDAEQgDAEAAALIAAAKIAUAAIAAAKIgTAAIAABJQAAABAAAAQAAABAAABQAAAAABABQAAAAABAAIAOAAIAAAJg");
	this.shape_23.setTransform(-134.9,39.175);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag6BKQgQgTAAgfQAAgeAQgTQARgSAbAAQAjAAAOAfIAAg6QAAgGgEAAIgSAAIAAgNIANAAQASAAALgCIAACiQAAAGADAAIARAAIAAAMIgmAAIgCgdQgNAggkAAQgbAAgRgSgAgpgQQgMAOAAAYIAAAEQAAAYAMAOQAMAOAVAAQASAAAMgOQANgOAAgZIAAgCQAAgYgNgOQgMgOgSAAQgVAAgMANg");
	this.shape_24.setTransform(131.25,13.325);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgtAxQgRgTAAgeQAAgdASgTQASgTAdAAQAbAAARARQAQASAAAeIAAAFIhoAAQAAAXAMAOQAMAPAWAAQAiAAAKgiIAMAFQgEATgOALQgPAMgYAAQgfAAgSgTgAAqgIQAAgWgKgMQgLgNgTAAQgSAAgMANQgMAMgBAWIBTAAIAAAAg");
	this.shape_25.setTransform(115.1,15.725);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgsAxQgSgTAAgeQAAgdASgTQASgTAcAAQAcAAAQARQARASAAAeIAAAFIhpAAQAAAXANAOQANAPAUAAQAkAAAIgiIAOAFQgFATgOALQgPAMgZAAQgeAAgRgTgAArgIQgBgWgKgMQgLgNgTAAQgTAAgLANQgMAMgCAWIBVAAIAAAAg");
	this.shape_26.setTransform(100.2,15.725);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAPBDIAAgNIAPAAQAEAAAAgGIAAhEQAAgggcAAQgQAAgLAQQgMAQAAAcIAAAoQAAAGAEAAIARAAIAAANIg+AAIAAgNIASAAQADAAAAgGIAAhcQAAgGgDAAIgSAAIAAgNIALAAQAUAAAKgCIAAAiQANgjAhAAQApAAAAAtIAABFQAAAGAEAAIARAAIAAANg");
	this.shape_27.setTransform(84.4,15.575);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("Ag1AYIAAhIQAAgFgDAAIgRAAIAAgNIAoAAIAABZQAAAeAcAAQARAAAKgPQALgPAAgXIAAgwQAAgFgEAAIgRAAIAAgNIApAAIAABvQAAAGAEAAIARAAIAAANIgLAAQgTAAgLACIAAgfQgOAggfAAQgpAAAAgrg");
	this.shape_28.setTransform(60.475,15.875);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgvAxQgSgTAAgeQAAgdATgTQASgTAcAAQAeAAASASQASATAAAeQAAAegTATQgSATgdAAQgdAAgSgTgAgggoQgMAOAAAaIAAABQAAAZALAPQAMAOAVAAQAWAAAMgOQAMgPAAgZIAAgBQAAgagMgOQgMgOgWAAQgUAAgMAOg");
	this.shape_29.setTransform(44.575,15.725);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("Ag+BTQgIgGAAgKQAAgIAEgFQAEgEAGAAQALAAABAJQACAIgJAGIgFgJQAAANAOAAQAMAAAIgIQAIgKAJgXIAAgBIgyhqQgCgFgEAAIgMAAIAAgNIA4AAIAAANIgNAAQgGAAACAGIAnBUIAkhUQADgGgHAAIgOAAIAAgNIAzAAIAAANIgNAAQgEAAgCAFIgwBvQgKAcgJAJQgMAMgSAAQgMABgIgHg");
	this.shape_30.setTransform(28.875,18.15);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AhKBaIAAgNIARAAQAEABgBgHIAAiKQABgGgEgBIgSAAIAAgMIAMAAQASAAAMgDIgBAhQAOghAjAAQAcAAARASQAPATABAfQAAAegRATQgQASgcABQgigBgOgfIAAA4QAAAHADgBIARAAIAAANgAgVg9QgMAPAAAYIAAACQAAAYANAOQAMAOASAAQAVAAALgOQANgOAAgXIAAgDQAAgagNgOQgLgNgVAAQgTAAgMAOg");
	this.shape_31.setTransform(4.85,17.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgdBbIAAgNIARAAQADAAAAgGIAAiMQAAgHgDAAIgRAAIAAgNIALAAQASAAAKgCIAACiQAAAGAEAAIARAAIAAANg");
	this.shape_32.setTransform(-7.5,13.175);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgsAxQgSgTAAgeQAAgdASgTQASgTAcAAQAcAAAQARQARASAAAeIAAAFIhpAAQAAAXANAOQANAPAUAAQAkAAAIgiIAOAFQgFATgOALQgQAMgYAAQgeAAgRgTgAArgIQgBgWgKgMQgLgNgTAAQgTAAgLANQgMAMgCAWIBVAAIAAAAg");
	this.shape_33.setTransform(-18.95,15.725);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAPBbIAAgNIAPAAQAEAAAAgGIAAhGQAAgegbAAQgSAAgLAQQgKAQgBAcIAAAoQABAGADAAIAQAAIAAANIg8AAIAAgNIARAAQADAAAAgGIAAiMQAAgHgDAAIgSAAIAAgNIAMAAQATAAAKgCIAABSQAOgiAgAAQApAAAAArIAABHQAAAGAEAAIARAAIAAANg");
	this.shape_34.setTransform(-34.7,13.175);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgtAxQgRgTAAgeQAAgdASgTQASgTAdAAQAbAAARARQAQASAAAeIAAAFIhoAAQAAAXAMAOQAMAPAVAAQAkAAAJgiIAMAFQgEATgOALQgPAMgYAAQgeAAgTgTgAAqgIQAAgWgKgMQgLgNgTAAQgSAAgMANQgMAMgBAWIBTAAIAAAAg");
	this.shape_35.setTransform(-57.6,15.725);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAPBbIAAgNIAQAAQADAAAAgGIAAhGQAAgegcAAQgQAAgMAQQgLAQABAcIAAAoQgBAGAEAAIAQAAIAAANIg9AAIAAgNIARAAQAEAAAAgGIAAiMQAAgHgEAAIgRAAIAAgNIAMAAQATAAALgCIAABSQANgiAgAAQApAAAAArIAABHQAAAGAEAAIARAAIAAANg");
	this.shape_36.setTransform(-73.35,13.175);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgIBLQgHgIgBgTIAAhVIgUAAIAAgLIAPgBQAIgBACgIIABgYIAOAAIAAAhIAeAAIAAAMIgeAAIAABVQgBAMAFAFQAEAEALAAQAGAAAIgCIAAANQgJADgLAAQgRAAgIgIg");
	this.shape_37.setTransform(-86.25,14.225);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgHBLQgIgIAAgTIAAhVIgVAAIAAgLIAOgBQAKgBAAgIIACgYIAOAAIAAAhIAeAAIAAAMIgeAAIAABVQAAAMAEAFQAEAEAKAAQAIAAAHgCIAAANQgJADgLAAQgRAAgHgIg");
	this.shape_38.setTransform(-102.6,14.225);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgsAxQgSgTAAgeQAAgdASgTQASgTAcAAQAcAAAQARQARASAAAeIAAAFIhpAAQAAAXANAOQANAPAUAAQAkAAAIgiIAOAFQgFATgOALQgPAMgZAAQgeAAgRgTgAArgIQgBgWgKgMQgLgNgTAAQgTAAgLANQgMAMgCAWIBVAAIAAAAg");
	this.shape_39.setTransform(-114.45,15.725);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("Ag5BEQgVgZAAgrQAAgpAYgaQAWgZAiAAQAXAAAPAKQARAJAGASIADgiIANAAIAABAIgQAAQgKg0gxAAQgaAAgSATQgRAVAAAkIAAADQABAlAQAUQAQAUAcgBQAYAAAPgNQAPgOAAgbIAAgEIgwAAIAAgNIBFAAIAABSIgKAAIgGggQgPAkgvAAQgkAAgWgZg");
	this.shape_40.setTransform(-131.55,13.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD4, new cjs.Rectangle(-202.5,0,405,53), null);


(lib.HEAD3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAKQgEgEAAgGQAAgFAEgEQAEgEAFAAQAGAAAEAEQAEAEAAAFQAAAGgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape.setTransform(152.175,50.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgHBIQgIgIAAgSIAAhRIgUAAIAAgLIAOgBQAJgBABgIIABgXIAOAAIAAAfIAdAAIAAANIgdAAIAABRQAAALADAFQAFAFAKAAQAGAAAHgDIAAANQgIADgKAAQgRAAgHgIg");
	this.shape_1.setTransform(144.8,43.775);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAPBAIAAgMIAOAAQADAAABgFIAAhCQAAgfgaAAQgRAAgLAQQgLAPABAaIAAAoQAAAFADAAIAQAAIAAAMIg7AAIAAgMIARAAQADAAAAgFIAAhZQAAgGgDAAIgRAAIAAgNIALAAQASAAAKgCIAAAhQANghAgAAQAnAAAAArIAABDQAAAFADAAIARAAIAAAMg");
	this.shape_2.setTransform(132.45,45.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgrAvQgRgSAAgdQAAgcASgSQARgTAbAAQAbAAAQARQAQARAAAdIAAAFIhlAAQAAAWAMAOQANAOATAAQAiAAAJggIANAEQgFASgNALQgPAMgYAAQgcAAgSgTgAApgIQAAgVgKgMQgKgMgTAAQgSAAgLAMQgLAMgCAVIBRAAIAAAAg");
	this.shape_3.setTransform(117.125,45.225);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAyBAIAAgMIAOAAQAEAAAAgFIAAg+QAAgSgGgIQgHgJgOAAQgfAAAAAwIAAAxQAAAFADAAIARAAIAAAMIg5AAIAAgMIAPAAQADAAAAgFIAAhBQAAgggaAAQggAAAAAwIAAAxQAAAFAEAAIAPAAIAAAMIg6AAIAAgMIAQAAQAEAAAAgFIAAhZQAAgGgEAAIgQAAIAAgNIALAAQASAAAKgCIAAAaQALgaAbAAQAeAAAGAeQALgeAdAAQAoAAAAAvIAAA/QAAAFAEAAIAQAAIAAAMg");
	this.shape_4.setTransform(98.375,45.075);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgHBIQgIgIAAgSIAAhRIgTAAIAAgLIANgBQAJgBABgIIACgXIANAAIAAAfIAdAAIAAANIgeAAIAABRQAAALAFAFQAEAFAJAAQAHAAAIgDIAAANQgJADgKAAQgRAAgHgIg");
	this.shape_5.setTransform(82.2,43.775);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgzA4QgLgJAAgPQAAgVAVgLQAUgJAtgFIAAgHQAAgRgIgHQgIgIgQAAQgXAAgJAMQAIACAAAJQAAAGgDADQgEADgGAAQgOAAAAgPQAAgOAQgJQAPgJAWAAQAZAAAMALQAMAKAAAXIAABCQAAAGAEAAIAQAAIAAAMIgjAAQgDgLgBgQQgFANgNAJQgNAIgQAAQgSAAgKgKgAgaAHQgRAIAAAPQAAAKAHAGQAHAHAMAAQASAAALgNQALgNABgUIAAgKQgjADgPAHg");
	this.shape_6.setTransform(70.875,45.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgrAvQgRgSAAgdQAAgcASgSQARgTAbAAQAbAAAQARQAQARAAAdIAAAFIhlAAQAAAWAMAOQANAOATAAQAiAAAJggIANAEQgFASgNALQgPAMgYAAQgcAAgSgTgAApgIQAAgVgKgMQgKgMgTAAQgSAAgLAMQgLAMgCAVIBRAAIAAAAg");
	this.shape_7.setTransform(55.975,45.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgxBAIAAgMIARAAQADAAAAgFIAAhZQAAgGgDAAIgSAAIAAgNIALAAQATAAAJgCIAAAeQAKgeAZAAQANAAAGAHQAIAHgBALQAAASgPAAQgFAAgDgDQgEgEAAgEQAAgKAKgCQgCgHgLAAQgPAAgHAPQgIAOAAAXIAAAtQAAAFAEAAIARAAIAAAMg");
	this.shape_8.setTransform(42.85,45.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgHBIQgIgIAAgSIAAhRIgUAAIAAgLIAPgBQAIgBABgIIACgXIANAAIAAAfIAdAAIAAANIgeAAIAABRQAAALAFAFQAEAFAJAAQAHAAAIgDIAAANQgJADgKAAQgRAAgHgIg");
	this.shape_9.setTransform(32.35,43.775);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgrAvQgRgSAAgdQAAgcASgSQARgTAbAAQAbAAAQARQAQARAAAdIAAAFIhlAAQAAAWAMAOQANAOATAAQAiAAAJggIANAEQgFASgNALQgPAMgYAAQgcAAgSgTgAApgIQAAgVgKgMQgKgMgTAAQgSAAgLAMQgLAMgCAVIBRAAIAAAAg");
	this.shape_10.setTransform(13.875,45.225);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgvA2IAAggIAPAAIAAAZQANAHASAAQAfAAAAgXQAAgMgKgFQgHgEgQgDQgVgFgJgFQgOgIAAgRQAAgRANgKQANgKAWAAQAZAAASALIAAAgIgPAAIAAgYQgLgHgRAAQgeAAAAAWQAAAMALAFQAFADASADQAUAEAKAGQANAJAAARQAAARgNAKQgNALgXAAQgZAAgVgMg");
	this.shape_11.setTransform(0.525,45.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgzAXIAAhFQAAgFgEAAIgQAAIAAgNIAoAAIAABWQgBAdAbAAQAQAAALgPQAKgOAAgWIAAguQgBgFgDAAIgQAAIAAgNIAnAAIAABrQAAAGADABIARAAIAAALIgLAAQgSAAgKACIAAgeQgNAfgeABQgoAAAAgqg");
	this.shape_12.setTransform(-13.6,45.35);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrAvQgRgSAAgdQAAgcASgSQARgTAbAAQAbAAAQARQAQARAAAdIAAAFIhlAAQAAAWAMAOQANAOATAAQAiAAAJggIANAEQgFASgNALQgPAMgYAAQgcAAgSgTgAApgIQAAgVgKgMQgKgMgTAAQgSAAgLAMQgLAMgCAVIBRAAIAAAAg");
	this.shape_13.setTransform(-35.625,45.225);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgqAwQgSgSAAgeQAAgdATgSQASgSAcAAQAZAAAPAMQAPAMAAAUQABAIgFAFQgEAFgHAAQgGAAgEgEQgDgDgBgGQABgMANgBQgHgYghAAQgTAAgNAOQgNAOAAAYIAAABQAAAZAMAOQANAOATAAQAjAAAIghIANAFQgLApgtAAQgdAAgRgSg");
	this.shape_14.setTransform(-49.75,45.225);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAPBAIAAgMIAOAAQADAAABgFIAAhCQAAgfgbAAQgQAAgLAQQgKAPAAAaIAAAoQgBAFAEAAIAQAAIAAAMIg7AAIAAgMIAQAAQAEAAAAgFIAAhZQAAgGgEAAIgQAAIAAgNIALAAQASAAAKgCIAAAhQANghAgAAQAnAAAAArIAABDQAAAFADAAIARAAIAAAMg");
	this.shape_15.setTransform(-65,45.075);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgzA4QgLgJAAgPQAAgVAVgLQAUgJAtgFIAAgHQAAgRgIgHQgIgIgQAAQgXAAgJAMQAIACAAAJQAAAGgDADQgEADgGAAQgOAAAAgPQAAgOAQgJQAPgJAWAAQAZAAAMALQAMAKAAAXIAABCQAAAGAEAAIAQAAIAAAMIgjAAQgDgLgBgQQgFANgNAJQgNAIgQAAQgSAAgKgKgAgaAHQgRAIAAAPQAAAKAHAGQAHAHAMAAQASAAALgNQALgNABgUIAAgKQgjADgPAHg");
	this.shape_16.setTransform(-80.175,45.225);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgHBIQgIgIAAgSIAAhRIgTAAIAAgLIANgBQAJgBABgIIACgXIANAAIAAAfIAdAAIAAANIgeAAIAABRQAAALAFAFQAEAFAJAAQAHAAAIgDIAAANQgJADgKAAQgRAAgHgIg");
	this.shape_17.setTransform(-92.4,43.775);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgvA2IAAggIAPAAIAAAZQANAHASAAQAfAAAAgXQAAgMgKgFQgHgEgQgDQgVgFgJgFQgOgIAAgRQAAgRANgKQANgKAWAAQAZAAASALIAAAgIgPAAIAAgYQgLgHgRAAQgeAAAAAWQAAAMALAFQAFADASADQAUAEAKAGQANAJAAARQAAARgNAKQgNALgXAAQgZAAgVgMg");
	this.shape_18.setTransform(-102.825,45.225);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgjA4IgGAeIgNAAQADgOAAgdIAAhuQAAgHgFAAIgQAAIAAgMIALAAQASAAALgCIAABMQAOgeAgAAQAbAAAQASQAQASAAAdQAAAegQASQgQASgbAAQgkAAgNghgAgVgPQgMAOABAXIAAACQgBAYAMAOQANANARAAQAUAAALgNQAMgOAAgYIAAgDQAAgXgMgNQgLgNgUAAQgSAAgMANg");
	this.shape_19.setTransform(-117.45,42.925);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgzAXIAAhFQAAgFgDAAIgRAAIAAgNIAnAAIAABWQAAAdAbAAQAQAAAKgPQAKgOAAgWIAAguQAAgFgDAAIgRAAIAAgNIApAAIAABrQAAAGACABIASAAIAAALIgLAAQgTAAgLACIAAgeQgNAfgdABQgoAAAAgqg");
	this.shape_20.setTransform(-133.25,45.35);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("Ag7BLIAAgpIAQAAIAAAhQAUAJAXAAQASAAALgJQALgIAAgQQAAgPgNgIQgJgHgYgFQgZgGgMgJQgPgLAAgVQAAgWAQgOQARgNAaAAQAdAAAYAMIAAApIgQAAIAAghQgQgHgVAAQgRAAgLAJQgMAIAAAPQAAAPAMAIQAJAHAVAEQAcAGANAJQAQAMAAAVQAAAXgQANQgRAOgbAAQghAAgagOg");
	this.shape_21.setTransform(-148.55,42.875);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgJAKQgEgEAAgGQAAgFAEgEQAEgEAFAAQAGAAAEAEQAEAEAAAFQAAAGgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape_22.setTransform(118.875,22.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgrAvQgRgSAAgdQAAgcASgSQARgTAbAAQAbAAAQARQAQARAAAdIAAAFIhlAAQAAAWAMAOQANAOATAAQAiAAAJggIANAEQgFASgNALQgPAMgYAAQgcAAgSgTgAApgIQAAgVgKgMQgKgMgTAAQgSAAgLAMQgLAMgCAVIBRAAIAAAAg");
	this.shape_23.setTransform(108.825,17.225);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgxBAIAAgMIAQAAQAEAAAAgFIAAhZQAAgGgEAAIgRAAIAAgNIALAAQATAAAKgCIAAAeQAIgeAaAAQAMAAAIAHQAGAHAAALQAAASgPAAQgFAAgDgDQgEgEAAgEQAAgKAKgCQgCgHgLAAQgPAAgHAPQgIAOAAAXIAAAtQAAAFAEAAIAQAAIAAAMg");
	this.shape_24.setTransform(95.7,17.075);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgzA4QgLgJAAgPQAAgVAVgLQAUgJAtgFIAAgHQAAgRgIgHQgIgIgQAAQgXAAgJAMQAIACAAAJQAAAGgDADQgEADgGAAQgOAAAAgPQAAgOAQgJQAPgJAWAAQAZAAAMALQAMAKAAAXIAABCQAAAGAEAAIAQAAIAAAMIgjAAQgDgLgBgQQgFANgNAJQgNAIgQAAQgSAAgKgKgAgaAHQgRAIAAAPQAAAKAHAGQAHAHAMAAQASAAALgNQALgNABgUIAAgKQgjADgPAHg");
	this.shape_25.setTransform(82.675,17.225);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgqAwQgRgSAAgeQAAgdASgSQASgSAcAAQAZAAAPAMQAPAMAAAUQABAIgFAFQgEAFgHAAQgGAAgEgEQgDgDgBgGQABgMANgBQgHgYghAAQgTAAgNAOQgNAOAAAYIAAABQAAAZAMAOQANAOATAAQAjAAAJghIAMAFQgLApgtAAQgdAAgRgSg");
	this.shape_26.setTransform(68.05,17.225);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAPBXIAAgMIAOAAQAEAAAAgFIAAhEQAAgdgaAAQgRAAgKAQQgMAOAAAbIAAAoQAAAFAEAAIAQAAIAAAMIg6AAIAAgMIAQAAQADAAAAgFIAAiIQAAgGgDAAIgRAAIAAgMIALAAQATAAAJgCIAABOQAOggAeAAQAoAAABApIAABFQgBAFAEAAIAQAAIAAAMg");
	this.shape_27.setTransform(45.85,14.775);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgHBIQgIgIAAgSIAAhRIgTAAIAAgLIANgBQAJgBABgIIABgXIAOAAIAAAfIAdAAIAAANIgeAAIAABRQAAALAEAFQAFAFAJAAQAIAAAHgDIAAANQgJADgKAAQgRAAgHgIg");
	this.shape_28.setTransform(33.4,15.775);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgcBXIAAgMIAQAAQADAAABgFIAAiIQgBgGgDAAIgQAAIAAgMIALAAQARAAAKgCIAACcQAAAFADAAIAQAAIAAAMg");
	this.shape_29.setTransform(25.15,14.775);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgzA4QgLgJAAgPQAAgVAVgLQAUgJAtgFIAAgHQAAgRgIgHQgIgIgQAAQgXAAgJAMQAIACAAAJQAAAGgDADQgEADgGAAQgOAAAAgPQAAgOAQgJQAPgJAWAAQAZAAAMALQAMAKAAAXIAABCQAAAGAEAAIAQAAIAAAMIgjAAQgDgLgBgQQgFANgNAJQgNAIgQAAQgSAAgKgKgAgaAHQgRAIAAAPQAAAKAHAGQAHAHAMAAQASAAALgNQALgNABgUIAAgKQgjADgPAHg");
	this.shape_30.setTransform(14.225,17.225);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgrAvQgRgSAAgdQAAgcASgSQARgTAbAAQAbAAAQARQAQARAAAdIAAAFIhlAAQAAAWAMAOQANAOATAAQAiAAAJggIANAEQgFASgNALQgPAMgYAAQgcAAgSgTgAApgIQAAgVgKgMQgKgMgTAAQgSAAgLAMQgLAMgCAVIBRAAIAAAAg");
	this.shape_31.setTransform(-0.675,17.225);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAOBXIAAgMIAPAAQAEAAAAgFIAAhEQAAgdgaAAQgRAAgLAQQgKAOgBAbIAAAoQABAFADAAIAQAAIAAAMIg6AAIAAgMIAQAAQADAAAAgFIAAiIQAAgGgDAAIgRAAIAAgMIALAAQASAAAKgCIAABOQAOggAeAAQApAAAAApIAABFQgBAFAEAAIAQAAIAAAMg");
	this.shape_32.setTransform(-15.9,14.775);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgcBXIAAgMIAQAAQADAAABgFIAAiIQgBgGgDAAIgQAAIAAgMIALAAQARAAAKgCIAACcQAAAFADAAIAQAAIAAAMg");
	this.shape_33.setTransform(-34.8,14.775);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgzA4QgLgJAAgPQAAgVAVgLQAUgJAtgFIAAgHQAAgRgIgHQgIgIgQAAQgXAAgJAMQAIACAAAJQAAAGgDADQgEADgGAAQgOAAAAgPQAAgOAQgJQAPgJAWAAQAZAAAMALQAMAKAAAXIAABCQAAAGAEAAIAQAAIAAAMIgjAAQgDgLgBgQQgFANgNAJQgNAIgQAAQgSAAgKgKgAgaAHQgRAIAAAPQAAAKAHAGQAHAHAMAAQASAAALgNQALgNABgUIAAgKQgjADgPAHg");
	this.shape_34.setTransform(-45.725,17.225);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgHBIQgIgIAAgSIAAhRIgTAAIAAgLIANgBQAJgBABgIIABgXIAOAAIAAAfIAdAAIAAANIgeAAIAABRQAAALAEAFQAFAFAJAAQAIAAAHgDIAAANQgJADgKAAQgRAAgHgIg");
	this.shape_35.setTransform(-57.95,15.775);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAOBAIAAgMIAPAAQADAAAAgFIAAhCQAAgfgaAAQgQAAgLAQQgKAPAAAaIAAAoQgBAFAEAAIAQAAIAAAMIg7AAIAAgMIAQAAQAEAAAAgFIAAhZQAAgGgEAAIgQAAIAAgNIALAAQATAAAJgCIAAAhQANghAgAAQAnAAAAArIAABDQAAAFAEAAIAQAAIAAAMg");
	this.shape_36.setTransform(-70.3,17.075);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgrAvQgRgSAAgdQAAgcASgSQARgTAbAAQAbAAAQARQAQARAAAdIAAAFIhlAAQAAAWAMAOQANAOATAAQAiAAAJggIANAEQgFASgNALQgPAMgYAAQgcAAgSgTgAApgIQAAgVgKgMQgKgMgTAAQgSAAgLAMQgLAMgCAVIBRAAIAAAAg");
	this.shape_37.setTransform(-85.625,17.225);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgKBXIg7idIAACKQAAAGAEAAIARAAIAAAMIg4AAIAAgMIASAAQAEAAAAgGIAAiIQAAgGgEABIgSAAIAAgNIAyAAIA2COIA4iOIAxAAIAAANIgRAAQgEgBAAAGIAACIQAAAGAEAAIARAAIAAAMIg9AAIAAgMIARAAQAEAAAAgGIAAiLIg/Ceg");
	this.shape_38.setTransform(-104.325,14.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD3, new cjs.Rectangle(-206,2,412,58), null);


(lib.HEAD1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAKQgEgEAAgGQAAgFAEgEQAEgEAFAAQAGAAAEAEQAEAEAAAFQAAAGgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape.setTransform(101.725,50.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgrAvQgRgSAAgdQAAgcASgSQARgTAbAAQAbAAAQARQAQARAAAdIAAAFIhlAAQAAAWAMAOQANAOATAAQAiAAAJggIANAEQgFASgNALQgPAMgYAAQgcAAgSgTgAApgIQAAgVgKgMQgKgMgTAAQgSAAgLAMQgLAMgCAVIBRAAIAAAAg");
	this.shape_1.setTransform(91.675,45.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAOBAIAAgMIAPAAQADAAABgFIAAhCQgBgfgaAAQgQAAgLAQQgKAPAAAaIAAAoQgBAFAEAAIAQAAIAAAMIg7AAIAAgMIAQAAQAEAAAAgFIAAhZQAAgGgEAAIgQAAIAAgNIALAAQATAAAJgCIAAAhQANghAgAAQAnAAAAArIAABDQAAAFAEAAIAQAAIAAAMg");
	this.shape_2.setTransform(76.4,45.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgtAvQgRgSgBgdQAAgcASgTQASgSAcAAQAcAAARASQARASABAdQgBAdgRASQgSATgcAAQgcAAgRgTgAgfgmQgLANAAAZIAAABQAAAYALAOQALAOAUAAQAVAAALgOQAMgOAAgYIAAgBQAAgZgMgNQgLgOgUAAQgVAAgLAOg");
	this.shape_3.setTransform(60.75,45.225);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgdBXIAAgMIARAAQAEAAgBgFIAAiIQABgGgEAAIgRAAIAAgMIAMAAQARAAAKgCIAACcQAAAFAEAAIAQAAIAAAMg");
	this.shape_4.setTransform(49.3,42.775);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgzA4QgLgJAAgPQAAgVAVgLQAUgJAtgFIAAgHQAAgRgIgHQgIgIgQAAQgXAAgJAMQAIACAAAJQAAAGgDADQgEADgGAAQgOAAAAgPQAAgOAQgJQAPgJAWAAQAZAAAMALQAMAKAAAXIAABCQAAAGAEAAIAQAAIAAAMIgjAAQgDgLgBgQQgFANgNAJQgNAIgQAAQgSAAgKgKgAgaAHQgRAIAAAPQAAAKAHAGQAHAHAMAAQASAAALgNQALgNABgUIAAgKQgjADgPAHg");
	this.shape_5.setTransform(38.375,45.225);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgHBIQgIgIAAgSIAAhRIgUAAIAAgLIAPgBQAIgBABgIIABgXIAOAAIAAAfIAdAAIAAANIgdAAIAABRQAAALADAFQAFAFAKAAQAHAAAGgDIAAANQgIADgKAAQgRAAgHgIg");
	this.shape_6.setTransform(19.15,43.775);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgtAvQgSgSAAgdQABgcARgTQASgSAbAAQAcAAASASQARASAAAdQAAAdgRASQgSATgcAAQgbAAgSgTgAgfgmQgMANAAAZIAAABQAAAYAMAOQALAOAUAAQAVAAAMgOQALgOAAgYIAAgBQAAgZgLgNQgMgOgVAAQgTAAgMAOg");
	this.shape_7.setTransform(7.35,45.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAOBAIAAgMIAPAAQADAAAAgFIAAhCQAAgfgaAAQgQAAgLAQQgKAPAAAaIAAAoQgBAFAEAAIAQAAIAAAMIg7AAIAAgMIAQAAQAEAAAAgFIAAhZQAAgGgEAAIgQAAIAAgNIALAAQATAAAJgCIAAAhQANghAgAAQAnAAAAArIAABDQAAAFAEAAIAQAAIAAAMg");
	this.shape_8.setTransform(-8.2,45.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgrAvQgRgSAAgdQAAgcASgSQARgTAbAAQAbAAAQARQAQARAAAdIAAAFIhlAAQAAAWAMAOQANAOATAAQAiAAAJggIANAEQgFASgNALQgPAMgYAAQgcAAgSgTgAApgIQAAgVgKgMQgKgMgTAAQgSAAgLAMQgLAMgCAVIBRAAIAAAAg");
	this.shape_9.setTransform(-30.525,45.225);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgxBAIAAgMIARAAQADAAAAgFIAAhZQAAgGgDAAIgRAAIAAgNIAKAAQASAAAKgCIAAAeQAKgeAZAAQANAAAGAHQAIAHgBALQAAASgPAAQgFAAgEgDQgDgEAAgEQAAgKAKgCQgCgHgLAAQgPAAgHAPQgIAOAAAXIAAAtQAAAFAEAAIARAAIAAAMg");
	this.shape_10.setTransform(-43.65,45.075);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgRAZIAAgKIAGAAQAQABAAgRIAAgDQgEAEgFAAQgMAAAAgMQAAgGAEgEQAEgDAHAAQAHAAAGAGQAGAIAAAJQAAAMgHAIQgIAIgMAAg");
	this.shape_11.setTransform(-52.475,36.55);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgzAXIAAhFQAAgFgEAAIgPAAIAAgNIAmAAIAABWQAAAdAbAAQAQAAAKgPQALgOgBgWIAAguQAAgFgDAAIgQAAIAAgNIAnAAIAABrQAAAGAEABIARAAIAAALIgMAAQgSAAgLACIAAgeQgNAfgdABQgoAAAAgqg");
	this.shape_12.setTransform(-63.35,45.35);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgtAvQgSgSAAgdQABgcARgTQASgSAbAAQAcAAASASQARASAAAdQAAAdgRASQgSATgcAAQgcAAgRgTgAgfgmQgMANAAAZIAAABQABAYAKAOQAMAOAUAAQAVAAAMgOQALgOAAgYIAAgBQAAgZgLgNQgMgOgVAAQgTAAgMAOg");
	this.shape_13.setTransform(-78.7,45.225);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag8BRQgIgHAAgJQAAgIAEgEQAEgFAHAAQAJAAACAIQACAJgJAGIgFgIQAAALAOAAQALAAAHgIQAIgJAJgWIAAgBIgwhmQgDgFgDAAIgLAAIAAgNIA2AAIAAANIgNAAQgGAAACAFIAlBRIAjhQQADgGgGAAIgOAAIAAgNIAxAAIAAANIgMAAQgEAAgCAFIguBqQgKAbgJAJQgKAMgSAAQgMAAgIgFg");
	this.shape_14.setTransform(-93.85,47.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1copy, new cjs.Rectangle(-211.9,2,427.9,58), null);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgRAZIAAgKIAGAAQAQAAAAgQIAAgDQgEAEgFAAQgMAAAAgMQAAgGAEgEQAEgDAHAAQAHAAAGAGQAGAHAAAKQAAAMgHAIQgIAIgMAAg");
	this.shape.setTransform(202.425,23.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgrAvQgRgSAAgdQAAgcASgSQARgTAbAAQAbAAAQARQAQARAAAdIAAAFIhlAAQAAAWAMAOQANAOATAAQAiAAAJggIANAEQgFASgNALQgPAMgYAAQgcAAgSgTgAApgIQAAgVgKgMQgKgMgTAAQgSAAgLAMQgLAMgCAVIBRAAIAAAAg");
	this.shape_1.setTransform(192.325,17.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAyBAIAAgMIAOAAQAEAAAAgFIAAg+QAAgSgGgIQgHgJgOAAQgfAAAAAwIAAAxQAAAFADAAIARAAIAAAMIg5AAIAAgMIAPAAQADAAAAgFIAAhBQAAgggaAAQggAAAAAwIAAAxQAAAFAEAAIAPAAIAAAMIg6AAIAAgMIAQAAQAEAAAAgFIAAhZQAAgGgEAAIgQAAIAAgNIALAAQASAAAKgCIAAAaQALgaAbAAQAeAAAGAeQALgeAdAAQAoAAAAAvIAAA/QAAAFAEAAIAQAAIAAAMg");
	this.shape_2.setTransform(173.575,17.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgtAvQgSgSABgdQAAgcARgTQASgSAbAAQAcAAASASQARASAAAdQAAAdgRASQgSATgcAAQgcAAgRgTgAgfgmQgMANAAAZIAAABQABAYAKAOQAMAOAUAAQAVAAAMgOQALgOAAgYIAAgBQAAgZgLgNQgMgOgVAAQgTAAgMAOg");
	this.shape_3.setTransform(154.4,17.225);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAOBXIAAgMIAPAAQAEAAAAgFIAAhEQAAgdgaAAQgRAAgLAQQgKAOgBAbIAAAoQABAFADAAIAQAAIAAAMIg6AAIAAgMIAQAAQADAAAAgFIAAiIQAAgGgDAAIgRAAIAAgMIALAAQASAAAKgCIAABOQAOggAeAAQApAAAAApIAABFQgBAFAEAAIAQAAIAAAMg");
	this.shape_4.setTransform(138.9,14.775);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgHBIQgIgIAAgSIAAhRIgTAAIAAgLIANgBQAJgBABgIIACgXIANAAIAAAfIAdAAIAAANIgeAAIAABRQAAALAFAFQAEAFAJAAQAIAAAHgDIAAANQgJADgKAAQgRAAgHgIg");
	this.shape_5.setTransform(119.45,15.775);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgzA4QgLgJAAgPQAAgVAVgLQAUgJAtgFIAAgHQAAgRgIgHQgIgIgQAAQgXAAgJAMQAIACAAAJQAAAGgDADQgEADgGAAQgOAAAAgPQAAgOAQgJQAPgJAWAAQAZAAAMALQAMAKAAAXIAABCQAAAGAEAAIAQAAIAAAMIgjAAQgDgLgBgQQgFANgNAJQgNAIgQAAQgSAAgKgKgAgaAHQgRAIAAAPQAAAKAHAGQAHAHAMAAQASAAALgNQALgNABgUIAAgKQgjADgPAHg");
	this.shape_6.setTransform(108.125,17.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAMBXIAAgMIAOAAQAFAAgDgEIgdgyIgbAbIAAAWQAAAFAEAAIAQAAIAAAMIg7AAIAAgMIARAAQADAAAAgFIAAiIQAAgGgDAAIgRAAIAAgMIALAAQASAAAKgCIAAB3IA0g2IABgDQAAAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgQAAIAAgNIA6AAIAAANIgNAAQgFAAgEAEIgfAdIAnA/QADAEAEAAIALAAIAAAMg");
	this.shape_7.setTransform(85.925,14.775);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgqAwQgRgSAAgeQAAgdASgSQASgSAcAAQAZAAAPAMQAPAMAAAUQAAAIgEAFQgFAFgGAAQgGAAgEgEQgDgDAAgGQgBgMANgBQgGgYghAAQgUAAgMAOQgMAOAAAYIAAABQAAAZALAOQAMAOAVAAQAiAAAJghIAMAFQgKApguAAQgdAAgRgSg");
	this.shape_8.setTransform(71.45,17.225);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgzAXIAAhFQAAgFgDAAIgRAAIAAgNIAnAAIAABWQAAAdAbAAQAQAAAKgPQALgOAAgWIAAguQAAgFgEAAIgRAAIAAgNIApAAIAABrQAAAGACABIASAAIAAALIgLAAQgTAAgKACIAAgeQgOAfgdAAQgoAAAAgpg");
	this.shape_9.setTransform(56.3,17.35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgHBIQgIgIAAgSIAAhRIgTAAIAAgLIANgBQAJgBABgIIACgXIANAAIAAAfIAdAAIAAANIgeAAIAABRQAAALAFAFQAEAFAJAAQAHAAAIgDIAAANQgJADgKAAQgRAAgHgIg");
	this.shape_10.setTransform(43.95,15.775);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgvA2IAAggIAPAAIAAAZQANAHASAAQAfAAAAgXQAAgMgKgFQgHgEgQgDQgVgFgJgFQgOgIAAgRQAAgRANgKQANgKAWAAQAZAAASALIAAAgIgPAAIAAgYQgLgHgRAAQgeAAAAAWQAAAMALAFQAFADASADQAUAEAKAGQANAJAAARQAAARgNAKQgNALgXAAQgZAAgVgMg");
	this.shape_11.setTransform(33.525,17.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgrAvQgRgSAAgdQAAgcASgSQARgTAbAAQAbAAAQARQAQARAAAdIAAAFIhlAAQAAAWAMAOQANAOATAAQAiAAAJggIANAEQgFASgNALQgPAMgYAAQgcAAgSgTgAApgIQAAgVgKgMQgKgMgTAAQgSAAgLAMQgLAMgCAVIBRAAIAAAAg");
	this.shape_12.setTransform(13.175,17.225);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgxBAIAAgMIAQAAQAEAAAAgFIAAhZQAAgGgEAAIgRAAIAAgNIAMAAQARAAALgCIAAAeQAIgeAaAAQAMAAAIAHQAGAHABALQAAASgQAAQgFAAgDgDQgEgEAAgEQAAgKAKgCQgCgHgLAAQgPAAgHAPQgIAOAAAXIAAAtQAAAFAEAAIAQAAIAAAMg");
	this.shape_13.setTransform(0.05,17.075);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgRAZIAAgKIAGAAQAQABAAgRIAAgDQgEAEgFAAQgMAAAAgMQAAgGAEgEQAEgDAHAAQAHAAAGAGQAGAHAAAKQAAAMgHAIQgIAIgMAAg");
	this.shape_14.setTransform(-8.775,8.55);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgzAXIAAhFQAAgFgEAAIgQAAIAAgNIAoAAIAABWQAAAdAaAAQAQAAALgPQAJgOABgWIAAguQAAgFgEAAIgRAAIAAgNIApAAIAABrQAAAGACABIARAAIAAALIgKAAQgTAAgKACIAAgeQgNAfgeAAQgoAAAAgpg");
	this.shape_15.setTransform(-19.65,17.35);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgtAvQgRgSAAgdQgBgcATgTQARgSAcAAQAcAAARASQASASAAAdQAAAdgSASQgSATgcAAQgcAAgRgTgAgfgmQgLANAAAZIAAABQgBAYALAOQANAOATAAQAVAAALgOQAMgOAAgYIAAgBQAAgZgMgNQgLgOgUAAQgVAAgLAOg");
	this.shape_16.setTransform(-35,17.225);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("Ag8BRQgIgHAAgJQAAgIAEgEQAEgFAGAAQALAAABAIQACAJgJAGIgGgIQAAALAPAAQALAAAIgIQAHgJAKgWIAAgCIgxhlQgCgFgDAAIgMAAIAAgNIA1AAIAAANIgMAAQgGAAACAFIAmBRIAjhQQACgGgHAAIgNAAIAAgNIAxAAIAAANIgMAAQgEAAgCAFIguBqQgKAbgIAKQgLALgSAAQgMAAgIgFg");
	this.shape_17.setTransform(-50.15,19.55);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAOBAIAAgMIAPAAQADAAAAgFIAAhCQAAgfgaAAQgQAAgLAQQgKAPAAAaIAAAoQAAAFADAAIAQAAIAAAMIg7AAIAAgMIAQAAQAEAAAAgFIAAhZQAAgGgEAAIgQAAIAAgNIALAAQATAAAJgCIAAAhQANghAgAAQAnAAAAArIAABDQAAAFAEAAIAQAAIAAAMg");
	this.shape_18.setTransform(-72.9,17.075);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgrAvQgRgSAAgdQAAgcASgSQARgTAbAAQAbAAAQARQAQARAAAdIAAAFIhlAAQAAAWAMAOQANAOATAAQAiAAAJggIANAEQgFASgNALQgPAMgYAAQgcAAgSgTgAApgIQAAgVgKgMQgKgMgTAAQgSAAgLAMQgLAMgCAVIBRAAIAAAAg");
	this.shape_19.setTransform(-88.225,17.225);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAPBXIAAgMIAOAAQAEAAAAgFIAAhEQAAgdgaAAQgRAAgKAQQgMAOAAAbIAAAoQAAAFAEAAIAQAAIAAAMIg7AAIAAgMIARAAQADAAAAgFIAAiIQAAgGgDAAIgRAAIAAgMIALAAQATAAAJgCIAABOQAOggAeAAQAoAAABApIAABFQAAAFADAAIAQAAIAAAMg");
	this.shape_20.setTransform(-103.45,14.775);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAlBAIgkhlIgjBlIgPAAIgkhtQgCgFgDAAIgNAAIAAgNIA3AAIAAANIgNAAQgGAAACAFIAbBUIAdhUQADgFgHAAIgJAAIAAgNIA0AAIAAANIgKAAQgHAAACAFIAfBVIAbhUQACgGgHAAIgNAAIAAgNIAxAAIAAANIgMAAQgEAAgCAFIgkBtg");
	this.shape_21.setTransform(-122.4,17.275);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAPBAIAAgMIAOAAQAEAAAAgFIAAhCQAAgfgaAAQgRAAgLAQQgLAPAAAaIAAAoQAAAFAEAAIAQAAIAAAMIg7AAIAAgMIARAAQADAAAAgFIAAhZQAAgGgDAAIgRAAIAAgNIALAAQASAAAKgCIAAAhQANghAfAAQAoAAAAArIAABDQAAAFADAAIARAAIAAAMg");
	this.shape_22.setTransform(-148.45,17.075);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgrAvQgRgSAAgdQAAgcASgSQARgTAbAAQAbAAAQARQAQARAAAdIAAAFIhlAAQAAAWAMAOQANAOATAAQAiAAAJggIANAEQgFASgNALQgPAMgYAAQgcAAgSgTgAApgIQAAgVgKgMQgKgMgTAAQgSAAgLAMQgLAMgCAVIBRAAIAAAAg");
	this.shape_23.setTransform(-163.775,17.225);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgFBAIguhtQgCgFgEAAIgNAAIAAgNIA5AAIAAANIgPAAQgGAAACAFIAjBXIAkhWQACgGgHAAIgPAAIAAgNIA0AAIAAANIgMAAQgFAAgCAFIgtBtg");
	this.shape_24.setTransform(-178.65,17.275);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AhBBWIAAgMIARAAQAEAAAAgGIAAiIQAAgFgEAAIgRAAIAAgMIB+AAIAAAlIgOAAIgBgUQgCgFgIAAIg9AAIAABDIAnAAQAGAAAAgGIAAgNIAMAAIAAAwIgMAAIAAgNQAAgFgGAAIgnAAIAABFIBDAAQAIAAACgGIABgTIANAAIAAAlg");
	this.shape_25.setTransform(-194.575,14.875);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(-211.9,2,427.9,30), null);


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgtAPIAUgPIgUgPIAAgZIAuAiIAAANIguAigAADANIATgNIgTgMIAAgYIArAeIAAANIgrAeg");
	this.shape.setTransform(26.05,54.85);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgJA1QgHgGAAgPIAAgzIgMAAIAAgNIAHgBQALgCAAgIIACgRIARAAIAAAaIASAAIAAAPIgTAAIAAAyQABANAMAAIAIgBIAAAPQgIACgIABQgPAAgHgIg");
	this.shape_1.setTransform(11.05,55.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgpAwIAAgPIAIAAQAEAAAAgEIAAg1QAAgGgEAAIgJAAIAAgOIAQAAQANAAAJgCIAAAVQAFgWATAAQALABAFAFQAHAHAAAKQAAAJgGAGQgFAFgHAAQgGAAgEgEQgEgEAAgEQABgKAIgDQgCgBgEgBQgSAAAAAfIAAAdQAAAEAEAAIAIAAIAAAPg");
	this.shape_2.setTransform(2.75,56.45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgjAjQgNgNAAgWQAAgVAOgNQANgOAWAAQAVAAAOAOQANANAAAVQAAAWgNANQgOAOgWAAQgVAAgOgOgAgWAAIAAABQAAAhAWAAQAYAAAAghIAAgBQAAghgYAAQgWAAAAAhg");
	this.shape_3.setTransform(-8.075,56.575);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag2BAIAAgOIAJAAQADAAAAgFIAAhVQAAgGgDAAIgJAAIAAgOIAPAAQAOAAAIgCIAAAUQAJgVAXAAQASAAALAOQALANAAAWQAAAVgLANQgMAOgSAAQgWAAgJgUIAAAfQAAAFAEAAIAIAAIAAAOgAgKgnQgHAIAAAQIAAACQAAAOAHAJQAGAHAJAAQALAAAGgHQAHgJAAgOIAAgCQAAgPgHgJQgGgHgLAAQgJAAgGAHg");
	this.shape_4.setTransform(-20.225,58.075);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag2BAIAAgOIAJAAQADAAAAgFIAAhVQAAgGgDAAIgJAAIAAgOIAPAAQAOAAAIgCIAAAUQAJgVAXAAQASAAALAOQALANAAAWQAAAVgLANQgMAOgSAAQgWAAgJgUIAAAfQAAAFAEAAIAIAAIAAAOgAgKgnQgHAIAAAQIAAACQAAAOAHAJQAGAHAJAAQALAAAGgHQAHgJAAgOIAAgCQAAgPgHgJQgGgHgLAAQgJAAgGAHg");
	this.shape_5.setTransform(-32.775,58.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgqANIAAgpQgBgEgDAAIgIAAIAAgPIAlAAIAAA8QAAASAPAAQATAAAAgbIAAggQAAgEgDAAIgJAAIAAgPIAmAAIAABIQAAAFADABIAJAAIAAAOIgPAAQgOAAgJACIAAgRQgJASgUAAQgeAAAAgjg");
	this.shape_6.setTransform(-45.1,56.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgmApIAAgZIATAAIAAARQAGACALAAQARAAAAgMQAAgGgGgDQgEgDgKgCQgQgDgHgEQgKgGAAgOQAAgNAKgIQALgJATAAQATAAAPAIIAAAYIgTAAIAAgQQgFgCgKAAQgRAAAAAMQAAAGAHADQADABALACQAQAEAHAEQAKAGAAAOQAAAOgLAIQgLAJgTAAQgRAAgTgIg");
	this.shape_7.setTransform(-55.925,56.575);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgrA0QgLgNAAgXQAAgVALgNQAMgNASAAQAXAAAIASIAAgdQAAgGgDAAIgJAAIAAgOIAPAAQAOAAAIgCIAABsQAAAEAEAAIAIAAIAAAPIgiAAIgCgSQgIAUgXAAQgTAAgMgNgAgVgHQgGAHAAAPIAAADQAAAPAGAIQAGAIALAAQAJAAAGgIQAHgIAAgPIAAgDQAAgPgHgHQgGgIgJAAQgLAAgGAIg");
	this.shape_8.setTransform(-4.425,34.925);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAHAwIAAgPIAHAAQAEAAAAgEIAAgpQAAgSgQAAQgTAAAAAeIAAAdQAAAEAEAAIAHAAIAAAPIgwAAIAAgPIAIAAQAEAAAAgEIAAg1QAAgGgEAAIgIAAIAAgOIAPAAQAOAAAIgCIAAASQAJgSAVgBQAeAAAAAjIAAApQAAAEAEAAIAIAAIAAAPg");
	this.shape_9.setTransform(-16.925,36.45);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgXBCIAAgOIAIAAQADAAAAgFIAAgzQAAgHgEAAIgHAAIAAgOIAPAAQAMAAAJgCIAABKQAAAFADAAIAIAAIAAAOgAgKgmQgFgFAAgHQAAgGAFgFQAEgEAGAAQAHAAAFAEQAEAFAAAGQAAAHgEAFQgFAEgHAAQgGAAgEgEg");
	this.shape_10.setTransform(-26.425,34.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgxA/IAAgOIAJAAQAEgBAAgFIAAhWQAAgFgEAAIgJAAIAAgOIBjAAIAAAgIgQAAIgCgMQgBgEgDgBIgIgBIgeAAIAAAtIAUAAQAFAAAAgHIAAgHIAPAAIAAAoIgPAAIAAgHQAAgHgFAAIgUAAIAAAiQAAAFAEABIAJAAIAAAOg");
	this.shape_11.setTransform(-35.825,34.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#7BAFD4").s().p("ApqHCIAAuDITVAAIAAODg");
	this.shape_12.setTransform(-19.35,45);

	this.timeline.addTween(cjs.Tween.get(this.shape_12).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTA, new cjs.Rectangle(-81.4,0,124,90), null);


(lib.CPCCOlogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AglAmQgPgPAAgXQAAgWAPgPQAPgPAWAAQAXAAAPAPQAPAPAAAWQAAAXgPAPQgPAPgXAAQgWAAgPgPgAgVgXQgJAJAAAOQAAAOAJAKQAIAJANAAQAOAAAJgJQAIgKAAgOQAAgOgIgJQgJgKgOAAQgNAAgIAKg");
	this.shape.setTransform(60.5029,11.3517,0.9528,0.9528);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggAmQgPgPgBgXQAAgWAQgPQAPgPAWAAQAeAAANAZIgSAJQgIgPgRAAQgMAAgJAKQgJAKAAANQAAAOAJAKQAJAJAMAAQARAAAIgOIASAJQgOAZgdAAQgWAAgPgPg");
	this.shape_1.setTransform(50.5701,11.3517,0.9528,0.9528);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggAmQgPgPAAgXQAAgWAPgPQAQgPAVAAQAeAAAOAZIgTAJQgHgPgSAAQgMAAgJAKQgJAKAAANQAAAOAJAKQAJAJAMAAQASAAAHgOIATAJQgOAZgeAAQgVAAgQgPg");
	this.shape_2.setTransform(41.0899,11.3517,0.9528,0.9528);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWAcQgLgLAAgRQAAgQALgLQALgLAQAAQAUAAAJAOIgNALQgFgIgKAAQgIAAgGAGQgFAGAAAJQAAAJAFAGQAGAGAIAAQAKAAAFgIIANAMQgJAOgUAAQgQAAgLgLg");
	this.shape_3.setTransform(29.1085,12.6856,0.9528,0.9528);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AASA2IAAhJIAUAAIAABJgAgaA2IAAg4IgNAAIAAgRIANAAIAAgEQAAgMAHgGQAHgIALAAQAIAAAFADIgEAOQgDgBgEAAQgIAAAAAKIAAAEIAOAAIAAARIgOAAIAAA4gAAUghQgEgEAAgEQAAgFAEgDQADgEAFAAQAFAAADAEQAEADAAAFQAAAEgEAEQgDAEgFgBQgFABgDgEg");
	this.shape_4.setTransform(21.2957,11.042,0.9528,0.9528);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgJA2IAAhJIATAAIAABJgAgHghQgEgEAAgEQAAgFAEgDQADgEAEAAQAFAAADAEQAEADAAAFQAAAEgEAEQgDAEgFgBQgEABgDgEg");
	this.shape_5.setTransform(15.9124,11.042,0.9528,0.9528);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgWAcQgLgLAAgRQAAgQALgLQALgLAQAAQAUAAAJAOIgNALQgFgIgKAAQgIAAgFAGQgGAGAAAJQAAAJAGAGQAFAGAIAAQAKAAAFgIIANAMQgJAOgUAAQgQAAgLgLg");
	this.shape_6.setTransform(11.0294,12.6856,0.9528,0.9528);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgZAhQgIgHAAgMQAAgMAIgFQAHgFAKAAQAPAAAIAIIAAgKQAAgFgFgEQgEgDgGAAQgNAAgJAJIgHgNQANgMASAAQAgAAAAAcIAAAvIgTAAIAAgIQgIAKgPAAQgJAAgIgGgAgKAGQgEAEAAAFQAAAFAEADQAEADAGAAQAKAAAFgHIAAgJQgFgHgKAAQgGAAgEADg");
	this.shape_7.setTransform(3.5738,12.6856,0.9528,0.9528);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgoAzIAAhlIAvAAQAPAAAKAKQAJAJAAAOQAAANgJAJQgKAKgPAAIgZAAIAAAkgAgSgDIAVAAQAHAAAEgEQAEgEABgGQgBgHgEgDQgEgFgHAAIgVAAg");
	this.shape_8.setTransform(-3.8818,11.3278,0.9528,0.9528);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgZAhQgIgHAAgMQAAgMAIgFQAHgFAKAAQAPAAAIAIIAAgKQAAgFgFgEQgEgDgGAAQgNAAgJAJIgHgNQANgMASAAQAgAAAAAcIAAAvIgTAAIAAgIQgIAKgPAAQgJAAgIgGgAgKAGQgEAEAAAFQAAAFAEADQAEADAGAAQAKAAAFgHIAAgJQgFgHgKAAQgGAAgEADg");
	this.shape_9.setTransform(-16.2919,12.6856,0.9528,0.9528);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgJA2IAAhJIATAAIAABJgAgHghQgDgEgBgEQABgFADgDQAEgEADAAQAFAAADAEQAEADAAAFQAAAEgEAEQgDAEgFgBQgDABgEgEg");
	this.shape_10.setTransform(-21.4131,11.042,0.9528,0.9528);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgRApIAAAJIgUAAIAAhlIAUAAIAAAlQAJgKANgBQAPAAAJALQAIALABAQQAAASgKALQgJAKgOAAQgMAAgKgLgAgRAAIAAAaQAGAJALAAQAHAAAGgHQAEgFAAgKQAAgKgEgEQgGgHgHAAQgLAAgGAIg");
	this.shape_11.setTransform(-26.8917,11.4231,0.9528,0.9528);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAkAmIAAguQAAgMgLAAQgJAAgGAJIAAAxIgTAAIAAguQAAgMgLAAQgJAAgGAJIAAAxIgUAAIAAhJIAUAAIAAAKQACgEAHgEQAHgEAIAAQAPAAAFAOQADgGAHgEQAHgEAIAAQAWAAAAAWIAAA1g");
	this.shape_12.setTransform(-37.158,12.5903,0.9528,0.9528);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AghAOIAAgzIATAAIAAAsQAAAOANAAQAKAAAGgJIAAgxIATAAIAABJIgTAAIAAgJQgKALgPAAQgXAAAAgYg");
	this.shape_13.setTransform(-47.1384,12.757,0.9528,0.9528);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgJAzIAAhlIATAAIAABlg");
	this.shape_14.setTransform(-52.7361,11.3278,0.9528,0.9528);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgcAbQgKgLAAgQQAAgPAKgLQALgMARAAQASAAALAMQAKAKAAAQQAAAQgKALQgLAMgSAAQgRAAgLgMgAgNgOQgFAGAAAIQAAAJAFAGQAFAGAIAAQAJAAAFgGQAFgGAAgJQAAgIgFgGQgFgHgJAAQgIAAgFAHg");
	this.shape_15.setTransform(-58.3575,12.6856,0.9528,0.9528);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AggAmQgQgPAAgXQAAgWAQgPQAPgPAWAAQAdAAAPAZIgTAJQgHgPgSAAQgMAAgJAKQgJAJAAAOQAAAOAJAKQAJAJAMAAQASAAAHgOIATAJQgPAZgdAAQgWAAgPgPg");
	this.shape_16.setTransform(-67.1232,11.3517,0.9528,0.9528);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgTAgIACgJIAEAAQAFAAACgEIACgFIgTgtIAKAAIANAhIAOghIAKAAIgWA0QgDALgMAAg");
	this.shape_17.setTransform(55.0006,30.2883,0.9528,0.9528);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgEAgIAAg+IAJAAIAAA+g");
	this.shape_18.setTransform(51.6658,28.5733,0.9528,0.9528);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgEAhIAAgtIAJAAIAAAtgAgFgaQAAgGAFAAQAGAAAAAGQAAAGgGAAQgFAAAAgGg");
	this.shape_19.setTransform(49.4744,28.4542,0.9528,0.9528);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAXAYIAAgeQAAgHgHgBQgHABgEAFIAAAgIgIAAIAAgeQAAgHgIgBQgGABgFAFIAAAgIgKAAIAAgtIAKAAIAAAGQAFgIAKAAQAJAAADAJQAFgJAKAAQANAAAAAPIAAAgg");
	this.shape_20.setTransform(44.6152,29.3356,0.9528,0.9528);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgOAVQgFgFAAgHQAAgIAFgDQAEgDAGAAQAJAAAFAFIAAgGQAAgIgKAAQgHAAgGAFIgEgGQAIgIAKAAQATAAAAARIAAAdIgKAAIAAgFQgFAGgJAAQgGAAgEgDgAgJAJQAAAJAJgBQAGAAAEgEIAAgIQgDgEgHAAQgJAAAAAIg");
	this.shape_21.setTransform(38.3506,29.3832,0.9528,0.9528);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgVAgIAAg+IArAAIAAAJIggAAIAAAQIAfAAIAAAJIgfAAIAAAcg");
	this.shape_22.setTransform(33.8725,28.5733,0.9528,0.9528);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAKAYIAAgcQAAgKgJAAQgGABgFAFIAAAgIgJAAIAAgtIAJAAIAAAGQAHgIAJAAQAOAAAAAPIAAAgg");
	this.shape_23.setTransform(26.2978,29.3356,0.9528,0.9528);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgQARQgHgHABgKQgBgJAHgHQAGgHAKAAQALAAAGAHQAGAHABAJQgBAKgGAHQgGAHgLAAQgKAAgGgHgAgJgKQgDAEAAAGQAAAGADAFQAEAEAFAAQAGABAEgFQADgFABgGQgBgFgDgFQgEgEgGAAQgFAAgEAEg");
	this.shape_24.setTransform(21.3671,29.3832,0.9528,0.9528);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgTAaIAEgHQAFAGAKAAQAMAAAAgNIAAgFQgFAHgIAAQgJAAgGgGQgFgGgBgKQABgLAFgGQAGgHAJAAQAIAAAFAIIAAgGIAKAAIAAAqQAAAVgWAAQgMAAgHgHgAgHgTQgEAEAAAHQAAAHAEADQADAEAFAAQAIAAADgGIAAgRQgDgGgIAAQgFAAgDAEg");
	this.shape_25.setTransform(16.2697,30.2169,0.9528,0.9528);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgPARQgHgGAAgLQAAgJAHgHQAGgHAJAAQALAAAGAHQAGAHAAAKIAAADIgiAAQABAMAMAAQAHAAAGgFIAFAGQgHAHgMAAQgJAAgHgHgAgMgDIAZAAQgBgMgMABQgLgBgBAMg");
	this.shape_26.setTransform(11.2914,29.3832,0.9528,0.9528);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgLAYIAAgtIAKAAIAAAGQAEgHAJgBIAAAKIgDAAQgIABgCAFIAAAfg");
	this.shape_27.setTransform(7.4326,29.3356,0.9528,0.9528);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgWAYQgJgJAAgPQAAgOAJgJQAJgIANgBQAOABAJAIQAJAKAAANQAAAPgJAJQgJAIgOABQgNgBgJgIgAgOgQQgGAHAAAJQAAAKAGAHQAGAGAIAAQAJAAAGgGQAGgHAAgKQAAgJgGgHQgGgGgJAAQgIAAgGAGg");
	this.shape_28.setTransform(2.3828,28.5733,0.9528,0.9528);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgPARQgHgGAAgLQAAgJAHgHQAGgHAJAAQAKAAAHAHQAGAHAAAKIAAADIgjAAQACAMAMAAQAHAAAGgFIAFAGQgHAHgMAAQgJAAgHgHgAgMgDIAZAAQgBgMgMABQgLgBgBAMg");
	this.shape_29.setTransform(-3.5721,29.3832,0.9528,0.9528);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgLAYIAAgtIAJAAIAAAGQAFgHAJgBIAAAKIgDAAQgIABgDAFIAAAfg");
	this.shape_30.setTransform(-7.4309,29.3356,0.9528,0.9528);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgOAVQgFgFAAgHQAAgIAFgDQAEgDAGAAQAJAAAFAFIAAgGQAAgIgKAAQgHAAgGAFIgEgGQAIgIAKAAQATAAAAARIAAAdIgKAAIAAgFQgFAGgJAAQgGAAgEgDgAgJAJQAAAJAJgBQAGAAAEgEIAAgIQgDgEgHAAQgJAAAAAIg");
	this.shape_31.setTransform(-11.7185,29.3832,0.9528,0.9528);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgTAYQgJgJAAgPQAAgOAJgJQAJgIANgBQARAAAJAOIgJAGQgFgKgMAAQgIAAgGAGQgGAHAAAJQAAAKAGAHQAGAGAIAAQAMAAAFgJIAJAEQgJAPgRAAQgNgBgJgIg");
	this.shape_32.setTransform(-17.0065,28.5733,0.9528,0.9528);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgPARQgHgGAAgLQAAgJAHgHQAGgHAKAAQAKAAAGAHQAGAHAAAKIAAADIgjAAQACAMAMAAQAIAAAFgFIAFAGQgHAHgMAAQgJAAgHgHgAgMgDIAZAAQAAgMgMABQgMgBgBAMg");
	this.shape_33.setTransform(-24.9861,29.3832,0.9528,0.9528);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAKAgIAAgeQABgHgKgBQgFABgFAFIAAAgIgKAAIAAg+IAKAAIAAAXQAGgIAJAAQAOAAAAAPIAAAgg");
	this.shape_34.setTransform(-29.8453,28.5733,0.9528,0.9528);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgGASIAAgaIgHAAIAAgIIAHAAIAAgNIAJAAIAAANIAJAAIAAAIIgJAAIAAAXQAAAGAEAAQABAAABAAQABAAAAgBQABAAAAAAQAAgBABAAIACAHQgDAEgGAAQgLAAAAgMg");
	this.shape_35.setTransform(-33.8232,28.8592,0.9528,0.9528);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgGAgIAAgkIgIAAIAAgIIAIAAIAAgDQAAgQAOAAQAFAAACABIgCAIIgEgBQgGAAAAAIIAAADIAJAAIAAAIIgJAAIAAAkg");
	this.shape_36.setTransform(-38.8492,28.5257,0.9528,0.9528);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgQARQgHgHABgKQgBgJAHgHQAGgHAKAAQALAAAGAHQAGAHABAJQgBAKgGAHQgGAHgLAAQgKAAgGgHgAgJgKQgEAFABAFQgBAGAEAFQAEAEAFAAQAGABADgFQAEgFAAgGQAAgGgEgEQgDgEgGAAQgFAAgEAEg");
	this.shape_37.setTransform(-42.9462,29.3832,0.9528,0.9528);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgGASIAAgaIgHAAIAAgIIAHAAIAAgNIAJAAIAAANIAKAAIAAAIIgKAAIAAAXQAAAGAEAAQABAAABAAQAAAAABgBQAAAAABAAQAAgBABAAIACAHQgCAEgHAAQgLAAAAgMg");
	this.shape_38.setTransform(-49.2822,28.8592,0.9528,0.9528);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgLAYIAAgtIAKAAIAAAGQAFgHAIgBIAAAKIgDAAQgIABgCAFIAAAfg");
	this.shape_39.setTransform(-52.2359,29.3356,0.9528,0.9528);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgOAVQgFgFAAgHQAAgIAFgDQAEgDAGAAQAJAAAFAFIAAgGQAAgIgKAAQgHAAgGAFIgEgGQAIgIAKAAQATAAAAARIAAAdIgKAAIAAgFQgFAGgJAAQgGAAgEgDgAgJAJQAAAJAJgBQAGAAAEgEIAAgIQgDgEgHAAQgJAAAAAIg");
	this.shape_40.setTransform(-56.2137,29.3832,0.9528,0.9528);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgXAgIAAg+IAbAAQAJAAAGAFQAFAGAAAIQAAAIgFAFQgGAGgJAAIgQAAIAAAYgAgMgBIAOAAQALAAAAgKQAAgKgLAAIgOAAg");
	this.shape_41.setTransform(-60.6919,28.5733,0.9528,0.9528);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AAKANIgBgWIgIAWIgCAAIgHgWIgCAWIgCAAIACgZIADAAIAHAUIAAAAIADgIIAEgMIAFAAIACAZg");
	this.shape_42.setTransform(70.2452,8.1836,0.9528,0.9528);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AAAANIAAgWIgIAAIAAgDIASAAIAAADIgJAAIAAAWg");
	this.shape_43.setTransform(67.8156,8.1836,0.9528,0.9528);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("ADOCEIgxhxIAUADIgUgpIAPACIgfhQIgcBDIAPADIgiA9IAaAEIgpBRIgbgCIgjhMIAPACIgPgiIAPACIgbg7IgVAwIANADIgcAyIAVADIgbA4IgrgBIgUgsIANACIgMgbIALABIgVgrIgRAjIAKACIgWAoIARACIgPAeIgdAAIgRgmIALABIgLgaIALACIgVg3IgSAsIAMAEIgVAnIAQACIgNAaIgTAAIAKgSIgRgDIAagnIgNgCIAlhWIAlBkIgLgCIAMASIAUggIgMgCIAmhIIAmBXIgLgCIARAbIgLgCIAPAdIAZgrIgXgDIAhgzIgQgDIAvhcIAwBvIgOgDIAWAjIgPgCIAUAjIAZgsIgbgEIAng6IgTgEIA5h3IA4COIgPgDIAYAmIgRgCIA1BigAiWBmIAIgPIgSgDIABgBIgCAAg");
	this.shape_44.setTransform(19.1281,-19.5664,0.9528,0.9528);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgWAvIgOgCIAUgfIgJgCIAbg9IAeBJIgJgCIAOAVIgJgBIAEAHIgPABIgHgSIAIABIgIgVIAIABIgPgiIgKAcIAHABIgQAfIALACIgDAJIgQAAg");
	this.shape_45.setTransform(-6.9784,-13.9449,0.9528,0.9528);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AipBaIgSgCIAagpIgMgCIAmhQIAmBfIgLgCIARAbIgLgCIAPAdIAZgrIgXgDIAhgyIgQgEIAwhlIAvB5IgNgBIAVAgIgPgCIATAkIAagtIgbgEIAng6IgTgEIA4iAIA7CYIgQgDIAaAsIgSgDIAjBBIgfAAIgnhaIAQACIgTgqIASADIghhVIgbBIIAQADIgjA9IAbAEIgmBMIgfACIgehKIALABIgOgiIAOADIgbhCIgWAzIAMADIgbA1IAWAEIghBCIgdADIgcg6IAMABIgLgbIALABIgUgwIgSAoIAKADIgXAnIASACIgdA6IgWADg");
	this.shape_46.setTransform(-29.5356,-19.876,0.9528,0.9528);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AFZAKQihgJi4AAQi3AAihAJQicAJhlAQQAhgYCngUQC7gYDWAAQDXAAC6AYQClAUAkAYQhlgQicgJg");
	this.shape_47.setTransform(-3.152,-2.9703,0.9529,0.9529);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CPCCOlogo, new cjs.Rectangle(-71.7,-33.5,143.3,66.9), null);


(lib.BKGD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#165C7D").s().p("A3bM5IAA5xMAu3AAAIAAZxg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGD2, new cjs.Rectangle(-150,-82.5,300,165), null);


// stage content:
(lib.CPCCO_StuckAtHome_728x90 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_205 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(205).call(this.frame_205).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Eg4ygG8MBxlAAAIAAN5MhxlAAAg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(206));

	// logo
	this.instance = new lib.CPCCOlogo();
	this.instance.setTransform(578.8,45,1.2679,1.2679);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(206));

	// HEAD1
	this.instance_1 = new lib.HEAD1();
	this.instance_1.setTransform(214.05,16);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(90).to({alpha:0},5).to({_off:true},1).wait(110));

	// HEAD2
	this.instance_2 = new lib.HEAD1copy();
	this.instance_2.setTransform(214.05,16);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(48).to({_off:false},0).to({alpha:1},5).wait(37).to({alpha:0},5).to({_off:true},1).wait(110));

	// HEAD3
	this.instance_3 = new lib.HEAD3();
	this.instance_3.setTransform(214.05,65,1,1,0,0,0,0,49);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(95).to({_off:false},0).to({alpha:1},5).wait(53).to({alpha:0},5).to({_off:true},1).wait(47));

	// HEAD4
	this.instance_4 = new lib.HEAD4();
	this.instance_4.setTransform(155,68.4,1,1,0,0,0,0,49);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(158).to({_off:false},0).to({x:156,alpha:1},5).wait(43));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_201 = new cjs.Graphics().p("ANuG/IAAt9IUHAAIAAN9g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(201).to({graphics:mask_graphics_201,x:216.4751,y:44.7315}).wait(5));

	// CTA
	this.instance_5 = new lib.CTA();
	this.instance_5.setTransform(476,0);
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(201).to({_off:false},0).to({x:390},4).wait(1));

	// bkgd2
	this.instance_6 = new lib.BKGD2();
	this.instance_6.setTransform(216.15,45.2,1.4402,0.5455,0,0,0,0.1,0.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(206));

	// bkgd
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#009681").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_1.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(206));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(316.5,44.5,412,46);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 728,
	height: 90,
	fps: 24,
	color: "#999999",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;