(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.HEAD4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgQAQQgGgGAAgJQAAgKAGgGQAHgHAJAAQAKAAAHAHQAGAGAAAKQAAAJgGAGQgHAHgKgBQgJABgHgHg");
	this.shape.setTransform(116.15,239.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAXBoIAAgTIAYAAQAGgBAAgIIAAhrQAAgygqAAQgcABgRAYQgRAZAAArIAABAQgBAIAGABIAaAAIAAATIhfAAIAAgTIAbAAQAFgBAAgIIAAiQQAAgLgFAAIgbAAIAAgTIASAAQAdAAAQgDIAAA1QAVg3AzAAQBAAAAABGIAABtQABAIAFABIAaAAIAAATg");
	this.shape_1.setTransform(99.1,231.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhTBbQgSgOABgYQAAgiAigSQAggQBIgHIAAgMQAAgbgMgMQgNgMgbAAQglAAgOASQANAEAAAPQAAAIgFAGQgGAFgJAAQgYAAAAgYQAAgYAagOQAYgOAlAAQAoAAAUARQATARAAAkIAABsQAAAJAFAAIAaAAIAAAUIg3AAQgFgSgCgaQgIAWgWANQgUANgaAAQgdAAgRgPgAgrALQgbANAAAZQAAAQAMAKQALAKAUAAQAcAAATgUQASgVAAghIAAgRQg5AGgYALg");
	this.shape_2.setTransform(75.2,231.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AguCNIAAgTIAaAAQAFgBAAgIIAAjcQAAgKgFAAIgaAAIAAgUIASAAQAcAAARgDIAAD9QgBAIAGABIAZAAIAAATg");
	this.shape_3.setTransform(57,227.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhpCLIAAgTIAbAAQAGAAAAgKIAAjbQAAgJgGAAIgbAAIAAgVIBuAAQBlAAAABQQAAAqgZASQgZAUg0AAIgsAAIAABZQAAAKAGAAIAcAAIAAATgAgoABIAtAAQAjABAQgOQAQgOAAghQAAgfgQgOQgQgOgjAAIgtAAg");
	this.shape_4.setTransform(38.775,227.55);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAXCNIAAgTIAZAAQAFgBAAgIIAAhtQAAgwgqAAQgcABgRAYQgRAYAAAsIAABAQAAAIAFABIAaAAIAAATIhfAAIAAgTIAaAAQAGgBAAgIIAAjcQAAgKgGAAIgbAAIAAgUIATAAQAdAAARgDIAAB/QAVg1AyAAQBBAAAABEIAABvQgBAIAGABIAaAAIAAATg");
	this.shape_5.setTransform(3.5,227.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgNB0QgMgMAAgdIAAiFIggAAIAAgRIAXgCQAOgBABgNIADglIAWAAIAAAzIAwAAIAAATIgxAAIAACFQAAASAHAHQAHAIAQAAQAKAAAMgEIAAAUQgOAFgPAAQgcAAgNgNg");
	this.shape_6.setTransform(-16,229.025);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgvCNIAAgTIAbAAQAFgBABgIIAAjcQgBgKgFAAIgbAAIAAgUIASAAQAdAAAQgDIAAD9QAAAIAGABIAaAAIAAATg");
	this.shape_7.setTransform(-28.7,227.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhTBbQgRgOAAgYQAAgiAigSQAggQBIgHIAAgMQAAgbgNgMQgMgMgbAAQglAAgOASQANAEAAAPQAAAIgFAGQgHAFgJAAQgXAAAAgYQAAgYAagOQAYgOAkAAQApAAAUARQATARAAAkIAABsQAAAJAGAAIAZAAIAAAUIg3AAQgFgSgBgaQgJAWgWANQgUANgaAAQgdAAgRgPgAgrALQgbANAAAZQAAAQAMAKQAMAKASAAQAeAAASgUQASgVAAghIAAgRQg4AGgZALg");
	this.shape_8.setTransform(-45.75,231.325);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhGBMQgbgdAAgvQAAguAcgdQAcgeAtAAQArAAAaAbQAZAcAAAuIAAAJIijAAQAAAkATAWQAUAXAhAAQA3AAAOg0IAUAHQgHAegWARQgYASgmAAQgvAAgcgegABCgNQAAgigQgTQgRgTgeAAQgdAAgSATQgSATgDAiICDAAIAAAAg");
	this.shape_9.setTransform(-69.175,231.325);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAnCLIAAgTIAcAAQAGAAAAgKIAAhmIiRAAIAABmQAAAKAGAAIAcAAIAAATIhjAAIAAgTIAbAAQAGAAAAgKIAAjbQAAgJgGAAIgbAAIAAgVIBjAAIAAAVIgcAAQgGAAAAAJIAABiICRAAIAAhiQAAgJgGAAIgcAAIAAgVIBjAAIAAAVIgbAAQgGAAAAAJIAADbQAAAKAGAAIAbAAIAAATg");
	this.shape_10.setTransform(-95.675,227.55);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAXBoIAAgTIAYAAQAGAAAAgJIAAhrQAAgygrAAQgbAAgRAZQgRAZgBArIAABAQAAAJAGAAIAaAAIAAATIhfAAIAAgTIAaAAQAGAAAAgJIAAiQQAAgKgGAAIgaAAIAAgUIARAAQAeAAAQgEIAAA1QAUg2A0AAQBBAAAABGIAABtQgBAJAGAAIAaAAIAAATg");
	this.shape_11.setTransform(64.15,179.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhJBNQgcgdAAgwQAAguAcgeQAdgdAtAAQAtAAAcAdQAcAeAAAuQAAAvgcAeQgdAdgtAAQgtAAgcgdgAgzg+QgTAWAAAnIAAADQAAAnATAWQASAXAhAAQAhAAATgXQATgWAAgnIAAgDQAAgngTgWQgSgWghAAQghAAgTAWg");
	this.shape_12.setTransform(39.525,179.325);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhwBvQAAghAzgMQgmgGAAgeQAAgcAhgJQgfgUAAgnQAAggAagUQAYgVAmAAQAoAAAYAYQAHgnAdgBQAKAAAGAHQAGAFAAAIQAAAJgFAFQgFAFgIAAQgOAAgCgOQgKAJgFAQQAMAQAAAYQAAAhgYATQgYATgnAAQgWAAgTgGQgYADAAASQABAUAgAAIBQAAQBBgBgBAzQAAAfgeARQgeARg1AAQhkAAAAgtgAhWBtQAAAeBMAAQBWAAAAgqQAAgOgLgHQgKgGgZgBIhEAAQgwAKAAAegAgyhqQgPAPAAAZIAAACQAAAZAOAPQAPANAaAAQAYAAAQgNQAPgPAAgZIAAgCQAAgZgPgPQgPgPgYAAQgaAAgPAPg");
	this.shape_13.setTransform(16.5,182.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhGBMQgbgdAAgvQAAguAcgdQAcgeAtAAQArAAAaAbQAZAcAAAuIAAAJIijAAQAAAkATAWQAUAXAhAAQA3AAAOg0IAUAHQgHAegWARQgYASgmAAQgvAAgcgegABCgNQAAgigQgTQgRgTgeAAQgdAAgSATQgSATgDAiICDAAIAAAAg");
	this.shape_14.setTransform(-6.675,179.325);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhQBoIAAgTIAbAAQAFAAAAgJIAAiQQAAgKgFAAIgbAAIAAgUIARAAQAcAAASgEIAAAwQAOgxApAAQAUAAANAMQAKALABARQAAAegaAAQgIAAgFgGQgFgFAAgHQgBgPARgDQgEgNgSAAQgZAAgMAZQgMAWABAnIAABIQAAAJAFAAIAcAAIAAATg");
	this.shape_15.setTransform(-27.25,179.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhiBpQglgoAAhBQAAg/AmgoQAngoA7AAQA8AAAmAoQAlAoAAA/QAABBgmAoQgmAng8AAQg8AAgmgngAhJhaQgdAgAAA3IAAAJQAAA2AcAfQAcAgAuAAQAvAAAcggQAcgfAAg2IAAgJQAAg3gcggQgcgfguAAQguAAgcAfg");
	this.shape_16.setTransform(-51.875,175.55);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhGBMQgbgdAAgvQAAguAcgdQAcgeAtAAQArAAAaAbQAZAcAAAuIAAAJIijAAQAAAkATAWQAUAXAhAAQA3AAAOg0IAUAHQgHAegWARQgYASgmAAQgvAAgcgegABCgNQAAgigQgTQgRgTgeAAQgdAAgSATQgSATgDAiICDAAIAAAAg");
	this.shape_17.setTransform(70.225,127.325);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAXCNIAAgUIAZAAQAFABAAgKIAAhtQAAgvgqABQgcAAgRAYQgRAYAAAsIAAA/QAAAKAFgBIAZAAIAAAUIheAAIAAgUIAaAAQAGABAAgKIAAjbQAAgKgGAAIgbAAIAAgUIATAAQAdAAARgDIAAB/QAVg1AyAAQBBAAAABEIAABuQgBAKAGgBIAaAAIAAAUg");
	this.shape_18.setTransform(46.25,123.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgNB0QgMgMAAgdIAAiFIggAAIAAgRIAXgCQAOgBABgNIADglIAWAAIAAAzIAwAAIAAATIgxAAIAACFQAAASAHAHQAHAIAQAAQAKAAAMgEIAAAUQgOAFgPAAQgcAAgNgNg");
	this.shape_19.setTransform(26.75,125.025);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("ABQBoIAAgUIAYAAQAFABAAgKIAAhjQAAgdgJgOQgKgNgXAAQg0AAABBMIAABPQAAAKAFgBIAcAAIAAAUIheAAIAAgUIAZAAQAFABAAgKIAAhpQAAgygqAAQgzAAAABMIAABPQAAAKAFgBIAZAAIAAAUIheAAIAAgUIAbAAQAFABAAgKIAAiPQAAgLgFABIgbAAIAAgUIASAAQAcAAARgEIAAAqQARgrAtAAQAxAAAJAyQATgyAuAAQBCAAAABNIAABlQAAAKAEgBIAbAAIAAAUg");
	this.shape_20.setTransform(-8.95,127.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhJBNQgcgdAAgwQAAguAcgeQAdgdAtAAQAtAAAcAdQAcAeAAAuQAAAvgcAeQgdAdgtAAQgtAAgcgdgAgzg+QgTAWAAAnIAAADQAAAnATAWQASAXAhAAQAhAAATgXQATgWAAgnIAAgDQAAgngTgWQgSgWghAAQghAAgTAWg");
	this.shape_21.setTransform(-39.275,127.325);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AhQBoIAAgUIAaAAQAGABAAgKIAAiPQAAgLgGABIgbAAIAAgUIASAAQAcAAARgEIAAAxQAPgyAqAAQATAAAMAMQAMALAAASQAAAdgZAAQgJAAgFgGQgGgFABgHQAAgPAPgDQgDgNgSAAQgZAAgLAYQgMAXAAAnIAABHQAAAKAFgBIAbAAIAAAUg");
	this.shape_22.setTransform(-60.3,127.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag3CPIAAgTIAYAAQAFAAAAgJIAAiaIgdAAIAAgUIAdAAIAAgaQAAg5A0AAQASAAAMAHIAAAUQgLgGgLAAQgRAAgHAIQgGAJAAAWIAAAXIArAAIAAAUIgrAAIAACaQAAAJAGAAIAcAAIAAATg");
	this.shape_23.setTransform(-75.65,123.175);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AhGBMQgbgdAAgvQAAguAcgdQAcgeAtAAQArAAAaAbQAZAcAAAuIAAAJIijAAQAAAkATAWQAUAXAhAAQA3AAAOg0IAUAHQgHAegWARQgYASgmAAQgvAAgcgegABCgNQAAgigQgTQgRgTgeAAQgdAAgSATQgSATgDAiICDAAIAAAAg");
	this.shape_24.setTransform(97.825,75.325);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AhQBoIAAgUIAbAAQAFAAAAgJIAAiQQAAgKgFAAIgbAAIAAgTIARAAQAdAAARgDIAAAwQAOgyApAAQAVAAAMAMQAKALABASQAAAdgaAAQgHAAgGgFQgFgGAAgIQAAgPAQgDQgEgMgSAAQgYAAgNAYQgMAXABAnIAABHQgBAJAHAAIAbAAIAAAUg");
	this.shape_25.setTransform(77.25,75.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AhUBbQgRgOAAgYQAAgiAjgSQAggQBJgHIAAgMQgBgbgNgMQgMgMgbAAQgkAAgPASQAOAEAAAPQAAAIgHAGQgFAFgKAAQgXAAAAgYQAAgYAagOQAYgOAkAAQApAAATARQAUARAAAkIAABsQAAAJAFAAIAbAAIAAAUIg4AAQgFgSgBgaQgKAWgUANQgVANgbAAQgcAAgSgPgAgrALQgbANAAAZQAAAQAMAKQALAKATAAQAeAAASgUQASgVABghIAAgRQg5AGgZALg");
	this.shape_26.setTransform(56.8,75.325);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AhFBNQgcgdAAgwQAAgvAdgdQAdgdAvAAQAoAAAZATQAZAUAAAgQAAAMgIAIQgHAIgLAAQgKAAgGgFQgGgGAAgIQAAgUAVgCQgKgmg0AAQghAAgVAWQgUAXAAAmIAAADQAAAnATAXQATAXAiAAQA3AAAOg1IAVAHQgSBChJAAQgvAAgcgdg");
	this.shape_27.setTransform(33.825,75.325);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAXCNIAAgUIAYAAQAGAAAAgJIAAhtQAAgugrAAQgbgBgRAZQgSAZAAArIAAA/QAAAJAHAAIAZAAIAAAUIhfAAIAAgUIAaAAQAGAAAAgJIAAjbQAAgKgGAAIgbAAIAAgUIATAAQAeAAAPgDIAAB/QAWg1AyAAQBBAAgBBEIAABuQAAAJAGAAIAbAAIAAAUg");
	this.shape_28.setTransform(-0.85,71.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgMB0QgNgMAAgdIAAiFIggAAIAAgRIAXgCQAOgBABgNIADglIAWAAIAAAzIAvAAIAAATIgwAAIAACFQABASAGAHQAHAIAPAAQAMAAAMgEIAAAUQgOAFgRAAQgbAAgMgNg");
	this.shape_29.setTransform(-20.35,73.025);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgvCNIAAgUIAbAAQAGAAAAgJIAAjbQAAgKgGAAIgbAAIAAgUIASAAQAdAAAQgDIAAD8QABAJAFAAIAaAAIAAAUg");
	this.shape_30.setTransform(-33.05,71.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AhUBbQgQgOAAgYQgBgiAjgSQAggQBIgHIAAgMQABgbgNgMQgNgMgbAAQglAAgOASQANAEAAAPQABAIgHAGQgGAFgIAAQgYAAAAgYQAAgYAagOQAYgOAlAAQAoAAATARQAUARAAAkIAABsQAAAJAFAAIAaAAIAAAUIg3AAQgFgSgCgaQgIAWgVANQgVANgaAAQgdAAgSgPgAgrALQgbANAAAZQAAAQAMAKQALAKAUAAQAcAAATgUQASgVAAghIAAgRQg4AGgZALg");
	this.shape_31.setTransform(-50.1,75.325);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AhGBMQgbgdAAgvQAAguAcgdQAcgeAtAAQArAAAaAbQAZAcAAAuIAAAJIijAAQAAAkATAWQAUAXAhAAQA3AAAOg0IAUAHQgHAegWARQgYASgmAAQgvAAgcgegABCgNQAAgigQgTQgRgTgeAAQgdAAgSATQgSATgDAiICDAAIAAAAg");
	this.shape_32.setTransform(-73.525,75.325);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AAXCNIAAgUIAYAAQAGAAAAgJIAAhtQAAgugrAAQgbgBgRAZQgSAZAAArIAAA/QABAJAFAAIAaAAIAAAUIhfAAIAAgUIAaAAQAGAAAAgJIAAjbQAAgKgGAAIgbAAIAAgUIATAAQAdAAAQgDIAAB/QAWg1AyAAQBBAAAABEIAABuQgBAJAGAAIAaAAIAAAUg");
	this.shape_33.setTransform(-97.5,71.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AhGBMQgbgdAAgvQAAguAcgdQAcgeAtAAQArAAAaAbQAZAcAAAuIAAAJIijAAQAAAkATAWQAUAXAhAAQA3AAAOg0IAUAHQgHAegWARQgYASgmAAQgvAAgcgegABCgNQAAgigQgTQgRgTgeAAQgdAAgSATQgSATgDAiICDAAIAAAAg");
	this.shape_34.setTransform(64.375,23.325);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AhGBMQgbgdAAgvQAAguAcgdQAcgeAtAAQArAAAaAbQAZAcAAAuIAAAJIijAAQAAAkATAWQAUAXAhAAQA3AAAOg0IAUAHQgHAegWARQgYASgmAAQgvAAgcgegABCgNQAAgigQgTQgRgTgeAAQgdAAgSATQgSATgDAiICDAAIAAAAg");
	this.shape_35.setTransform(41.725,23.325);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AhQBoIAAgTIAaAAQAGgBAAgIIAAiRQAAgJgGgBIgbAAIAAgTIASAAQAcAAARgDIAAAvQAPgxAqAAQATAAAMAMQAMALAAARQAAAegZAAQgJAAgFgFQgGgGABgIQAAgOAPgEQgDgMgSAAQgZAAgLAZQgMAWAAAnIAABIQAAAIAFABIAbAAIAAATg");
	this.shape_36.setTransform(21.15,23.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("Ag3CPIAAgTIAYAAQAFAAAAgJIAAiaIgdAAIAAgUIAdAAIAAgaQAAg5A0AAQASAAAMAHIAAAUQgLgGgLAAQgRAAgHAIQgGAJAAAWIAAAXIArAAIAAAUIgrAAIAACaQAAAJAGAAIAcAAIAAATg");
	this.shape_37.setTransform(5.8,19.175);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgNB0QgMgMAAgdIAAiFIggAAIAAgRIAXgCQAOgBABgNIADglIAWAAIAAAzIAwAAIAAATIgxAAIAACFQAAASAHAHQAHAIAQAAQAKAAAMgEIAAAUQgOAFgPAAQgcAAgNgNg");
	this.shape_38.setTransform(-18.7,21.025);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AhGBMQgbgdAAgvQAAguAcgdQAcgeAtAAQArAAAaAbQAZAcAAAuIAAAJIijAAQAAAkATAWQAUAXAhAAQA3AAAOg0IAUAHQgHAegWARQgYASgmAAQgvAAgcgegABCgNQAAgigQgTQgRgTgeAAQgdAAgSATQgSATgDAiICDAAIAAAAg");
	this.shape_39.setTransform(-36.625,23.325);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AhYBqQgigmAAhDQAAhBAkgpQAjgmA3AAQAjAAAYAPQAZAPAJAbIAGg1IAUAAIAABkIgaAAQgQhShKAAQgrAAgaAfQgbAfAAA4IAAAGQAAA6AaAfQAZAfAsgBQAlAAAXgVQAYgWAAgpIAAgHIhLAAIAAgUIBsAAIAACAIgQAAIgKgyQgXA3hJAAQg4AAghgmg");
	this.shape_40.setTransform(-62.675,19.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD4, new cjs.Rectangle(-148.9,0,297.9,254), null);


(lib.HEAD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgQAQQgGgGAAgJQAAgJAGgHQAHgGAJgBQAKABAHAGQAGAHAAAJQAAAJgGAGQgHAGgKAAQgJAAgHgGg");
	this.shape.setTransform(97.7,291.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhGBMQgbgdAAgvQAAguAcgdQAcgeAtAAQArAAAaAbQAZAcAAAuIAAAJIijAAQAAAkATAWQAUAXAhAAQA3AAAOg0IAUAHQgHAegWARQgYASgmAAQgvAAgcgegABCgNQAAgigQgTQgRgTgeAAQgdAAgSATQgSATgDAiICDAAIAAAAg");
	this.shape_1.setTransform(82.075,283.325);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ah0CMIAAgUIAaAAQAGAAAAgJIAAjYQAAgJgGgBIgbAAIAAgTIASAAQAdAAARgDIAAAxQAVgzA5AAQAqAAAZAdQAaAdgBAwQAAAwgaAdQgaAcgqAAQg1ABgXgyIAABYQAAAJAHAAIAaAAIAAAUgAghhfQgUAWAAAmIAAAFQAAAkAUAXQATAVAeABQAggBASgVQATgWAAglIAAgFQAAgngTgWQgSgUgggBQgeAAgTAWg");
	this.shape_2.setTransform(57.3,286.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhJBNQgcgdAAgwQAAguAcgeQAdgdAtAAQAtAAAcAdQAcAeAAAuQAAAvgcAeQgdAdgtAAQgtAAgcgdgAgzg+QgTAWAAAnIAAADQAAAnATAWQASAXAhAAQAhAAATgXQATgWAAgnIAAgDQAAgngTgWQgSgWghAAQghAAgTAWg");
	this.shape_3.setTransform(32.875,283.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAXCNIAAgUIAZAAQAFAAAAgJIAAhtQAAgugqgBQgcAAgRAZQgRAZAAArIAAA/QAAAJAFAAIAZAAIAAAUIheAAIAAgUIAaAAQAGAAAAgJIAAjbQAAgKgGAAIgbAAIAAgUIATAAQAdAAARgDIAAB/QAVg1AyAAQBBAAAABEIAABuQgBAJAGAAIAaAAIAAAUg");
	this.shape_4.setTransform(8.45,279.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhGBMQgbgdAAgvQAAguAcgdQAcgeAtAAQArAAAaAbQAZAcAAAuIAAAJIijAAQAAAkATAWQAUAXAhAAQA3AAAOg0IAUAHQgHAegWARQgYASgmAAQgvAAgcgegABCgNQAAgigQgTQgRgTgeAAQgdAAgSATQgSATgDAiICDAAIAAAAg");
	this.shape_5.setTransform(-26.075,283.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhMBYIAAg0IAYAAIAAApQAUAKAeAAQAyAAAAglQAAgSgQgJQgLgHgbgFQghgHgPgIQgWgOAAgbQAAgbAVgRQAVgQAjAAQAoAAAeASIAAAzIgZAAIAAgnQgRgLgbAAQgxAAAAAkQAAASARAJQAJAEAcAGQAiAHAPAJQAVAPAAAbQAAAcgVARQgVAQglAAQgpAAghgSg");
	this.shape_6.setTransform(-47.025,283.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhJBNQgcgdAAgwQAAguAcgeQAdgdAtAAQAtAAAcAdQAcAeAAAuQAAAvgcAeQgdAdgtAAQgtAAgcgdgAgzg+QgTAWAAAnIAAADQAAAnATAWQASAXAhAAQAhAAATgXQATgWAAgnIAAgDQAAgngTgWQgSgWghAAQghAAgTAWg");
	this.shape_7.setTransform(-68.475,283.325);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AguCNIAAgUIAaAAQAGAAgBgJIAAjbQABgKgGAAIgaAAIAAgUIASAAQAcAAARgDIAAD8QAAAJAFAAIAZAAIAAAUg");
	this.shape_8.setTransform(-86.35,279.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgMB0QgNgMAAgdIAAiFIggAAIAAgRIAXgCQAOgBABgNIADglIAWAAIAAAzIAvAAIAAATIgwAAIAACFQABASAGAHQAHAIAPAAQALAAANgEIAAAUQgOAFgQAAQgcAAgMgNg");
	this.shape_9.setTransform(81,229.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgdAoIAAgQIALABQAaAAAAgaIgBgHQgFAHgJAAQgUAAAAgTQAAgKAHgFQAHgGAKAAQANAAAKAKQAJALABARQAAATgOANQgMANgUAAg");
	this.shape_10.setTransform(70.1,217.375);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAXBoIAAgTIAYAAQAGgBAAgIIAAhrQAAgygrAAQgbABgRAYQgSAZAAArIAABAQABAIAFABIAaAAIAAATIhfAAIAAgTIAaAAQAGgBAAgIIAAiQQAAgLgGAAIgaAAIAAgTIARAAQAeAAAQgDIAAA1QAUg3A0AAQBBAAgBBGIAABtQAAAIAGABIAaAAIAAATg");
	this.shape_11.setTransform(54.95,231.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhbBzQgZgdAAgxQAAgvAagdQAZgdArAAQA3AAAVAxIAAhaQAAgKgGAAIgbAAIAAgUIASAAQAdAAARgDIAAD8QAAAJAGAAIAaAAIAAAUIg8AAIgCgtQgWAxg3AAQgrAAgagcgAhBgZQgTAWAAAmIAAAFQAAAmATAWQATAWAgAAQAeAAASgWQAUgXAAgmIAAgEQgBglgTgWQgSgWgeAAQggAAgTAVg");
	this.shape_12.setTransform(29.35,227.625);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AguCNIAAgTIAaAAQAGgBgBgIIAAjcQABgKgGAAIgaAAIAAgUIASAAQAcAAARgDIAAD9QAAAIAFABIAZAAIAAATg");
	this.shape_13.setTransform(9.95,227.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhSAlIAAhvQAAgJgGAAIgbAAIAAgUIBAAAIAACKQAAAvAqAAQAbAAARgYQARgXAAgkIAAhJQAAgJgGAAIgbAAIAAgUIBAAAIAACtQAAAKAGAAIAbAAIAAATIgSAAQgeAAgQAEIAAgxQgWAygwAAQhAAAAAhDg");
	this.shape_14.setTransform(-8.6,231.575);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhJBNQgcgdAAgwQAAguAcgeQAdgdAtAAQAtAAAcAdQAcAeAAAuQAAAvgcAeQgdAdgtAAQgtAAgcgdgAgzg+QgTAWAAAnIAAADQAAAnATAWQASAXAhAAQAhAAATgXQATgWAAgnIAAgDQAAgngTgWQgSgWghAAQghAAgTAWg");
	this.shape_15.setTransform(-32.725,231.325);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAXCNIAAgTIAZAAQAFgBAAgIIAAhtQAAgwgqAAQgcABgRAYQgRAYAAAsIAABAQAAAIAFABIAZAAIAAATIheAAIAAgTIAbAAQAFgBAAgIIAAjcQAAgKgFAAIgbAAIAAgUIASAAQAdAAARgDIAAB/QAVg1AyAAQBBAAAABEIAABvQAAAIAFABIAaAAIAAATg");
	this.shape_16.setTransform(-57.15,227.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhMBYIAAg0IAYAAIAAApQAUAKAeAAQAyAAAAglQAAgSgQgJQgLgHgbgFQghgHgPgIQgWgOAAgbQAAgbAVgRQAVgQAjAAQAoAAAeASIAAAzIgZAAIAAgnQgRgLgbAAQgxAAAAAkQAAASARAJQAJAEAcAGQAiAHAPAJQAVAPAAAbQAAAcgVARQgVAQglAAQgpAAghgSg");
	this.shape_17.setTransform(-79.275,231.325);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhTAlIAAhvQABgJgGAAIgaAAIAAgUIA/AAIAACKQAAAvAqAAQAbAAARgYQAQgXAAgkIAAhJQABgJgGAAIgbAAIAAgUIBAAAIAACtQAAAKAFAAIAbAAIAAATIgRAAQgeAAgRAEIAAgxQgUAygyAAQg/AAgBhDg");
	this.shape_18.setTransform(60.75,179.575);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhJBNQgcgdAAgwQAAguAcgeQAdgdAtAAQAtAAAcAdQAcAeAAAuQAAAvgcAeQgdAdgtAAQgtAAgcgdgAgzg+QgTAWAAAnIAAADQAAAnATAWQASAXAhAAQAhAAATgXQATgWAAgnIAAgDQAAgngTgWQgSgWghAAQghAAgTAWg");
	this.shape_19.setTransform(36.625,179.325);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AhhCCQgNgKAAgQQAAgMAGgHQAHgHAKAAQAQAAADANQACANgOAKIgIgNQAAATAXAAQARAAANgOQAMgOAPgkIAAgCIhOikQgEgJgFAAIgTAAIAAgTIBXAAIAAATIgUAAQgKAAADAJIA+CEIA4iDQAEgKgLAAIgVAAIAAgTIBPAAIAAATIgUAAQgGAAgDAJIhKCsQgSArgNAPQgSATgcAAQgUAAgMgJg");
	this.shape_20.setTransform(12.775,183.125);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgNB0QgMgMAAgdIAAiFIggAAIAAgRIAXgCQAOgBABgNIADglIAWAAIAAAzIAwAAIAAATIgxAAIAACFQABASAGAHQAHAIAPAAQALAAAMgEIAAAUQgNAFgQAAQgcAAgNgNg");
	this.shape_21.setTransform(-17,177.025);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AhTAlIAAhvQAAgJgFAAIgbAAIAAgUIBAAAIAACKQAAAvAqAAQAbAAARgYQAQgXAAgkIAAhJQAAgJgFAAIgbAAIAAgUIBAAAIAACtQAAAKAFAAIAbAAIAAATIgRAAQgeAAgRAEIAAgxQgVAygxAAQhAAAAAhDg");
	this.shape_22.setTransform(-36.2,179.575);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag4BbIgLAwIgUAAQADgWAAgwIAAiyQAAgKgGAAIgaAAIAAgUIARAAQAeAAARgDIAAB7QAWgxA2AAQArAAAZAdQAZAdAAAvQAAAwgZAdQgaAdgrAAQg6AAgVg0gAghgZQgTAXAAAlIAAAEQAAAmATAXQATAWAdAAQAgAAATgWQATgWAAgmIAAgFQAAgmgTgWQgTgVggAAQgeAAgSAVg");
	this.shape_23.setTransform(-61.925,175.625);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-148.9,0,297.9,306), null);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgdApIAAgRIALABQAaAAAAgaIgBgHQgFAHgJAAQgUAAAAgTQAAgJAHgGQAGgGALAAQANAAAKALQAJALABAQQgBATgNANQgMANgUAAg");
	this.shape.setTransform(85.95,137.675);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag4BbIgLAwIgUAAQADgWAAgwIAAiyQAAgKgGAAIgaAAIAAgUIARAAQAeAAARgDIAAB7QAWgxA2AAQArAAAZAdQAZAdAAAvQAAAwgZAdQgaAdgrAAQg6AAgVg0gAghgZQgTAXAAAlIAAAEQAAAmATAXQATAWAdAAQAgAAATgWQATgWAAgmIAAgFQAAgmgTgWQgTgVggAAQgeAAgSAVg");
	this.shape_1.setTransform(68.125,123.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhJBNQgcgdAAgwQAAguAcgeQAdgdAtAAQAtAAAcAdQAcAeAAAuQAAAvgcAeQgdAdgtAAQgtAAgcgdgAgzg+QgTAWAAAnIAAADQAAAnATAWQASAXAhAAQAhAAATgXQATgWAAgnIAAgDQAAgngTgWQgSgWghAAQghAAgTAWg");
	this.shape_2.setTransform(44.025,127.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgnCvIAAgTIALABQASAAAHgJQAFgIAAgaIAAiuQAAgRgJAAIgWAAIAAgUIASAAQAcAAAQgEIAADVQAAAmgMAOQgNAOgdAAQgNAAgFgDgAAAiMQgEgFAAgLQAAgIAEgGQAHgHAKAAQAJAAAHAHQAHAGAAAIQAAAKgHAGQgHAHgJAAQgKAAgHgHg");
	this.shape_3.setTransform(25.45,127);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhQBoIAAgUIAbAAQAFABAAgKIAAiPQAAgLgFABIgbAAIAAgUIARAAQAcAAASgEIAAAxQAOgyAqAAQATAAANAMQAKALABASQAAAdgaAAQgIAAgFgGQgFgFAAgHQgBgPARgDQgEgNgSAAQgZAAgMAYQgMAXABAnIAABHQAAAKAFgBIAcAAIAAAUg");
	this.shape_4.setTransform(1.55,127.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhSAlIAAhvQAAgJgGAAIgbAAIAAgUIBAAAIAACKQAAAvAqAAQAbAAARgYQAQgXABgkIAAhJQAAgJgGAAIgbAAIAAgUIBAAAIAACtQAAAKAGAAIAbAAIAAATIgSAAQgdAAgRAEIAAgxQgWAygwAAQhAAAAAhDg");
	this.shape_5.setTransform(-20.4,127.575);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhJBNQgcgdAAgwQAAguAcgeQAdgdAtAAQAtAAAcAdQAcAeAAAuQAAAvgcAeQgdAdgtAAQgtAAgcgdgAgzg+QgTAWAAAnIAAADQAAAnATAWQASAXAhAAQAhAAATgXQATgWAAgnIAAgDQAAgngTgWQgSgWghAAQghAAgTAWg");
	this.shape_6.setTransform(-44.525,127.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhhCCQgNgKAAgQQAAgMAGgHQAHgHAKAAQAQAAADANQACANgOAKIgIgNQAAATAXAAQARAAANgOQAMgOAPgkIAAgCIhOikQgEgJgFAAIgTAAIAAgTIBXAAIAAATIgUAAQgKAAADAJIA+CEIA4iDQAEgKgLAAIgVAAIAAgTIBPAAIAAATIgUAAQgGAAgDAJIhKCsQgSArgNAPQgSATgcAAQgUAAgMgJg");
	this.shape_7.setTransform(-68.375,131.125);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgMB0QgNgMAAgdIAAiFIgfAAIAAgRIAWgCQAOgBABgNIADglIAWAAIAAAzIAvAAIAAATIgvAAIAACFQAAASAGAHQAHAIAQAAQALAAAMgEIAAAUQgPAFgQAAQgbAAgMgNg");
	this.shape_8.setTransform(79.8,73.025);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhMBYIAAg0IAYAAIAAApQAUAKAeAAQAyAAAAglQAAgSgQgJQgLgHgbgFQghgHgPgIQgWgOAAgbQAAgbAVgRQAVgQAjAAQAoAAAeASIAAAzIgZAAIAAgnQgRgLgbAAQgxAAAAAkQAAASARAJQAJAEAcAGQAiAHAPAJQAVAPAAAbQAAAcgVARQgVAQglAAQgpAAghgSg");
	this.shape_9.setTransform(63.575,75.325);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhJBNQgcgdAAgwQAAguAcgeQAdgdAtAAQAtAAAcAdQAcAeAAAuQAAAvgcAeQgdAdgtAAQgtAAgcgdgAgzg+QgTAWAAAnIAAADQAAAnATAWQASAXAhAAQAhAAATgXQATgWAAgnIAAgDQAAgngTgWQgSgWghAAQghAAgTAWg");
	this.shape_10.setTransform(42.125,75.325);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AguCNIAAgUIAaAAQAGAAgBgJIAAjbQABgKgGAAIgaAAIAAgUIASAAQAcAAARgDIAAD8QgBAJAGAAIAZAAIAAAUg");
	this.shape_11.setTransform(24.25,71.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhGBMQgbgdAAgvQAAguAcgdQAcgeAtAAQArAAAaAbQAZAcAAAuIAAAJIijAAQAAAkATAWQAUAXAhAAQA3AAAOg0IAUAHQgHAegWARQgYASgmAAQgvAAgcgegABCgNQAAgigQgTQgRgTgeAAQgdAAgSATQgSATgDAiICDAAIAAAAg");
	this.shape_12.setTransform(-3.725,75.325);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgJBnIhLiwQgDgJgGAAIgWAAIAAgUIBcAAIAAAUIgWAAQgLAAAEAJIA5CMIA5iMQADgJgKAAIgZAAIAAgUIBWAAIAAAUIgVAAQgGAAgFAJIhJCwg");
	this.shape_13.setTransform(-27.15,75.475);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhUBbQgQgOgBgYQAAgiAjgSQAggQBJgHIAAgMQgBgbgNgMQgMgMgbAAQgkAAgPASQAOAEAAAPQgBAIgGAGQgFAFgKAAQgXAAAAgYQAAgYAagOQAYgOAkAAQApAAATARQAUARAAAkIAABsQAAAJAGAAIAaAAIAAAUIg4AAQgFgSgBgaQgKAWgUANQgVANgbAAQgcAAgSgPgAgrALQgbANAAAZQAAAQAMAKQAMAKASAAQAeAAASgUQASgVABghIAAgRQg6AGgYALg");
	this.shape_14.setTransform(-50.4,75.325);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAXCNIAAgUIAZAAQAFAAAAgJIAAhtQAAgugqAAQgcgBgRAZQgRAZAAArIAAA/QAAAJAFAAIAZAAIAAAUIheAAIAAgUIAbAAQAFAAAAgJIAAjbQAAgKgFAAIgbAAIAAgUIASAAQAdAAARgDIAAB/QAVg1AyAAQBBAAAABEIAABuQAAAJAFAAIAaAAIAAAUg");
	this.shape_15.setTransform(-75.15,71.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhhCCQgNgKAAgQQAAgMAGgHQAHgHAKAAQAQAAADANQACANgOAKIgIgNQAAATAXAAQARAAANgOQAMgOAPgkIAAgCIhOikQgEgJgFAAIgTAAIAAgTIBXAAIAAATIgUAAQgKAAADAJIA+CEIA4iDQAEgKgLAAIgVAAIAAgTIBPAAIAAATIgUAAQgGAAgDAJIhKCsQgSArgNAPQgSATgcAAQgUAAgMgJg");
	this.shape_16.setTransform(71.925,27.125);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhTBbQgRgOAAgYQAAgiAigSQAggQBIgHIAAgMQAAgbgNgMQgMgMgbAAQglAAgOASQANAEAAAPQAAAIgFAGQgHAFgJAAQgXAAAAgYQAAgYAagOQAYgOAlAAQAoAAAUARQATARAAAkIAABsQAAAJAGAAIAZAAIAAAUIg3AAQgFgSgBgaQgJAWgWANQgUANgaAAQgdAAgRgPgAgrALQgbANAAAZQAAAQAMAKQAMAKASAAQAeAAASgUQASgVAAghIAAgRQg4AGgZALg");
	this.shape_17.setTransform(48.75,23.325);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("ABQBoIAAgTIAYAAQAFgBAAgIIAAhkQABgdgKgOQgKgOgXAAQg0AAAABOIAABPQAAAIAHABIAbAAIAAATIheAAIAAgTIAZAAQAFgBAAgIIAAhqQAAgzgqAAQg0AAAABOIAABPQABAIAFABIAaAAIAAATIhfAAIAAgTIAaAAQAGgBAAgIIAAiRQAAgJgGgBIgaAAIAAgTIASAAQAcAAARgDIAAAoQASgqAsAAQAxAAAKAxQASgxAuAAQBBAAAABNIAABmQAAAIAGABIAaAAIAAATg");
	this.shape_18.setTransform(18.25,23.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhSAlIAAhvQAAgJgGAAIgbAAIAAgUIBAAAIAACKQAAAvAqAAQAbAAARgYQAQgXABgkIAAhJQAAgJgGAAIgbAAIAAgUIBAAAIAACtQAAAKAGAAIAbAAIAAATIgSAAQgdAAgRAEIAAgxQgWAygwAAQhAAAAAhDg");
	this.shape_19.setTransform(-23.55,23.575);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AhJBNQgcgdAAgwQAAguAcgeQAdgdAtAAQAtAAAcAdQAcAeAAAuQAAAvgcAeQgdAdgtAAQgtAAgcgdgAgzg+QgTAWAAAnIAAADQAAAnATAWQASAXAhAAQAhAAATgXQATgWAAgnIAAgDQAAgngTgWQgSgWghAAQghAAgTAWg");
	this.shape_20.setTransform(-47.675,23.325);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgyCLIAAgTIAdAAQAGAAgBgKIAAhjIhOh6QgEgIgHAAIgYAAIAAgUIBnAAIAAAUIgcAAQgJABAGAHIA9BlIBAhlQACgCgBgDIgEgDIgeAAIAAgUIBfAAIAAAUIgZAAQgHAAgGAIIhNB4IAABlQAAAKAFAAIAcAAIAAATg");
	this.shape_21.setTransform(-70.6,19.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(-148.9,0,297.9,150), null);


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgxAQIAWgQIgWgPIAAgcIAxAlIAAANIgxAlgAADAOIAVgOIgVgNIAAgaIAvAhIAAANIgvAhg");
	this.shape.setTransform(78.2,34.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAiBFIghhXIghBXIgaAAIgnhtQgDgHgEAAIgJAAIAAgVIBEAAIAAAVIgJAAQgHAAADAIIAWBAIAXhAQADgIgIAAIgHAAIAAgVIBCAAIAAAVIgJAAQgIAAADAIIAaBAIAWg/QACgJgHAAIgKAAIAAgVIA2AAIAAAVIgJAAQgEAAgDAHIgnBtg");
	this.shape_1.setTransform(52.375,34.75);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag0A0QgTgUAAggQgBgfAVgUQAUgUAgAAQAgAAATAUQAVAUAAAfQAAAggVAUQgUAUggAAQggAAgUgUgAghgBIAAADQAAAwAhAAQAjAAgBgwIAAgDQABgvgjAAQghAAAAAvg");
	this.shape_2.setTransform(32.05,34.675);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AALBGIAAgVIALAAQAEAAAAgIIAAg6QAAgcgWABQgdAAAAAsIAAApQAAAIAFAAIALAAIAAAVIhHAAIAAgVIAMAAQAFAAABgIIAAhNQgBgIgFAAIgMAAIAAgWIAWAAQAUAAANgCIAAAbQAMgcAhAAQAsAAAAAzIAAA7QAAAIAEAAIANAAIAAAVg");
	this.shape_3.setTransform(14.95,34.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhEBXQgLgIAAgOQAAgLAHgHQAGgGALAAQANAAAEAJQAFAKgHAMQASgBANgeIAAgBIgxhpQgEgHgEAAIgJAAIAAgVIBIAAIAAAVIgLAAQgIAAAEAIIAdBBIAbhAQADgJgJAAIgLAAIAAgVIA7AAIAAAVIgLAAQgGAAgDAHIgtBrQgMAdgLALQgNAMgVAAQgRAAgJgHg");
	this.shape_4.setTransform(-10.175,37.275);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgiBeIAAgVIAMAAQAFAAAAgHIAAh/QAAgJgFAAIgNAAIAAgVIAXAAQATAAANgCIAACfQAAAHAEAAIAMAAIAAAVg");
	this.shape_5.setTransform(-23.125,32.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhQBeIAAgVIAMAAQAFAAABgHIAAh+QgBgIgFAAIgMAAIAAgWIAWAAQAUAAANgCIAAAfQANggAiAAQAbAAARATQAQAUAAAgQAAAggRAUQgRAUgcgBQggAAgNgcIAAAtQAAAHAFAAIANAAIAAAVgAgPg6QgKAMAAAXIAAAEQAAAVAKAMQAIALAPAAQAQAAAJgLQAJgMAAgVIAAgEQAAgXgJgMQgJgLgQABQgPgBgIALg");
	this.shape_6.setTransform(-36.8,36.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhQBeIAAgVIAMAAQAGAAgBgHIAAh+QABgIgGAAIgNAAIAAgWIAXAAQAVAAALgCIAAAfQANggAjAAQAbAAAQATQARAUgBAgQAAAggRAUQgQAUgcgBQggAAgNgcIAAAtQAAAHAFAAIAMAAIAAAVgAgQg6QgJAMAAAXIAAAEQAAAVAJAMQAKALAOAAQAQAAAJgLQAKgMAAgVIAAgEQAAgXgKgMQgJgLgQABQgOgBgKALg");
	this.shape_7.setTransform(-54.85,36.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAUBdIAAgUIANAAQAIgBgDgHIgMghIhBAAIgMAhQgDAHAIABIAOAAIAAAUIhDAAIAAgUIAOAAQAEgBACgBQACgCACgEIA9ieIAhAAIA9CeQADAHAGABIALAAIAAAUgAAUALIgZhFIgbBFIA0AAg");
	this.shape_8.setTransform(-74.5,32.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00A7B5").s().p("A3TFYIAAqvMAunAAAIAAKvg");
	this.shape_9.setTransform(0.025,34.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTA, new cjs.Rectangle(-149.2,0,298.5,68.8), null);


(lib.covwhiteRGBai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// co-v-white-RGB.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(526.5006,189.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(271.9321,70.8329);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(494.55,205.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(438.825,205.55);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(386.35,217.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(336.35,205.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(296.35,205.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(236.525,200.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(171.8,205.55);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(132.5,205.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(85.3,205.55);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(28.225,200.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0.1,533.9,251.3);


(lib.BKGD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00778B").s().p("A3bM5IAA5xMAu3AAAIAAZxg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGD2, new cjs.Rectangle(-150,-82.5,300,165), null);


// stage content:
(lib.CO_LostYourJob_300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_158 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(158).call(this.frame_158).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgXWguyMAutAAAMAAABdlMgutAAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(159));

	// CO logo V
	this.instance = new lib.covwhiteRGBai("synched",0);
	this.instance.setTransform(98.1,525.05,0.2678,0.2678,0,0,0,267,125.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(159));

	// HS logo
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjkBkIAEimIEygDIgBgsICKgBIAJDlgABzADQgDAIAAAIQAAAIADAIQAFATAZAAQARAAALgMQAAAAAAAAQABAAAAAAQAAgBgBAAQAAAAAAAAIgKgJIgBAAQgGAGgKAAQgLAAgCgJIgCgEIACAAIAoAAQAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAgPgCgFQgGgSgWAAQgXAAgGASgAgVAhQAAAKAHAGQAGAFAJAAQAMAAAGgIIAAAFQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAAAAAIAQAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIAAgrQAAgMgHgFQgGgGgQAAQgQAAgIAGIgBACIAHAKQAAAAAAABQAAAAAAAAQABAAAAAAQAAgBAAAAQAHgDAHAAQAOAAAAAIIAAADIgBABIgMAAQgbAAAAAVgAikAfIgJAKQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAQANALASAAQAOAAAHgHQAJgGgBgKQABgTgXgCIgHAAQgJgCAAgEQAAgFAIAAQAKAAAIAFIACAAIAIgJQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAQgLgIgQAAQgcAAAAAUQAAASAWADIAHAAQAKACAAAEQAAAHgLAAQgKAAgKgIIgBAAIgBAAgAA5gMIAAA/QAAAAAAAAQAAABAAAAQABAAAAAAQAAAAAAAAIARAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgjQABgPAJAAQAFAAAGADIACAAIAHgNQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQgFgEgHAAQgNAAgFAIIAAgFQAAgBAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgRAAQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABgAg4AMIAAAnQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQAAAAAAgBQABAAAAAAIAAgqQgBgLgGgGQgFgHgMAAQgLAAgGAHIAAAAIAAggIgBgBIgRAAIgBABIAABbQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIARAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIAAgnQAAgMAKAAQALAAAAAMg");
	this.shape_1.setTransform(247.9,532.925);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgKAAQAAgGALAAIAJAAIABAAIAAAFQAAAIgLAAQgKAAAAgHg");
	this.shape_2.setTransform(248.675,536.125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgKAHIgBgBIABgFQACgHAIAAQAJAAADAHIAAAFIgBABg");
	this.shape_3.setTransform(262.25,533.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AjohvIHUAQIADDKIndAFgAgmAdQAAAUAWABQANgBAFgGIAAADQAAABAAAAQAAAAAAABQABAAAAAAQAAAAABAAIAPAAQAAAAABAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAgrQABgLgHgGQgHgFgQAAQgPgBgKAHQAAAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIAGALQAAAAABAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAHgEAIAAQANAAAAAIIAAADIgBABIgLAAQgcgBAAAWgAhvgBQgCAFAAALQAAAJADAGQAFAUAYAAQASAAAKgMQABAAAAAAQAAAAAAgBQAAAAAAAAQAAAAgBgBIgJgIQAAgBAAAAQAAAAgBAAQAAAAAAAAQAAAAgBABQgHAGgIAAQgLAAgDgJIgBgEIABgBIApAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAgNgCgHQgHgSgWAAQgXgBgGATgABPgRIAAALQAAABAAAAQAAAAAAABQABAAAAAAQAAAAAAAAIAFAAIABABIAAAdQgBAMAFAFQAFAGALAAIAIAAQAAAAABAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAgNQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgEAAQgFgBAAgGIAAgdIABgBIAIAAQAAAAABAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAgLQAAAAAAAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgIAAIgBgBIAAgSQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBgBAAAAIgQAAQgBAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAASIgBABIgFAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAgAAngsIAABHQAAAWAVAAIAHAAQAAAAABAAQAAAAAAAAQAAgBAAAAQABAAAAgBIAAgNQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgDAAQgGAAABgHIAAhGQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBgBAAAAIgRAAQAAAAAAABQgBAAAAAAQAAAAAAAAQAAABAAAAgACvAIIAAAmQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIARAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAgBIAAgpQAAgLgGgHQgGgGgLAAQgMAAgGAHIAAggQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBgBAAAAIgRAAQAAAAAAABQAAAAgBAAQAAAAAAAAQAAABAAAAIAABaQAAABAAAAQAAAAAAABQABAAAAAAQAAAAAAAAIARAAQAAAAABAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAgmQAAgLALAAQALAAAAALgAiVAIIAAAmQAAABAAAAQAAAAAAABQABAAAAAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQAAgBAAAAQABAAAAgBIAAgpQgBgLgFgHQgGgGgMAAQgMAAgFAHIAAggQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAgBgBAAIgQAAQAAAAgBABQAAAAAAAAQAAAAAAAAQgBABAAAAIAABaQAAABABAAQAAAAAAABQAAAAAAAAQABAAAAAAIAQAAQABAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAgBIAAgmQAAgLAKAAQALAAAAALg");
	this.shape_4.setTransform(231.1,514.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgKAAQAAgGALAAIAJAAIABAAIAAAFQAAAIgLAAQgKAAAAgHg");
	this.shape_5.setTransform(230.175,516.975);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgKAHIgBgBIABgFQACgHAIAAQAJAAACAHIABAFIgBABg");
	this.shape_6.setTransform(222.8,514.275);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ADZARIAKAAQAAADAEAAQAGAAAAgEIAAgDQgDACgEAAQgGAAgEgFQgEgEAAgGQAAgGAEgEQAEgEAGAAQAEAAADACIAAgBIAKAAIAAAcQAAAGgEAEQgFADgGAAQgOABgBgMgADiAAQAAAGAGAAQAFAAAAgGIAAAAQAAgFgFAAQgGgBAAAGgAEAALQgEgFAAgGQAAgGAEgEQAEgEAHAAQAHAAAEAEQAFAEAAAGQAAAGgFAFQgEAEgHAAQgHAAgEgEgAEGAAQAAAGAFAAQAFAAAAgGQAAgGgFABQgFgBAAAGgAC7ALQgEgEAAgHQAAgGAEgEQAEgEAHAAQAOAAAAAOIAAACIgSAAQAAAFAEAAQABAAAAAAQABAAABgBQAAAAAAAAQABgBAAAAIAKABQgBADgEAEQgEACgFAAQgGAAgFgEgADKgCQAAgFgEAAQgEAAAAAFIAIAAIAAAAgAB3AJQgGgGAAgIQAAgKAGgFQAGgHAKAAQAKAAAGAHQAGAFAAAKQAAAIgGAGQgGAGgKAAQgKAAgGgGgAB8gFQAAAKALABQALgBAAgKQAAgMgLAAQgLAAAAAMgAAwALQgEgFAAgGQAAgGAEgEQAEgEAHAAQAHAAAEAEQAFAEAAAGQAAAGgFAFQgEAEgHAAQgHAAgEgEgAA2AAQAAAGAFAAQAGAAAAgGQAAgGgGABQgFgBAAAGgAADALQgDgEAAgHQAAgGADgEQAEgEAHAAQAOAAAAAOIAAACIgSAAQAAAFAEAAQAAAAABAAQABAAAAgBQABAAAAAAQAAgBAAAAIAKABQAAADgEAEQgEACgFAAQgGAAgFgEgAASgCQAAgFgEAAQgEAAAAAFIAIAAIAAAAgAg1AGQAAgHANgBIADAAIAAgBQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAQgBAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAABIgKAAQAAgFADgCQAEgEAFAAQANAAAAAMIAAAQIgKAAIAAgCQgCADgFAAQgJAAAAgJgAgoAEQgBAAAAAAQgBAAAAAAQAAAAgBABQAAAAAAABQAAAAAAAAQAAABABAAQAAAAAAAAQABAAAAAAQABAAABAAQAAAAABAAQAAgBABAAQAAgBAAAAIAAgCgAh8ABIALgBQAAAGAGAAQAFAAAAgEQAAgCgHgBQgHgCgDgCQgEgDAAgFQAAgOAPAAQAPAAABAOIgLABQAAgFgFAAQgEAAAAAEQAAACAHABQAOAEAAAIQAAANgQAAQgRAAAAgOgAi+AFIAAgKIgFAAIAAgIIAFAAIAAgJIAKAAIAAAJIAGAAIAAAIIgGAAIAAAHQAAAEAEAAIACAAIAAAJIgFAAQgMAAABgKgAjxAGQAAgHAMgBIADAAIAAgBQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAABIgKAAQAAgFAEgCQAEgEAFAAQAMAAAAAMIAAAQIgJAAIAAgCQgDADgEAAQgJAAAAgJgAjkAEQgBAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAQABAAAAAAQABAAAAAAQABgBAAAAQAAgBAAAAIAAgCgAkOALQgEgEAAgHQAAgGAEgEQAEgEAGAAQAOAAAAAOIAAACIgSAAQAAAFAEAAQABAAABAAQAAAAABgBQAAAAABAAQAAgBAAAAIAKABQgBAJgMAAQgHAAgEgEgAkAgCQAAgFgEAAQgDAAgBAFIAIAAIAAAAgAEyAOIAAgOQAAgFgEAAQgEAAAAAFIAAAOIgKAAIAAgbIAKAAIAAABQACgCAFAAQALAAAAAMIAAAQgACiAOIAAgbIAKAAIAAACQACgCAGAAIAAAJQgIAAAAAFIAAANgABSAOIAAgTIgFAAIAAgIIAFAAIAAgCQAAgFADgEQAEgDAGgBIADAAIAAAJIgCAAQgEAAAAADIAAADIAGAAIAAAIIgGAAIAAATgAgVAOIAAgbIAKAAIAAACQACgCAFAAIAAAJQgHAAAAAFIAAANgAhEAOIAAgOQAAgFgEAAQgEAAAAAFIAAAOIgKAAIAAgqIAKAAIAAAQQACgCAFAAQALAAAAAMIAAAQgAiXAOIAAgOQAAgFgEAAQgDAAAAAFIAAAOIgKAAIAAgqIAKAAIAAAQQABgCAFAAQALAAAAAMIAAAQgAjRAOIAAgqIAKAAIAAAqgAkjAOIAAgPIgNAAIAAAPIgLAAIAAgoIALAAIAAAQIANAAIAAgQIALAAIAAAog");
	this.shape_7.setTransform(239.025,551.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(159));

	// HEAD1
	this.instance_1 = new lib.HEAD1();
	this.instance_1.setTransform(150,65);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(106).to({alpha:0},5).to({_off:true},1).wait(47));

	// HEAD2
	this.instance_2 = new lib.HEAD2();
	this.instance_2.setTransform(150,65);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(48).to({_off:false},0).to({alpha:1},5).wait(53).to({alpha:0},5).to({_off:true},1).wait(47));

	// HEAD4
	this.instance_3 = new lib.HEAD4();
	this.instance_3.setTransform(150,119,1,1,0,0,0,0,49);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(111).to({_off:false},0).to({alpha:1},5).wait(43));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_154 = new cjs.Graphics().p("EgXbAjTIAA4NMAu3AAAIAAYNg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(154).to({graphics:mask_graphics_154,x:150,y:225.9493}).wait(5));

	// CTA
	this.instance_4 = new lib.CTA();
	this.instance_4.setTransform(149.2,447.85);
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(154).to({_off:false},0).to({y:383},4,cjs.Ease.quadOut).wait(1));

	// bkgd2
	this.instance_5 = new lib.BKGD2();
	this.instance_5.setTransform(150.1,165.9,1,2.0001,0,0,0,0.1,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(43).to({regX:0,regY:0.4,scaleY:2.0002,x:150,y:165.7},0).to({regX:0.1,scaleY:2.7243,x:150.1,y:226.15},5,cjs.Ease.quadOut).wait(111));

	// bkgd
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF8300").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_8.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(159));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149.5,299.5,151,301);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 300,
	height: 600,
	fps: 24,
	color: "#999999",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;