(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.HEAD4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgGAHQgDgCAAgFQAAgDADgDQADgDADAAQAFAAADADQADADAAADQAAAFgDACQgDADgFAAQgDAAgDgDg");
	this.shape.setTransform(55.55,271.425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAKAvIAAgJIALAAQABAAAAAAQABAAAAgBQABAAAAgBQAAgBAAgBIAAgwQAAgWgTAAQgNAAgHALQgIALAAAUIAAAcQAAABAAABQAAABABAAQAAABAAAAQABAAABAAIALAAIAAAJIgrAAIAAgJIANAAQAAAAABAAQAAAAAAgBQABAAAAgBQAAgBAAgBIAAhAQAAgFgCAAIgNAAIAAgJIAIAAQANAAAIgCIAAAZQAJgZAXAAQAdAAAAAgIAAAwQAAABAAABQAAABABAAQAAABAAAAQABAAABAAIAMAAIAAAJg");
	this.shape_1.setTransform(47.3,267.55);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AglApQgIgHAAgKQAAgPAQgJQAOgGAggEIAAgFQAAgMgFgFQgGgGgMAAQgQAAgHAIQAGACAAAHQAAADgDADQgCACgEABQgLgBAAgKQAAgLAMgHQALgGAQAAQASAAAJAIQAJAHAAARIAAAwQAAABAAABQAAABAAAAQABABAAAAQABAAAAAAIAMAAIAAAJIgZAAQgCgIgBgMQgEAKgKAGQgIAGgMAAQgNAAgIgHgAgTAFQgMAFAAAMQAAAHAFAFQAFAFAJAAQANgBAIgIQAIgKAAgPIAAgHQgZACgLAFg");
	this.shape_2.setTransform(35.925,267.65);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUBAIAAgJIALAAQABAAABAAQAAgBAAAAQABgBAAAAQAAgBAAgBIAAhjQAAgFgDAAIgLAAIAAgIIAIAAQAMAAAHgCIAAByQABABAAABQAAAAAAABQAAAAABABQAAAAABAAIAMAAIAAAJg");
	this.shape_3.setTransform(27.15,265.875);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgvA/IAAgJIAMAAQADAAAAgFIAAhiQAAgFgDAAIgMAAIAAgIIAxAAQAuAAAAAjQAAAUgMAIQgKAIgYABIgUAAIAAAnQAAAFADAAIAMAAIAAAJgAgSABIAUAAQAQAAAHgGQAIgGAAgPQAAgOgIgHQgHgGgQgBIgUAAg");
	this.shape_4.setTransform(18.35,265.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAKBAIAAgJIALAAQABAAABAAQAAgBAAAAQABgBAAAAQAAgBAAgBIAAgxQAAgVgTAAQgMAAgIALQgIALAAATIAAAdQAAABABABQAAAAAAABQAAAAABABQAAAAABAAIAMAAIAAAJIgsAAIAAgJIAMAAQABAAABAAQAAgBAAAAQABgBAAAAQAAgBAAgBIAAhjQAAgFgDAAIgMAAIAAgIIAIAAQAOAAAHgCIAAA6QAKgYAWAAQAdAAAAAeIAAAyQAAABAAABQAAAAABABQAAAAAAABQABAAAAAAIANAAIAAAJg");
	this.shape_5.setTransform(1.3,265.875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgFA0QgGgFAAgNIAAg8IgOAAIAAgIIAKAAQAGgBABgGIABgQIAJAAIAAAWIAWAAIAAAJIgWAAIAAA8QAAAIAEADQACAEAIAAQAEAAAGgCIAAAJQgGACgIAAQgMAAgFgGg");
	this.shape_6.setTransform(-8.05,266.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgUBAIAAgJIALAAQABAAABAAQAAgBAAAAQABgBAAAAQAAgBAAgBIAAhjQAAgFgDAAIgLAAIAAgIIAIAAQAMAAAIgCIAAByQAAABAAABQAAAAAAABQAAAAABABQAAAAABAAIALAAIAAAJg");
	this.shape_7.setTransform(-14.35,265.875);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AglApQgIgHAAgKQAAgPAQgJQAOgGAggEIAAgFQAAgMgFgFQgGgGgMAAQgQAAgHAIQAGACAAAHQAAADgDADQgCACgEABQgLgBAAgKQAAgLAMgHQALgGAQAAQASAAAJAIQAJAHAAARIAAAwQAAABAAABQAAABAAAAQABABAAAAQABAAAAAAIAMAAIAAAJIgZAAQgCgIgBgMQgEAKgKAGQgIAGgMAAQgNAAgIgHgAgTAFQgMAFAAAMQAAAHAFAFQAFAFAJAAQANgBAIgIQAIgKAAgPIAAgHQgZACgLAFg");
	this.shape_8.setTransform(-22.625,267.65);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgfAiQgMgNAAgVQAAgUAMgNQANgOAUAAQATAAAMAMQALANAAAVIAAADIhJAAQAAAQAJALQAJAKAOAAQAZAAAGgYIAJADQgDAOgKAIQgLAIgRAAQgUAAgNgOgAAegFQAAgQgIgIQgHgJgOAAQgMAAgIAJQgJAJgBAPIA7AAIAAAAg");
	this.shape_9.setTransform(-33.775,267.65);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AASA/IAAgJIAMAAQADAAAAgFIAAgtIhBAAIAAAtQAAAFADAAIAMAAIAAAJIgsAAIAAgJIAMAAQADAAAAgFIAAhiQAAgFgDAAIgMAAIAAgIIAsAAIAAAIIgMAAQgDAAAAAFIAAAtIBBAAIAAgtQAAgFgDAAIgMAAIAAgIIAsAAIAAAIIgMAAQgDAAAAAFIAABiQAAAFADAAIAMAAIAAAJg");
	this.shape_10.setTransform(-46.275,265.95);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAKAvIAAgJIALAAQADAAAAgEIAAgwQAAgWgTAAQgMAAgIALQgIALAAAUIAAAcQAAABAAABQAAABABAAQAAABAAAAQABAAABAAIALAAIAAAJIgrAAIAAgJIANAAQAAAAABAAQAAAAAAgBQABAAAAgBQAAgBAAgBIAAhBQAAgEgCAAIgNAAIAAgJIAIAAQAOAAAHgBIAAAXQAJgYAXAAQAdAAAAAfIAAAxQAAABAAABQAAABABAAQAAABAAAAQABAAABAAIALAAIAAAJg");
	this.shape_11.setTransform(27.7,246.55);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AghAjQgMgOAAgVQAAgVANgNQAMgNAUAAQAVAAAMANQANAOAAAUQAAAVgNAOQgNANgUAAQgUAAgNgNgAgXgbQgIAKAAARIAAABQAAARAIAKQAJALAOAAQAPAAAJgLQAIgKAAgRIAAgBQAAgRgIgKQgJgLgPABQgOgBgJALg");
	this.shape_12.setTransform(16.025,246.65);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgyAyQAAgPAXgFQgRgDAAgOQAAgMAPgEQgOgJAAgRQAAgOALgKQAMgJAQAAQASAAALAKQADgRANAAQAFAAACACQADADAAAEQAAADgCADQgDACgDAAQgHAAAAgGQgFAEgCAHQAGAIgBAKQAAAPgLAJQgLAIgQAAQgKAAgIgDQgMACABAIQAAAIAOAAIAjAAQAeAAAAAXQAAAOgOAIQgNAHgXAAQguAAAAgUgAgmAxQAAAOAiAAQAmAAAAgTQAAgHgEgDQgFgDgMAAIgdAAQgWAFAAANgAgWgvQgHAGAAAMIAAABQAAALAHAGQAHAHALAAQAKAAAHgHQAIgGAAgLIAAgBQAAgMgIgGQgGgHgLAAQgLAAgHAHg");
	this.shape_13.setTransform(5.05,248.175);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgfAjQgMgOAAgVQAAgUAMgOQANgNAUAAQATAAAMAMQALANAAAVIAAADIhJAAQAAAQAJAKQAJALAOAAQAZAAAGgYIAJADQgDAOgKAHQgLAJgRAAQgUAAgNgNgAAegFQAAgQgIgIQgHgJgOAAQgMAAgIAJQgJAIgBAQIA7AAIAAAAg");
	this.shape_14.setTransform(-5.975,246.65);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgkAvIAAgJIAMAAQABAAAAAAQABAAAAgBQAAAAABgBQAAgBAAgBIAAhBQAAgEgDAAIgMAAIAAgJIAIAAQANAAAIgBIAAAVQAGgWASAAQAKAAAFAFQAFAGAAAHQAAANgLAAQgEABgDgDQgCgCAAgEQAAgGAHgCQgBgGgIABQgMgBgEALQgGAKAAASIAAAgQAAABAAABQABABAAAAQAAABABAAQAAAAABAAIALAAIAAAJg");
	this.shape_15.setTransform(-15.825,246.55);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgsAvQgQgSgBgdQABgcAQgSQASgSAaAAQAcAAARASQAQASABAcQAAAdgSASQgRASgbAAQgbAAgRgSgAghgoQgNAOAAAZIAAADQAAAZANAPQANANAUAAQAVAAANgNQAMgPAAgZIAAgDQABgZgNgOQgNgOgVgBQgUABgNAOg");
	this.shape_16.setTransform(-27.5,244.95);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgfAjQgMgNAAgWQAAgUAMgNQANgOAUAAQATAAAMANQALAMAAAVIAAADIhJAAQAAARAJAKQAJAKAOAAQAZAAAGgYIAJAEQgDANgKAHQgLAJgRAAQgUAAgNgNgAAegFQAAgQgIgJQgHgIgOAAQgMAAgIAIQgJAJgBAQIA7AAIAAAAg");
	this.shape_17.setTransform(36.025,225.65);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AALBAIAAgJIALAAQAAAAABgBQAAAAAAAAQABgBAAgBQAAAAAAgBIAAgxQAAgVgTAAQgMAAgIALQgHALAAATIAAAdQAAABAAAAQAAABAAABQAAAAABAAQAAABABAAIALAAIAAAJIgqAAIAAgJIAMAAQAAAAABgBQAAAAAAAAQABgBAAgBQAAAAAAgBIAAhjQAAgFgCAAIgMAAIAAgIIAHAAQAOAAAIgCIAAA6QAJgYAWAAQAdAAAAAeIAAAyQAAABAAAAQAAABABABQAAAAAAAAQABABABAAIALAAIAAAJg");
	this.shape_18.setTransform(24.65,223.875);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgFA0QgGgFAAgNIAAg8IgOAAIAAgIIAKAAQAHgBAAgGIABgQIAKAAIAAAWIAVAAIAAAJIgWAAIAAA8QAAAIADADQAEAEAGAAQAFAAAGgCIAAAJQgHACgGAAQgNAAgFgGg");
	this.shape_19.setTransform(15.3,224.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAkAvIAAgJIALAAQABAAAAAAQABgBAAAAQAAgBABAAQAAgBAAgBIAAgtQAAgMgFgHQgFgGgKAAQgXAAAAAjIAAAjQAAABAAABQAAAAAAABQABAAAAABQABAAABAAIAMAAIAAAJIgqAAIAAgJIALAAQABAAAAAAQABgBAAAAQAAgBABAAQAAgBAAgBIAAgvQAAgXgTAAQgYAAAAAjIAAAjQAAABAAABQABAAAAABQAAAAABABQAAAAABAAIALAAIAAAJIgqAAIAAgJIAMAAQAAAAABAAQAAgBABAAQAAgBAAAAQAAgBAAgBIAAhBQAAgEgCAAIgMAAIAAgJIAHAAQAOAAAHgCIAAATQAIgTAUAAQAWAAAEAWQAIgWAVAAQAeAAAAAiIAAAuQAAABAAABQAAAAAAABQABAAAAABQABAAAAAAIAMAAIAAAJg");
	this.shape_20.setTransform(-1.925,225.55);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AghAjQgMgNAAgWQAAgUANgNQAMgOAUAAQAVAAAMANQANAOAAAUQAAAWgNANQgNANgUAAQgUAAgNgNgAgXgbQgIAJAAASIAAABQAAASAIAKQAJAKAOAAQAPAAAJgKQAIgKAAgSIAAgBQAAgSgIgJQgJgLgPAAQgOAAgJALg");
	this.shape_21.setTransform(-16.175,225.65);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgkAvIAAgJIAMAAQABAAAAAAQABgBAAAAQAAgBABAAQAAgBAAgBIAAhBQAAgEgDAAIgMAAIAAgJIAIAAQANAAAIgCIAAAXQAGgXASAAQAKAAAFAFQAFAFAAAIQAAAOgLAAQgEgBgDgCQgCgDAAgDQAAgHAHgBQgBgGgIAAQgMAAgEAMQgGAJAAASIAAAgQAAABAAABQABAAAAABQAAAAABABQAAAAABAAIALAAIAAAJg");
	this.shape_22.setTransform(-26.225,225.55);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgYBBIAAgJIALAAQAAAAABgBQAAAAAAAAQAAgBABgBQAAAAAAgBIAAhFIgOAAIAAgJIAOAAIAAgMQAAgaAXAAQAIAAAGADIAAAJQgFgCgGAAQgHAAgDAEQgDADAAALIAAAKIATAAIAAAJIgTAAIAABFQAAABAAAAQAAABABABQAAAAAAAAQABABAAAAIANAAIAAAJg");
	this.shape_23.setTransform(-33.675,223.775);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AhSBoQgXgbAAgrQAAgrAYgbQAXgaAmAAQAyAAATAtIAAhSQAAgJgGAAIgXAAIAAgSIAQAAQAaAAAPgDIAADkQAAAJAGgBIAXAAIAAASIg2AAIgDgoQgTAtgyAAQgmAAgYgagAg6gWQgSATAAAiIAAAFQAAAjASATQARAUAdAAQAbAAAQgUQARgUABgjIAAgDQAAgigSgUQgRgUgaAAQgdAAgRAUg");
	this.shape_24.setTransform(31.95,191.95);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("Ag/BFQgZgbAAgqQAAgqAagaQAZgbApAAQAmAAAXAZQAXAZAAApIAAAIIiSAAQAAAgAQAUQATAVAeAAQAxAAANgvIASAHQgHAbgTAPQgWARgiAAQgrAAgZgbgAA8gMQgBgfgPgRQgOgRgbAAQgbAAgQARQgQASgCAeIB2AAIAAAAg");
	this.shape_25.setTransform(9.6,195.325);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("Ag/BFQgZgbAAgqQAAgqAagaQAZgbApAAQAnAAAXAZQAWAZAAApIAAAIIiSAAQgBAgASAUQASAVAdAAQAyAAANgvIASAHQgHAbgUAPQgWARghAAQgrAAgZgbgAA8gMQgBgfgPgRQgOgRgbAAQgbAAgQARQgQASgCAeIB2AAIAAAAg");
	this.shape_26.setTransform(-11,195.325);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAVBeIAAgSIAVAAQAFAAABgIIAAhhQAAgsgnAAQgYAAgQAXQgQAWAAAmIAAA6QAAAIAFAAIAYAAIAAASIhWAAIAAgSIAYAAQAFAAAAgIIAAiCQAAgJgFAAIgYAAIAAgSIAQAAQAbAAAOgDIAAAwQASgxAvAAQA6AAAABAIAABhQAAAIAFAAIAYAAIAAASg");
	this.shape_27.setTransform(-32.85,195.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AhLAhIAAhkQABgIgGAAIgXAAIAAgSIA5AAIAAB9QAAAqAmAAQAYAAAQgVQAPgVAAghIAAhCQAAgIgGAAIgYAAIAAgSIA7AAIAACcQAAAJAEAAIAZAAIAAASIgQAAQgbAAgPADIAAgsQgTAtgtAAQg5AAgBg9g");
	this.shape_28.setTransform(21.05,155.525);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhCBFQgagaABgrQgBgqAagbQAagaAoAAQApAAAaAaQAZAbAAAqQAAArgaAaQgZAbgpAAQgoAAgagbgAgug5QgRAUAAAkIAAACQAAAkARAUQARAUAdAAQAeAAARgUQARgUAAgkIAAgCQABgjgSgVQgRgUgeAAQgdAAgRAUg");
	this.shape_29.setTransform(-0.85,155.325);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AhYB1QgMgJAAgOQAAgLAGgGQAGgHAJAAQAPAAACAMQADAMgNAJIgIgMQAAARAVAAQAQAAALgMQALgMAOghIAAgCIhHiUQgDgIgFAAIgRAAIAAgSIBPAAIAAASIgSAAQgKAAAEAIIA3B3IAyh3QAFgIgKAAIgUAAIAAgSIBIAAIAAASIgSAAQgGAAgCAIIhECbQgPAngNAOQgQARgZAAQgSAAgLgJg");
	this.shape_30.setTransform(-22.525,158.725);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AhoB/IAAgSIAXAAQAFAAAAgIIAAjEQAAgJgFAAIgYAAIAAgSIAQAAQAaAAAPgDIAAAuQAUgvAyAAQAnAAAXAaQAWAaAAAsQAAArgXAaQgXAbgnAAQgwAAgUgtIAABQQAAAIAFAAIAYAAIAAASgAgehWQgRAUAAAiIAAAEQAAAiARAUQASATAaAAQAdAAARgTQARgTAAgiIAAgFQAAgjgRgUQgRgTgdAAQgbAAgRAUg");
	this.shape_31.setTransform(26.375,118.375);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgqCAIAAgSIAYAAQAFAAAAgIIAAjHQAAgJgFAAIgYAAIAAgSIAQAAQAaAAAPgDIAADlQAAAIAEAAIAYAAIAAASg");
	this.shape_32.setTransform(9.4,111.725);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("Ag/BFQgYgbgBgqQABgqAZgaQAZgbAoAAQAoAAAWAZQAYAZAAApIAAAIIiUAAQAAAgARAUQATAVAeAAQAxAAANgvIASAHQgGAbgUAPQgXARghAAQgrAAgZgbgAA8gMQgBgfgOgRQgPgRgbAAQgaAAgRARQgRASgCAeIB3AAIAAAAg");
	this.shape_33.setTransform(-6.35,115.325);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAVCAIAAgSIAWAAQAFAAAAgIIAAhjQAAgqgmAAQgZAAgQAWQgQAWAAAnIAAA6QAAAIAGAAIAXAAIAAASIhWAAIAAgSIAYAAQAFAAAAgIIAAjHQAAgJgFAAIgZAAIAAgSIARAAQAbAAAOgDIAABzQAUgvAuAAQA5AAAAA9IAABkQAAAIAGAAIAXAAIAAASg");
	this.shape_34.setTransform(-28.15,111.725);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("Ag/BFQgYgbgBgqQABgqAZgaQAZgbAoAAQAoAAAWAZQAYAZAAApIAAAIIiUAAQAAAgARAUQASAVAfAAQAxAAANgvIASAHQgHAbgTAPQgWARgiAAQgrAAgZgbgAA8gMQgBgfgOgRQgPgRgbAAQgbAAgQARQgQASgDAeIB3AAIAAAAg");
	this.shape_35.setTransform(17.15,75.325);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAVCAIAAgSIAWAAQAFAAAAgIIAAhjQAAgqgmAAQgZAAgQAWQgPAWAAAnIAAA6QgBAIAGAAIAXAAIAAASIhWAAIAAgSIAYAAQAFAAAAgIIAAjHQAAgJgFAAIgZAAIAAgSIARAAQAbAAAPgDIAABzQATgvAuAAQA5AAAAA9IAABkQABAIAFAAIAYAAIAAASg");
	this.shape_36.setTransform(-4.65,71.725);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgLBpQgLgLAAgbIAAh3IgdAAIAAgQIAUgBQANgBABgMIADghIATAAIAAAtIArAAIAAASIgrAAIAAB3QAAARAGAHQAGAHAOAAQALAAAKgEIAAASQgNAEgOAAQgZAAgLgLg");
	this.shape_37.setTransform(-22.4,73.225);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgLBpQgLgLAAgbIAAh3IgdAAIAAgQIAVgBQAMgBABgMIADghIAUAAIAAAtIArAAIAAASIgsAAIAAB3QAAARAGAHQAGAHAPAAQAJAAALgEIAAASQgMAEgPAAQgZAAgLgLg");
	this.shape_38.setTransform(22.65,33.225);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("Ag/BFQgYgbgBgqQABgqAZgaQAZgbAoAAQAoAAAWAZQAYAZAAApIAAAIIiUAAQAAAgARAUQASAVAfAAQAxAAANgvIASAHQgHAbgTAPQgWARgiAAQgrAAgZgbgAA8gMQgBgfgOgRQgPgRgbAAQgbAAgQARQgQASgDAeIB3AAIAAAAg");
	this.shape_39.setTransform(6.35,35.325);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AhQBgQgegjAAg9QAAg6AhglQAfgiAygBQAfAAAWAOQAWANAJAZIAFgvIASAAIAABaIgXAAQgOhLhDAAQgnAAgYAdQgYAcAAAzIAAAFQAAA0AXAcQAXAcAogBQAhABAVgUQAWgUAAgkIAAgHIhEAAIAAgSIBhAAIAAB0IgOAAIgJguQgVAyhCAAQgzAAgegig");
	this.shape_40.setTransform(-17.325,31.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD4, new cjs.Rectangle(-72,14,144,265), null);


(lib.HEAD3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLALQgEgEgBgHQABgGAEgEQAFgFAGAAQAHAAAFAFQAEAEAAAGQAAAHgEAEQgFAFgHAAQgGAAgFgFg");
	this.shape.setTransform(72.7,250.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgJBTQgIgJgBgVIAAheIgWAAIAAgNIAQAAQAKgBABgKIACgaIAPAAIAAAkIAiAAIAAAOIgiAAIAABeQAAANAEAFQAGAGAKAAQAJAAAIgDIAAAPQgKADgLAAQgUAAgJgJg");
	this.shape_1.setTransform(64.35,242.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAQBKIAAgOIARAAQAFAAAAgGIAAhMQAAgjgfAAQgTAAgMARQgNASAAAeIAAAuQAAAGAEAAIATAAIAAAOIhEAAIAAgOIATAAQAEAAAAgGIAAhnQAAgHgEAAIgTAAIAAgOIAMAAQAWAAALgCIAAAmQAPgnAkAAQAuAAAAAyIAABNQAAAGAEAAIATAAIAAAOg");
	this.shape_2.setTransform(50.225,244.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgyA2QgTgVAAghQAAghAUgVQAUgVAgAAQAfAAASATQASAVAAAgIAAAGIh0AAQAAAaAOAPQAOARAXAAQAnAAAKglIAPAFQgGAVgPAMQgRAOgbAAQgiAAgUgWgAAvgJQAAgYgMgOQgLgOgWAAQgUAAgNAOQgNAOgCAYIBdAAIAAAAg");
	this.shape_3.setTransform(32.725,244.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA5BKIAAgOIARAAQAFAAAAgGIAAhHQAAgVgIgKQgHgJgRAAQgkAAAAA3IAAA4QAAAGAFAAIATAAIAAAOIhDAAIAAgOIARAAQAFAAAAgGIAAhLQAAgkgfAAQgkAAgBA3IAAA4QAAAGAFAAIASAAIAAAOIhEAAIAAgOIATAAQAFAAAAgGIAAhnQAAgHgFAAIgTAAIAAgOIANAAQAUAAAMgCIAAAdQANgeAfAAQAjAAAHAjQANgjAhAAQAvAAAAA3IAABIQAAAGAEAAIATAAIAAAOg");
	this.shape_4.setTransform(11.2,244.075);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgJBTQgIgJgBgVIAAheIgWAAIAAgNIAQAAQAKgBABgKIACgaIAQAAIAAAkIAhAAIAAAOIgiAAIAABeQAAANAEAFQAGAGAKAAQAJAAAIgDIAAAPQgKADgLAAQgUAAgJgJg");
	this.shape_5.setTransform(-7.3,242.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag7BBQgMgLAAgQQAAgZAYgNQAXgKAzgGIAAgIQAAgUgJgJQgJgIgTAAQgaAAgKANQAJADAAAKQAAAHgEAEQgEADgHAAQgQAAAAgRQAAgRASgKQASgKAZAAQAdAAAOAMQAOANAAAaIAABMQAAAGAEABIASAAIAAANIgnAAQgEgMgBgTQgGAQgPAKQgPAJgSAAQgVAAgMgLgAgfAIQgTAJAAARQAAANAJAGQAIAIANAAQAVAAANgPQANgOAAgYIAAgMQgoAEgSAIg");
	this.shape_6.setTransform(-20.225,244.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgyA2QgTgVAAghQAAghAUgVQAUgVAgAAQAfAAASATQASAVAAAgIAAAGIh0AAQAAAaAOAPQAOARAXAAQAnAAAKglIAPAFQgGAVgPAMQgRAOgbAAQgiAAgUgWgAAvgJQAAgYgMgOQgLgOgWAAQgUAAgNAOQgNAOgCAYIBdAAIAAAAg");
	this.shape_7.setTransform(-37.225,244.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag5BKIAAgOIATAAQAEAAAAgGIAAhnQAAgHgEAAIgTAAIAAgOIAMAAQAVAAAMgCIAAAiQAKgjAeAAQAOAAAIAIQAIAIAAANQAAAVgSAAQgFAAgEgEQgEgEgBgFQAAgLAMgCQgDgJgMAAQgSAAgIARQgJAQAAAcIAAAzQAAAGAFAAIATAAIAAAOg");
	this.shape_8.setTransform(-52.2,244.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgIBTQgJgJAAgVIAAheIgXAAIAAgNIAQAAQAKgBAAgKIADgaIAPAAIAAAkIAiAAIAAAOIgiAAIAABeQAAANAFAFQAFAGAKAAQAIAAAJgDIAAAPQgKADgLAAQgUAAgIgJg");
	this.shape_9.setTransform(-64.15,242.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgyA3QgTgWAAghQAAghAUgUQAUgWAgAAQAfAAASAUQASATAAAhIAAAGIh0AAQAAAaAOAQQAOAQAXAAQAnAAAKglIAPAFQgGAVgPANQgRANgbAAQgiAAgUgVgAAvgJQAAgZgMgNQgLgOgWAAQgUAAgNAOQgNAOgCAYIBdAAIAAAAg");
	this.shape_10.setTransform(15.625,212.25);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag2A/IAAglIARAAIAAAdQAOAHAWAAQAjAAAAgaQAAgNgLgHQgIgFgTgDQgYgFgLgGQgPgKAAgTQAAgUAPgLQAPgMAYAAQAeAAAVANIAAAlIgSAAIAAgcQgMgJgUABQgjAAABAaQAAAMAMAHQAGADAUAEQAYAEALAHQAPAKAAAUQAAAUgOAMQgQAMgaAAQgdAAgYgNg");
	this.shape_11.setTransform(0.35,212.25);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag6AaIAAhPQAAgGgFAAIgTAAIAAgOIAuAAIAABiQAAAhAeAAQATAAAMgQQAMgRAAgZIAAg1QAAgGgEAAIgTAAIAAgOIAtAAIAAB7QAAAHAEAAIAUAAIAAAOIgNAAQgVAAgMACIAAgiQgPAjgiAAQgvAAABgwg");
	this.shape_12.setTransform(-15.85,212.425);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgyA2QgTgVAAghQAAghAUgVQAUgVAgAAQAfAAASATQASAUAAAiIAAAFIh0AAQAAAaAOAPQAOARAXAAQAnAAAKglIAPAFQgGAVgPAMQgRAOgbAAQgiAAgUgWgAAvgJQAAgZgMgNQgLgOgWAAQgUAAgNAOQgNAOgCAYIBdAAIAAAAg");
	this.shape_13.setTransform(64.275,180.25);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgxA3QgUgVAAgiQAAghAVgVQAVgVAgAAQAdAAASANQASAPAAAWQAAAKgGAFQgFAGgIAAQgGAAgFgEQgEgEAAgGQAAgOAPgCQgHgbgmAAQgXAAgPAQQgOAQAAAcIAAABQAAAcANAQQAOARAYAAQAnAAAKglIAPAEQgNAwg0AAQghAAgUgVg");
	this.shape_14.setTransform(48.125,180.25);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAQBKIAAgOIARAAQAFAAAAgGIAAhMQAAgjgfAAQgTAAgMARQgNASAAAeIAAAuQAAAGAEAAIATAAIAAAOIhEAAIAAgOIATAAQAEAAAAgGIAAhnQAAgHgEAAIgTAAIAAgOIAMAAQAWAAALgCIAAAmQAPgnAkAAQAuAAAAAyIAABNQAAAGAEAAIATAAIAAAOg");
	this.shape_15.setTransform(30.625,180.075);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag7BBQgMgKAAgSQAAgXAYgOQAXgLAzgFIAAgJQAAgSgJgKQgJgIgTAAQgaAAgKANQAJADAAAKQAAAHgEAEQgEADgHABQgQAAAAgSQAAgRASgKQASgKAZAAQAdAAAOAMQAOANAAAZIAABNQAAAGAEABIASAAIAAANIgnAAQgEgMgBgSQgGAPgPAKQgPAJgSAAQgVAAgMgLgAgfAIQgTAJAAARQAAANAJAGQAIAIANAAQAVAAANgPQANgPAAgXIAAgMQgoAEgSAIg");
	this.shape_16.setTransform(13.275,180.25);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgJBTQgIgJgBgUIAAhfIgWAAIAAgMIAQgBQAKgBABgKIACgaIAQAAIAAAkIAhAAIAAAOIgiAAIAABfQAAAMAEAGQAGAFAKAAQAJAAAIgDIAAAPQgKADgMAAQgTAAgJgJg");
	this.shape_17.setTransform(-0.65,178.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag2A+IAAgkIASAAIAAAcQAOAIAVAAQAjAAAAgbQAAgNgLgGQgIgFgTgDQgYgFgKgGQgQgKAAgTQAAgTAPgMQAPgMAYAAQAdAAAWANIAAAkIgSAAIAAgcQgMgHgUgBQgjAAAAAaQABAOAMAFQAGAEAVADQAXAFALAHQAPALAAATQAAAUgOAMQgQAMgaAAQgdAAgYgOg");
	this.shape_18.setTransform(-12.55,180.25);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgoBBIgIAiIgOAAQACgQAAgiIAAh/QAAgHgEAAIgTAAIAAgOIAMAAQAWAAAMgDIAABYQAQgiAmgBQAeABASAUQATAVAAAiQAAAigTAVQgSAUgfAAQgpAAgPglgAgYgRQgNAPAAAbIAAADQAAAbANAQQAOAPAVAAQAWAAAOgOQANgQAAgcIAAgDQAAgbgNgQQgOgPgWAAQgVAAgOAQg");
	this.shape_19.setTransform(-29.275,177.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag7AaIAAhPQAAgGgDAAIgTAAIAAgOIAtAAIAABiQAAAhAeAAQATAAAMgQQAMgRAAgZIAAg1QAAgGgEAAIgUAAIAAgOIAuAAIAAB7QABAHAEAAIASAAIAAAOIgMAAQgVAAgMACIAAgiQgPAjgjAAQgtAAgBgwg");
	this.shape_20.setTransform(-47.4,180.425);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhEBXIAAgvIATAAIAAAmQAWAKAbAAQAVAAANgKQAMgKAAgSQAAgSgOgJQgLgIgbgGQgegGgOgLQgRgOAAgXQAAgaATgPQATgQAeAAQAiAAAcAOIAAAwIgSAAIAAgmQgTgJgYAAQgVAAgNALQgNAJAAASQAAAQANAKQALAHAZAGQAgAHAOAJQATAOAAAZQAAAagSAQQgUAQgfAAQgmAAgegQg");
	this.shape_21.setTransform(-64.875,177.55);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgKALQgGgEAAgHQAAgGAGgEQAEgFAGAAQAHAAAFAFQAFAEAAAGQAAAHgFAEQgFAFgHAAQgGAAgEgFg");
	this.shape_22.setTransform(34.95,137.225);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgyA3QgTgWAAghQAAghAUgUQAUgWAgAAQAfAAASAUQASATAAAhIAAAGIh0AAQAAAaAOAQQAOAQAXAAQAnAAAKglIAPAFQgGAVgPANQgRANgbAAQgiAAgUgVgAAvgJQAAgZgMgNQgLgOgWAAQgUAAgNAOQgNAOgCAYIBdAAIAAAAg");
	this.shape_23.setTransform(23.525,131.25);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag5BKIAAgOIATAAQAEAAAAgGIAAhnQAAgHgEAAIgTAAIAAgOIAMAAQAVAAAMgCIAAAiQAKgjAeAAQAOAAAIAIQAIAIAAANQAAAVgSAAQgFAAgEgEQgEgEgBgFQAAgLAMgCQgDgJgMAAQgSAAgIARQgJAQAAAcIAAAzQAAAGAFAAIATAAIAAAOg");
	this.shape_24.setTransform(8.55,131.075);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("Ag7BBQgMgLAAgQQAAgZAYgMQAXgLAzgGIAAgJQAAgSgJgJQgJgJgTAAQgaAAgKANQAJADAAALQAAAGgEAEQgEADgHAAQgQAAAAgRQAAgQASgLQASgKAZAAQAdAAAOAMQAOAMAAAaIAABNQAAAHAEgBIASAAIAAAPIgnAAQgEgNgBgTQgGAQgPAJQgPAKgSAAQgVAAgMgLgAgfAIQgTAJAAASQAAAMAJAHQAIAHANAAQAVAAANgPQANgPAAgXIAAgMQgoAEgSAIg");
	this.shape_25.setTransform(-6.325,131.25);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgxA3QgUgVAAgiQAAghAVgVQAVgVAgAAQAdAAASAOQASANAAAXQAAAJgGAHQgFAFgIAAQgGAAgFgEQgEgEAAgGQAAgOAPgBQgHgcgmAAQgXAAgPARQgOAPAAAcIAAACQAAAcANAQQAOAQAYAAQAnAAAKgmIAPAFQgNAwg0AAQghAAgUgVg");
	this.shape_26.setTransform(-23.025,131.25);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AARBlIAAgOIARAAQAEAAAAgHIAAhNQAAgigeAAQgUAAgMASQgMARAAAfIAAAtQAAAHADAAIATAAIAAAOIhDAAIAAgOIATAAQADAAAAgHIAAicQAAgHgDAAIgUAAIAAgOIANAAQAVAAAMgDIAABbQAPgmAkAAQAtAAABAwIAABPQAAAHADAAIATAAIAAAOg");
	this.shape_27.setTransform(34.7,96.425);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgJBTQgIgJgBgUIAAhfIgWAAIAAgMIAQgBQAKgBABgKIACgaIAQAAIAAAkIAhAAIAAAOIgiAAIAABfQAAAMAEAGQAGAFAKAAQAJAAAIgDIAAAPQgKADgMAAQgTAAgJgJg");
	this.shape_28.setTransform(20.5,97.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AghBlIAAgOIATAAQAEAAAAgHIAAicQAAgHgEAAIgTAAIAAgOIANAAQAUAAAMgDIAAC0QAAAHAEAAIASAAIAAAOg");
	this.shape_29.setTransform(11.125,96.425);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("Ag7BBQgMgKAAgSQAAgXAYgOQAXgLAzgFIAAgJQAAgSgJgKQgJgIgTAAQgaAAgKANQAJADAAAKQAAAHgEAEQgEADgHABQgQAAAAgSQAAgRASgKQASgKAZAAQAdAAAOAMQAOANAAAZIAABNQAAAGAEABIASAAIAAANIgnAAQgEgMgBgSQgGAPgPAKQgPAJgSAAQgVAAgMgLgAgfAIQgTAJAAARQAAANAJAGQAIAIANAAQAVAAANgPQANgPAAgXIAAgMQgoAEgSAIg");
	this.shape_30.setTransform(-1.325,99.25);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgyA2QgTgUAAgiQAAghAUgVQAUgVAgAAQAfAAASATQASAUAAAiIAAAFIh0AAQAAAaAOAPQAOARAXAAQAnAAAKglIAPAFQgGAVgPAMQgRAOgbAAQgiAAgUgWgAAvgJQAAgZgMgNQgLgOgWAAQgUAAgNAOQgNAOgCAYIBdAAIAAAAg");
	this.shape_31.setTransform(-18.325,99.25);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAQBlIAAgOIASAAQAEAAAAgHIAAhNQAAgigfAAQgSAAgNASQgNARAAAfIAAAtQAAAHAFAAIASAAIAAAOIhEAAIAAgOIATAAQAEAAAAgHIAAicQAAgHgEAAIgTAAIAAgOIANAAQAVAAALgDIAABbQAQgmAkAAQAtAAAAAwIAABPQAAAHAEAAIATAAIAAAOg");
	this.shape_32.setTransform(-35.75,96.425);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AghBlIAAgOIATAAQAEAAAAgHIAAicQAAgHgEAAIgTAAIAAgOIANAAQAUAAAMgDIAAC0QAAAHAEAAIASAAIAAAOg");
	this.shape_33.setTransform(47.525,64.425);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("Ag7BBQgMgKAAgRQAAgYAYgNQAXgLAzgGIAAgIQAAgUgJgIQgJgJgTAAQgaAAgKANQAJADAAALQAAAGgEAEQgEAEgHgBQgQAAAAgRQAAgQASgLQASgKAZAAQAdAAAOAMQAOANAAAaIAABMQAAAGAEAAIASAAIAAAPIgnAAQgEgNgBgTQgGAQgPAJQgPAKgSAAQgVAAgMgLgAgfAIQgTAJAAASQAAALAJAIQAIAHANAAQAVAAANgPQANgOAAgYIAAgMQgoAEgSAIg");
	this.shape_34.setTransform(35.075,67.25);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgJBTQgIgJgBgVIAAheIgWAAIAAgNIAQgBQAKgBABgJIACgaIAQAAIAAAkIAhAAIAAAOIgiAAIAABeQAAANAEAFQAFAGALAAQAJAAAIgDIAAAOQgKAEgLAAQgUAAgJgJg");
	this.shape_35.setTransform(21.15,65.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAQBKIAAgOIARAAQAFAAAAgGIAAhMQAAgjgfAAQgTAAgMARQgNASAAAeIAAAuQAAAGAEAAIATAAIAAAOIhEAAIAAgOIATAAQAEAAAAgGIAAhnQAAgHgEAAIgTAAIAAgOIAMAAQAWAAALgCIAAAmQAPgnAkAAQAuAAAAAyIAABNQAAAGAEAAIATAAIAAAOg");
	this.shape_36.setTransform(7.025,67.075);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgyA3QgTgVAAgiQAAghAUgUQAUgWAgAAQAfAAASATQASAVAAAgIAAAGIh0AAQAAAaAOAQQAOAQAXAAQAnAAAKglIAPAFQgGAVgPANQgRANgbAAQgiAAgUgVgAAvgJQAAgZgMgNQgLgOgWAAQgUAAgNAOQgNAOgCAYIBdAAIAAAAg");
	this.shape_37.setTransform(-10.475,67.25);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgMBkIhEi1IAACfQAAAHAFAAIATAAIAAAOIhAAAIAAgOIAUAAQAFAAAAgHIAAicQAAgHgFAAIgUAAIAAgOIA6AAIA+CkIBBikIA4AAIAAAOIgUAAQgEAAAAAHIAACcQAAAHAEAAIAUAAIAAAOIhHAAIAAgOIAUAAQAFAAAAgHIAAigIhJC2g");
	this.shape_38.setTransform(-31.925,64.575);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD3, new cjs.Rectangle(-80,50,160,211), null);


(lib.HEAD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLALQgEgEAAgHQAAgGAEgEQAFgFAGAAQAHAAAFAFQAFAEgBAGQABAHgFAEQgFAFgHAAQgGAAgFgFg");
	this.shape.setTransform(39.95,287.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgyA3QgTgWAAghQAAggAUgWQAUgVAgAAQAfAAASATQASAVAAAgIAAAGIh0AAQAAAaAOAPQAOARAXAAQAnAAAKglIAPAFQgGAVgPAMQgRAOgbAAQgiAAgUgVgAAvgJQAAgYgMgOQgLgOgWAAQgUAAgNAOQgNAOgCAYIBdAAIAAAAg");
	this.shape_1.setTransform(28.525,281.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAQBKIAAgOIARAAQAFAAAAgGIAAhMQAAgjgfAAQgTAAgMARQgNASAAAeIAAAuQAAAGAEAAIATAAIAAAOIhEAAIAAgOIATAAQAEAAAAgGIAAhnQAAgHgEAAIgTAAIAAgOIAMAAQAWAAALgCIAAAmQAPgnAkAAQAuAAAAAyIAABNQAAAGAEAAIATAAIAAAOg");
	this.shape_2.setTransform(11.025,281.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag0A3QgUgVAAgiQAAghAUgVQAVgVAfAAQAhAAATAVQAVAVAAAhQAAAhgVAWQgUAVggAAQggAAgUgVgAglgtQgNARABAbIAAACQgBAcANAQQAOAQAXAAQAXAAAOgQQANgQAAgcIAAgCQABgbgNgRQgOgPgYAAQgXAAgOAPg");
	this.shape_3.setTransform(-6.85,281.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AghBlIAAgOIATAAQAEAAAAgHIAAicQAAgHgEAAIgTAAIAAgOIANAAQAUAAAMgDIAAC0QAAAHAEAAIASAAIAAAOg");
	this.shape_4.setTransform(-19.925,278.425);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag7BBQgMgLAAgQQAAgZAYgMQAXgMAzgFIAAgIQAAgUgJgIQgJgJgTAAQgaAAgKANQAJADAAALQAAAGgEAEQgEADgHAAQgQAAAAgRQAAgRASgKQASgKAZAAQAdAAAOAMQAOANAAAaIAABMQAAAGAEABIASAAIAAAOIgnAAQgEgNgBgTQgGAQgPAKQgPAJgSAAQgVAAgMgLgAgfAIQgTAJAAARQAAANAJAGQAIAIANAAQAVAAANgPQANgOAAgYIAAgMQgoAEgSAIg");
	this.shape_5.setTransform(-32.375,281.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgJBTQgIgJgBgVIAAheIgWAAIAAgNIAQAAQAKgBABgKIACgaIAQAAIAAAkIAhAAIAAAOIgiAAIAABeQAAANAEAFQAGAGAKAAQAJAAAIgDIAAAOQgKAEgLAAQgUAAgJgJg");
	this.shape_6.setTransform(14.75,243.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag0A3QgUgVAAgiQAAghAUgVQAVgVAgAAQAfAAAVAVQAUAVAAAhQAAAigUAVQgVAVggAAQggAAgUgVgAgkgtQgOARAAAbIAAACQAAAcAOAQQANAQAXAAQAYAAANgQQAOgQAAgcIAAgCQAAgbgOgRQgNgPgXAAQgYAAgNAPg");
	this.shape_7.setTransform(1.3,245.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAQBKIAAgOIARAAQAFAAAAgGIAAhMQAAgjgfAAQgTAAgMARQgNASAAAeIAAAuQAAAGAEAAIATAAIAAAOIhEAAIAAgOIATAAQAEAAAAgGIAAhnQAAgHgEAAIgTAAIAAgOIAMAAQAWAAALgCIAAAmQAPgnAkAAQAuAAAAAyIAABNQAAAGAEAAIATAAIAAAOg");
	this.shape_8.setTransform(-16.525,245.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgyA3QgTgWAAghQAAggAUgWQAUgVAgAAQAfAAASATQASAVAAAgIAAAGIh0AAQAAAaAOAPQAOARAXAAQAnAAAKglIAPAFQgGAVgPAMQgRAOgbAAQgiAAgUgVgAAvgJQAAgYgMgOQgLgOgWAAQgUAAgNAOQgNAOgCAYIBdAAIAAAAg");
	this.shape_9.setTransform(33.475,209.25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag5BKIAAgOIATAAQAEAAAAgGIAAhnQAAgHgEAAIgTAAIAAgOIAMAAQAVAAAMgCIAAAiQALgjAcAAQAPAAAJAIQAHAIAAANQAAAVgRAAQgGAAgFgEQgEgEAAgFQAAgLAMgCQgCgJgNAAQgSAAgHARQgJAQAAAcIAAAzQAAAGADAAIAUAAIAAAOg");
	this.shape_10.setTransform(18.5,209.075);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgUAdIAAgMIAIABQASAAAAgTIAAgEQgFAFgFAAQgOAAgBgOQABgHAEgEQAFgEAHAAQAKAAAGAHQAHAIAAAMQAAANgJAKQgJAJgOAAg");
	this.shape_11.setTransform(8.45,199.275);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag7AaIAAhPQAAgGgEAAIgSAAIAAgOIAtAAIAABiQAAAhAeAAQATAAAMgQQAMgRAAgZIAAg1QAAgGgEAAIgTAAIAAgOIAuAAIAAB7QAAAHADAAIATAAIAAAOIgMAAQgVAAgMACIAAgiQgPAjgiAAQgvAAAAgwg");
	this.shape_12.setTransform(-4,209.425);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag0A3QgUgVAAgiQAAghAUgVQAUgVAhAAQAgAAATAVQAVAVAAAhQAAAigVAVQgUAVggAAQggAAgUgVgAglgtQgNARAAAbIAAACQAAAcANAQQAOAQAXAAQAXAAAOgQQANgQAAgcIAAgCQABgbgNgRQgOgPgXAAQgYAAgOAPg");
	this.shape_13.setTransform(-21.5,209.25);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhGBdQgJgIAAgLQABgIAEgGQAEgEAIAAQALAAACAJQACAKgKAGIgGgJQAAAOARAAQAMAAAJgKQAJgKAKgaIAAgBIg3h1QgDgHgEAAIgNAAIAAgOIA+AAIAAAOIgOAAQgHABACAGIArBdIAphcQACgIgHAAIgPAAIAAgOIA4AAIAAAOIgOAAQgEAAgCAHIg1B6QgNAfgKALQgMAOgUAAQgOgBgKgGg");
	this.shape_14.setTransform(-38.85,211.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-78.9,0,152.9,298), null);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgYAjIAAgPIAJABQAWAAAAgWIAAgGQgGAGgHAAQgRAAAAgQQAAgIAGgFQAGgFAJAAQAKAAAJAJQAIAJAAAOQAAARgLALQgLALgRAAg");
	this.shape.setTransform(73.775,179.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag8BBQgXgZAAgoQAAgoAYgZQAYgZAmAAQAlAAAWAXQAWAYAAAnIAAAIIiMAAQABAeAQAUQARATAcABQAvgBAMgsIARAGQgGAZgTAPQgUAQggAAQgpAAgYgagAA5gLQgBgdgOgRQgOgQgZAAQgZAAgQAQQgPARgDAdIBxAAIAAAAg");
	this.shape_1.setTransform(60.175,170.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABFBZIAAgRIAUAAQAFAAAAgHIAAhWQAAgZgIgLQgJgMgUAAQgsAAAABCIAABEQAAAHAFAAIAYAAIAAARIhQAAIAAgRIAVAAQAEAAAAgHIAAhbQAAgrgkAAQgsAAAABCIAABEQAAAHAFAAIAWAAIAAARIhRAAIAAgRIAWAAQAFAAAAgHIAAh7QAAgKgFABIgWAAIAAgRIAPAAQAYAAAPgDIAAAjQAPgkAlAAQAqAAAJAqQAPgqAoAAQA4AAAABCIAABXQAAAHAFAAIAWAAIAAARg");
	this.shape_2.setTransform(34.575,170.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag+BBQgZgZAAgoQABgnAYgaQAYgZAnAAQAnAAAYAZQAYAZAAAoQAAAogYAZQgZAagnAAQgmAAgYgagAgrg1QgQASgBAjIAAACQAAAhAQATQAQAUAcAAQAcAAARgUQAQgTAAghIAAgCQAAgjgQgSQgQgUgcABQgcgBgQAUg");
	this.shape_3.setTransform(8.4,170.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAUB5IAAgRIAVAAQAEAAAAgHIAAheQAAgogkAAQgXAAgPAVQgPAVAAAlIAAA3QAAAHAFAAIAWAAIAAARIhRAAIAAgRIAWAAQAFAAAAgHIAAi8QAAgJgFAAIgXAAIAAgRIAQAAQAZAAAOgDIAABtQASgtArAAQA3AAAAA6IAABfQAAAHAFAAIAXAAIAAARg");
	this.shape_4.setTransform(-12.675,166.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgKBkQgLgLAAgZIAAhyIgbAAIAAgOIATgCQAMgBABgLIACgfIATAAIAAArIApAAIAAAQIgpAAIAAByQAAAPAFAHQAGAGAOAAQAJAAAKgDIAAARQgMAEgNAAQgYAAgKgKg");
	this.shape_5.setTransform(-38.875,168.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhHBOQgPgMAAgVQAAgdAdgPQAcgOA+gGIAAgLQAAgWgLgLQgLgKgXAAQgfAAgNAPQAMADAAAOQAAAHgGAFQgFAEgHABQgUgBAAgUQAAgVAWgMQAVgMAfAAQAiAAARAOQARAPAAAfIAABdQAAAHAEAAIAXAAIAAARIgwAAQgEgPgBgWQgIASgSAMQgSALgWAAQgYAAgPgNgAglAKQgXAKAAAVQAAAOAKAKQAKAIAQAAQAZAAAQgRQAPgSABgcIAAgPQgxAFgVAKg");
	this.shape_6.setTransform(-54.15,170.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AARB5IAAgRIATAAQAHAAgEgGIgqhEIgkAlIAAAeQAAAHAGAAIAVAAIAAARIhRAAIAAgRIAXAAQAEAAAAgHIAAi8QAAgJgEAAIgYAAIAAgRIAQAAQAZAAAOgDIAACmIBIhLQABgBAAAAQAAgBAAAAQABgBAAAAQAAgBgBAAQAAgCgEgBIgVAAIAAgQIBPAAIAAAQIgRAAQgHAAgGAHIgrApIA2BWQAEAGAFAAIAQAAIAAARg");
	this.shape_7.setTransform(38.35,124.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag7BCQgYgZAAgpQAAgoAZgZQAZgZAnAAQAjAAAVARQAWAQAAAcQAAAKgHAIQgGAGgJAAQgIAAgGgEQgFgFAAgIQAAgQASgCQgJghgtAAQgcAAgRATQgSATAAAiIAAABQAAAiAQATQARAUAdAAQAvAAAMgtIASAGQgPA5g/AAQgoAAgYgZg");
	this.shape_8.setTransform(18.725,128.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhGAgIAAhgQAAgIgGAAIgWAAIAAgQIA3AAIAAB3QgBAnAlAAQAXAAAOgUQAOgUAAgfIAAg/QAAgIgFAAIgWAAIAAgQIA3AAIAACUQgBAIAFAAIAXAAIAAARIgPAAQgaAAgOADIAAgqQgSArgqAAQg2AAAAg5g");
	this.shape_9.setTransform(-1.95,128.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgKBkQgLgLAAgZIAAhyIgbAAIAAgOIATgCQAMgBABgLIACgfIATAAIAAArIApAAIAAAQIgpAAIAAByQAAAPAFAHQAGAGAOAAQAJAAAKgDIAAARQgMAEgNAAQgYAAgKgKg");
	this.shape_10.setTransform(-18.625,126.325);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhBBLIAAgsIAVAAIAAAiQARAJAaAAQAqAAAAgfQAAgQgOgIQgJgFgWgFQgegFgMgIQgTgMAAgWQAAgYASgOQASgOAeAAQAjAAAZAPIAAAsIgVAAIAAghQgPgJgYAAQgpgBAAAfQAAAQAOAHQAIAEAZAFQAcAGANAHQASANAAAXQAAAZgRAOQgTAOgfAAQgkAAgcgQg");
	this.shape_11.setTransform(-32.7,128.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgyA2QgTgUAAgiQAAggAUgWQAUgVAgAAQAfAAASAUQASATAAAiIAAAFIh0AAQAAAaAOAPQAOARAXAAQAnAAAKglIAPAFQgGAVgPAMQgRAOgbAAQgiAAgUgWgAAvgJQAAgZgMgNQgLgOgWAAQgUAAgNAOQgNAOgCAYIBdAAIAAAAg");
	this.shape_12.setTransform(40.225,89.25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag5BKIAAgOIATAAQAEAAAAgGIAAhnQAAgHgEAAIgTAAIAAgOIAMAAQAVAAAMgCIAAAiQALgjAcAAQAPAAAJAIQAHAIAAANQAAAVgRAAQgGAAgFgEQgEgEAAgFQAAgLAMgCQgCgJgNAAQgSAAgHARQgJAQAAAcIAAAzQAAAGADAAIAUAAIAAAOg");
	this.shape_13.setTransform(25.25,89.075);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgUAdIAAgMIAIABQASAAAAgTIAAgEQgFAFgFAAQgOAAgBgOQABgHAEgEQAFgEAHAAQAKAAAGAHQAHAIAAAMQAAANgJAKQgJAJgOAAg");
	this.shape_14.setTransform(15.2,79.275);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag7AaIAAhPQAAgGgEAAIgSAAIAAgOIAtAAIAABiQAAAhAeAAQATAAAMgQQAMgRAAgZIAAg1QAAgGgEAAIgTAAIAAgOIAuAAIAAB7QAAAHADAAIATAAIAAAOIgMAAQgVAAgMACIAAgiQgPAjgiAAQgvAAAAgwg");
	this.shape_15.setTransform(2.75,89.425);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag0A3QgUgVAAgiQAAghAUgVQAUgVAhAAQAgAAATAVQAVAVAAAhQAAAhgVAWQgUAVggAAQggAAgUgVgAglgtQgNAQAAAcIAAACQAAAdANAPQAOAQAXAAQAXAAAOgQQANgQAAgcIAAgCQABgcgNgQQgOgPgXAAQgYAAgOAPg");
	this.shape_16.setTransform(-14.75,89.25);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhGBcQgJgGAAgMQABgJAEgEQAEgFAIgBQALAAACAKQACAKgKAGIgGgJQAAAOARAAQAMAAAJgKQAJgKAKgaIAAgCIg3h1QgDgFgEAAIgNAAIAAgPIA+AAIAAAPIgOAAQgHgBACAHIArBeIApheQACgGgHAAIgPAAIAAgPIA4AAIAAAPIgOAAQgEAAgCAFIg1B7QgNAfgKALQgMAOgUgBQgOABgKgIg");
	this.shape_17.setTransform(-32.1,91.95);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAQBKIAAgOIARAAQAFAAAAgGIAAhMQAAgjgfAAQgTAAgMARQgNASAAAeIAAAuQAAAGAEAAIATAAIAAAOIhEAAIAAgOIATAAQAEAAAAgGIAAhnQAAgHgEAAIgTAAIAAgOIAMAAQAWAAALgCIAAAmQAPgnAkAAQAuAAAAAyIAABNQAAAGAEAAIATAAIAAAOg");
	this.shape_18.setTransform(33.775,53.075);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgyA2QgTgUAAgiQAAggAUgWQAUgVAgAAQAfAAASAUQASATAAAiIAAAFIh0AAQAAAaAOAPQAOARAXAAQAnAAAKglIAPAFQgGAVgPAMQgRAOgbAAQgiAAgUgWgAAvgJQAAgZgMgNQgLgOgWAAQgUAAgNAOQgNAOgCAYIBdAAIAAAAg");
	this.shape_19.setTransform(16.275,53.25);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AARBlIAAgOIARAAQAEAAAAgHIAAhNQAAgigeAAQgUAAgMASQgMARAAAfIAAAtQAAAHADAAIATAAIAAAOIhDAAIAAgOIATAAQADAAAAgHIAAicQAAgHgDAAIgUAAIAAgOIANAAQAVAAAMgDIAABbQAPgmAjAAQAvAAgBAwIAABPQABAHAEAAIASAAIAAAOg");
	this.shape_20.setTransform(-1.15,50.425);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAqBJIgph1IgpB1IgQAAIgqh+QgCgFgEAAIgQAAIAAgPIBAAAIAAAPIgOAAQgIgBADAHIAfBhIAihhQACgHgHABIgLAAIAAgPIA8AAIAAAPIgMAAQgHgBADAHIAjBhIAfhhQACgGgHAAIgQAAIAAgPIA6AAIAAAPIgPAAQgEAAgCAFIgqB+g");
	this.shape_21.setTransform(-22.825,53.35);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAQBKIAAgOIARAAQAFAAAAgGIAAhMQAAgjgfAAQgTAAgMARQgNASAAAeIAAAuQAAAGAEAAIATAAIAAAOIhEAAIAAgOIATAAQAEAAAAgGIAAhnQAAgHgEAAIgTAAIAAgOIAMAAQAWAAALgCIAAAmQAPgnAkAAQAuAAAAAyIAABNQAAAGAEAAIATAAIAAAOg");
	this.shape_22.setTransform(29.875,17.075);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgyA2QgTgUAAgiQAAggAUgWQAUgVAgAAQAfAAASAUQASATAAAiIAAAFIh0AAQAAAaAOAPQAOARAXAAQAnAAAKglIAPAFQgGAVgPAMQgRAOgbAAQgiAAgUgWgAAvgJQAAgZgMgNQgLgOgWAAQgUAAgNAOQgNAOgCAYIBdAAIAAAAg");
	this.shape_23.setTransform(12.375,17.25);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgHBJIg1h+QgCgFgEAAIgQAAIAAgPIBCAAIAAAPIgQAAQgIgBADAHIApBkIAohkQADgGgHAAIgSAAIAAgPIA9AAIAAAPIgPAAQgFAAgDAFIg0B+g");
	this.shape_24.setTransform(-4.625,17.35);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AhMBjIAAgNIAUAAQAEAAAAgHIAAidQAAgHgEABIgUAAIAAgPICSAAIAAArIgQAAIgCgWQgCgHgJABIhGAAIAABMIAsAAQAHAAAAgGIAAgOIAPAAIAAA3IgPAAIAAgPQAAgGgHAAIgsAAIAABQIBNAAQAKAAABgHIACgXIAPAAIAAArg");
	this.shape_25.setTransform(-22.85,14.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(-75.9,0,160.4,190), null);


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgoANIASgNIgSgMIAAgXIAoAeIAAALIgoAegAADAMIARgMIgRgLIAAgVIAmAbIAAALIgmAbg");
	this.shape.setTransform(54.125,44.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLBBQgIgIAAgTIAAg+IgPAAIAAgPIAIgBQANgCABgKIADgUIAUAAIAAAfIAWAAIAAARIgXAAIAAA+QAAAQAPAAQAFAAAFgCIAAASQgJADgLAAQgSAAgIgIg");
	this.shape_1.setTransform(38.125,43.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgyA5IAAgRIALAAQADAAAAgFIAAhAQAAgIgDABIgLAAIAAgRIASAAQARgBAKgCIAAAZQAHgZAXAAQAMgBAHAIQAHAHAAANQAAAKgFAHQgHAHgJAAQgHAAgEgEQgFgFAAgGQAAgMALgDQgDgCgFAAQgWAAAAAlIAAAjQAAAFAEAAIAKAAIAAARg");
	this.shape_2.setTransform(28.275,44.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgqAqQgQgQgBgaQAAgaARgPQARgRAaAAQAaAAAQARQARAPgBAaQAAAagQAQQgQARgbAAQgaAAgQgRgAgcgBIAAADQAAAnAcgBQAcABABgnIAAgDQgBgmgcgBQgcABAAAmg");
	this.shape_3.setTransform(15.4,44.65);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhBBNIAAgRIAKAAQAEAAAAgGIAAhnQAAgHgEAAIgLAAIAAgRIATAAQARAAAKgDIAAAZQAKgZAcAAQAWAAAOAQQANAQAAAbQAAAZgOAQQgOARgWAAQgaAAgLgYIAAAlQAAAGAEAAIAKAAIAAARgAgNgvQgHAKAAASIAAAEQAAARAHAJQAIAKAMAAQANAAAHgKQAIgJAAgRIAAgEQAAgSgIgKQgHgJgNAAQgMAAgIAJg");
	this.shape_4.setTransform(0.85,46.475);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhBBNIAAgRIAKAAQAEAAAAgGIAAhnQAAgHgEAAIgLAAIAAgRIATAAQAQAAALgDIAAAZQAKgZAcAAQAWAAAOAQQANAQAAAbQAAAZgOAQQgNARgYAAQgaAAgKgYIAAAlQAAAGAEAAIAKAAIAAARgAgMgvQgIAKAAASIAAAEQAAARAIAJQAHAKALAAQAOAAAHgKQAIgJAAgRIAAgEQAAgSgIgKQgHgJgOAAQgLAAgHAJg");
	this.shape_5.setTransform(-14.15,46.475);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag0AQIAAgyQAAgFgDAAIgLAAIAAgRIAuAAIAABIQAAAVASAAQAXAAAAggIAAgnQAAgFgEAAIgLAAIAAgRIAuAAIAABXQAAAGAEAAIALAAIAAARIgTAAQgRAAgKADIAAgVQgLAWgZAAQglAAAAgqg");
	this.shape_6.setTransform(-28.825,44.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AguAyIAAgeIAXAAIAAAUQAIACAMAAQAWAAAAgOQAAgIgIgEQgFgCgNgDQgSgDgJgGQgNgHAAgRQAAgQANgKQANgKAXAAQAXAAATAJIAAAdIgYAAIAAgTQgFgCgMAAQgVAAAAAOQAAAHAIAEQAEACANACQATAEAJAFQANAIAAAQQAAARgOALQgNAKgXAAQgVAAgXgJg");
	this.shape_7.setTransform(-41.725,44.65);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgzA/QgOgRgBgaQABgaAOgQQANgQAXAAQAaAAALAXIAAgkQgBgIgDAAIgLAAIAAgRIATAAQAQABALgDIAACDQAAAFAEAAIAKAAIAAASIgqAAIgCgWQgKAZgcAAQgXAAgNgQgAgZgJQgIAJAAATIAAADQAAASAIAKQAHAJANAAQALAAAIgJQAHgKABgSIAAgDQgBgTgHgJQgIgKgLAAQgNAAgHAKg");
	this.shape_8.setTransform(18,19.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAJA6IAAgSIAJAAQADAAAAgGIAAgwQAAgXgSAAQgXAAAAAlIAAAiQAAAGAEAAIAIAAIAAASIg5AAIAAgSIAKAAQADAAAAgGIAAg/QAAgIgDAAIgKAAIAAgRIASAAQAQABAKgDIAAAWQALgWAaAAQAlgBAAAqIAAAxQgBAGAEAAIAKAAIAAASg");
	this.shape_9.setTransform(3.1,21.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgdBQIAAgSIALAAQAEAAAAgFIAAg9QgBgKgFAAIgJAAIAAgRIATAAQAPAAALgDIAABbQAAAFAEAAIAKAAIAAASgAgNgvQgFgGAAgHQAAgIAFgFQAGgGAHAAQAJAAAFAGQAGAFAAAIQAAAHgGAGQgFAGgJgBQgHABgGgGg");
	this.shape_10.setTransform(-8.2,19.05);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag8BMIAAgRIALAAQAFAAAAgGIAAhpQAAgGgFAAIgLAAIAAgRIB5AAIAAAmIgUAAIgDgOQgBgFgCgBIgKgBIgmAAIAAA2IAZAAQAGAAAAgIIAAgIIASAAIAAAwIgSAAIAAgJQAAgHgGAAIgZAAIAAApQAAAGAFAAIALAAIAAARg");
	this.shape_11.setTransform(-19.4,19.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#94D600").s().p("AsfFJIAAqSIY/AAIAAKSg");
	this.shape_12.setTransform(0,32.95);

	this.timeline.addTween(cjs.Tween.get(this.shape_12).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTA, new cjs.Rectangle(-80,0,160,65.9), null);


(lib.CPCCOlogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#40474F").s().p("AgRAdIABgIIAEABQAFgBABgDIACgFIgRgqIAKAAIALAfIAMgfIALAAIgVAxQgCAJgMABg");
	this.shape.setTransform(56.05,24.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#40474F").s().p("AgEAdIAAg5IAJAAIAAA5g");
	this.shape_1.setTransform(52.775,22.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#40474F").s().p("AgDAfIAAgqIAIAAIAAAqgAgFgYQAAgFAFgBQAGABAAAFQAAAGgGAAQgFAAAAgGg");
	this.shape_2.setTransform(50.625,22.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#40474F").s().p("AAVAWIAAgbQAAgIgHAAQgGAAgEAGIAAAdIgIAAIAAgbQAAgIgHAAQgGAAgEAGIAAAdIgJAAIAAgqIAJAAIAAAGQAFgHAJAAQAIAAADAIQAFgIAJAAQANAAAAANIAAAeg");
	this.shape_3.setTransform(45.925,23.375);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#40474F").s().p("AgNATQgFgEAAgHQAAgHAFgCQAEgEAGAAQAIAAAFAFIAAgFQAAgIgKAAQgHAAgFAFIgEgGQAHgHAKAAQASAAAAAPIAAAbIgJAAIAAgEQgFAFgIAAQgGAAgEgDgAgIAIQgBAIAJAAQAGAAAEgEIAAgHQgEgEgGAAQgJAAABAHg");
	this.shape_4.setTransform(39.75,23.425);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#40474F").s().p("AgTAdIAAg5IAnAAIAAAJIgdAAIAAAPIAcAAIAAAIIgcAAIAAAZg");
	this.shape_5.setTransform(35.375,22.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#40474F").s().p("AAKAWIAAgaQAAgJgJAAQgGAAgDAGIAAAdIgKAAIAAgqIAKAAIAAAGQAFgHAIAAQAOAAAAAOIAAAdg");
	this.shape_6.setTransform(27.95,23.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#40474F").s().p("AgPAQQgGgHAAgJQAAgJAGgGQAGgGAJAAQAKAAAGAGQAGAGAAAJQAAAJgGAHQgGAGgKAAQgJAAgGgGgAgIgJQgDAEgBAFQAAAOAMAAQANAAAAgOQAAgFgDgEQgEgEgGAAQgFAAgDAEg");
	this.shape_7.setTransform(23.15,23.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#40474F").s().p("AgRAYIADgGQAGAFAIAAQALAAAAgMIAAgFQgEAHgIAAQgIAAgGgFQgFgHAAgIQAAgLAFgGQAGgFAIAAQAIAAAEAGIAAgFIAKAAIAAAnQAAATgVAAQgLABgGgHgAgKgHQAAAMALAAQAHAAADgFIAAgQQgDgFgHgBQgLAAAAAPg");
	this.shape_8.setTransform(18.15,24.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#40474F").s().p("AgOAQQgGgGAAgKQAAgIAGgHQAGgGAIAAQAKAAAGAGQAFAHAAAJIAAACIgfAAQAAAFAEADQAEAEAEAAQAIAAAEgFIAEAGQgGAGgLAAQgJAAgGgGgAgLgCIAXAAQAAgFgDgDQgDgEgGAAQgKAAgBAMg");
	this.shape_9.setTransform(13.275,23.425);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#40474F").s().p("AgKAWIAAgqIAJAAIAAAGQAFgHAHAAIAAAJIgCAAQgIAAgCAGIAAAcg");
	this.shape_10.setTransform(9.5,23.375);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#40474F").s().p("AgVAWQgIgJAAgNQAAgMAIgJQAJgIAMAAQANAAAIAIQAJAJAAAMQAAANgJAJQgIAIgNAAQgMAAgJgIgAgNgOQgGAGABAIQgBAJAGAGQAFAGAIAAQAJAAAFgGQAGgGgBgJQABgIgGgGQgFgGgJAAQgIAAgFAGg");
	this.shape_11.setTransform(4.55,22.625);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#40474F").s().p("AgOAQQgGgGAAgKQAAgIAGgHQAGgGAIAAQAKAAAGAGQAFAHAAAJIAAACIgfAAQAAAFAEADQAEAEAEAAQAIAAAEgFIAEAGQgGAGgLAAQgJAAgGgGgAgLgCIAXAAQAAgFgDgDQgDgEgGAAQgKAAgBAMg");
	this.shape_12.setTransform(-1.275,23.425);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#40474F").s().p("AgLAWIAAgqIAKAAIAAAGQAEgHAJAAIAAAJIgDAAQgIAAgCAGIAAAcg");
	this.shape_13.setTransform(-5.025,23.375);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#40474F").s().p("AgNATQgFgEAAgHQAAgNAPAAQAIAAAFAFIAAgFQAAgIgKAAQgHAAgFAFIgEgGQAHgHAKAAQASAAAAAPIAAAbIgJAAIAAgEQgGAFgHAAQgGAAgEgDgAgJAIQAAAIAJAAQAGAAAEgEIAAgHQgEgEgGAAQgJAAAAAHg");
	this.shape_14.setTransform(-9.225,23.425);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#40474F").s().p("AgRAWQgJgJAAgNQAAgMAJgJQAIgIAMAAQAQAAAIANIgJAEQgFgIgKAAQgIAAgFAGQgGAGAAAIQAAAJAGAGQAFAGAIAAQAKAAAFgIIAJAEQgIANgQAAQgMAAgIgIg");
	this.shape_15.setTransform(-14.375,22.625);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#40474F").s().p("AgOAQQgGgGgBgKQAAgIAHgHQAGgGAJAAQAJAAAFAGQAHAHgBAJIAAACIggAAQABAFAEADQAEAEAEAAQAHAAAFgFIAFAGQgHAGgLAAQgIAAgHgGgAgLgCIAYAAQgCgMgKAAQgLAAgBAMg");
	this.shape_16.setTransform(-22.2,23.425);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#40474F").s().p("AAKAdIAAgaQAAgIgJAAQgFAAgEAFIAAAdIgKAAIAAg5IAKAAIAAAWQAFgHAIAAQAOAAAAANIAAAdg");
	this.shape_17.setTransform(-26.95,22.625);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#40474F").s().p("AgFARIAAgYIgIAAIAAgIIAIAAIAAgLIAIAAIAAALIAJAAIAAAIIgJAAIAAAWQAAAEAEAAQABAAAAAAQABAAAAAAQABAAAAAAQABgBAAAAIADAHQgEACgGABQgKAAABgLg");
	this.shape_18.setTransform(-30.85,22.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#40474F").s().p("AgGAeIAAgiIgHAAIAAgIIAHAAIAAgCQAAgPANAAQAFAAACACIgCAHIgEgBQgFAAgBAHIAAACIAJAAIAAAIIgJAAIAAAig");
	this.shape_19.setTransform(-35.75,22.575);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#40474F").s().p("AgPAQQgGgHAAgJQAAgJAGgGQAGgGAJAAQAKAAAGAGQAGAGAAAJQAAAJgGAHQgGAGgKAAQgJAAgGgGgAgIgJQgDAEAAAFQAAAGADAEQADAEAFAAQAMAAAAgOQAAgFgDgEQgDgEgGAAQgFAAgDAEg");
	this.shape_20.setTransform(-39.775,23.425);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#40474F").s().p("AgFARIAAgYIgHAAIAAgIIAHAAIAAgLIAIAAIAAALIAJAAIAAAIIgJAAIAAAWQAAAEAEAAQABAAAAAAQABAAAAAAQABAAAAAAQABgBAAAAIACAHQgCACgGABQgKAAAAgLg");
	this.shape_21.setTransform(-45.975,22.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#40474F").s().p("AgLAWIAAgqIAJAAIAAAGQAGgHAIAAIAAAJIgEAAQgHAAgDAGIAAAcg");
	this.shape_22.setTransform(-48.85,23.375);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#40474F").s().p("AgNATQgFgEAAgHQAAgHAFgCQAEgEAGAAQAIAAAEAFIAAgFQABgIgKAAQgHAAgFAFIgEgGQAHgHAKAAQASAAAAAPIAAAbIgKAAIAAgEQgEAFgIAAQgGAAgEgDgAgJAIQAAAIAJAAQAHAAACgEIAAgHQgCgEgHAAQgJAAAAAHg");
	this.shape_23.setTransform(-52.75,23.425);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#40474F").s().p("AgWAdIAAg5IAZAAQAJAAAGAFQAEAFAAAIQAAAIgEAEQgGAFgJAAIgPAAIAAAWgAgMgBIANAAQALAAgBgJQABgJgLAAIgNAAg");
	this.shape_24.setTransform(-57.1,22.625);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#40474F").s().p("AAIAKIgBgRIgGARIgCAAIgFgRIgBARIgDAAIACgTIADAAIAFAQIAAAAIAFgQIAEAAIACATg");
	this.shape_25.setTransform(68.25,3.275);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#40474F").s().p("AAAAKIAAgRIgHAAIAAgCIAPAAIAAACIgHAAIAAARg");
	this.shape_26.setTransform(66.225,3.275);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#40474F").s().p("AgLAaIAAgjIgMAAIAAgRIAMAAIAAgTIASAAIAAATIAOAAIAAARIgOAAIAAAeQAAAIAGAAQAEAAACgCIAFAOQgGAEgKAAQgTABAAgUg");
	this.shape_27.setTransform(63.25,6.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#40474F").s().p("AgVAaQgLgKAAgQQAAgPALgLQALgKAPAAQATAAAJANIgNALQgFgIgJAAQgIAAgFAGQgGAGAAAIQAAAJAGAGQAFAFAIAAQAIAAAGgHIANALQgKANgSAAQgPAAgLgLg");
	this.shape_28.setTransform(57.3,7.675);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#40474F").s().p("AgYAbQgLgLAAgQQAAgPAKgKQALgLAPAAQAPAAAKALQAKAKAAARIAAAEIgzAAQABAHAFAEQAGAFAHAAQALAAAIgHIAIAMQgLAKgSAAQgPAAgLgKgAgLgQQgEAEAAAGIAhAAQAAgGgEgEQgFgFgIAAQgHAAgFAFg");
	this.shape_29.setTransform(50.025,7.675);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#40474F").s().p("AAPAkIAAgpQAAgOgOAAQgIAAgHAJIAAAuIgSAAIAAhFIASAAIAAAJQAKgLAOAAQAXAAAAAWIAAAxg");
	this.shape_30.setTransform(42.55,7.575);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#40474F").s().p("AAOAkIAAgpQABgOgNAAQgJAAgGAJIAAAuIgTAAIAAhFIATAAIAAAJQAJgLAOAAQAXAAAAAWIAAAxg");
	this.shape_31.setTransform(34.85,7.575);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#40474F").s().p("AgaAaQgKgLAAgPQAAgPAKgKQAKgLAQAAQARAAAKALQAKAKAAAPQAAAPgKALQgKALgRAAQgQAAgKgLgAgMgOQgFAGAAAIQAAAIAFAGQAFAGAHAAQAIAAAFgGQAFgGAAgIQAAgIgFgGQgFgGgIAAQgHAAgFAGg");
	this.shape_32.setTransform(27.225,7.675);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#40474F").s().p("AgeAkQgPgOAAgWQAAgVAPgOQAOgOAVAAQAbAAAOAYIgSAIQgHgOgQAAQgMAAgIAJQgJAJAAANQAAAOAJAJQAIAJAMAAQAQAAAHgOIASAIQgOAYgbAAQgVAAgOgOg");
	this.shape_33.setTransform(18.825,6.325);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#40474F").s().p("AgYAbQgLgLAAgQQAAgPAKgKQALgLAOAAQAQAAAKALQAKALAAAQIAAAEIg0AAQADAQARAAQALAAAHgHIAIAMQgLAKgRAAQgQAAgKgKgAgQgGIAiAAQgBgGgDgEQgFgFgJAAQgOAAgCAPg");
	this.shape_34.setTransform(7.925,7.675);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#40474F").s().p("AgTAkIAAhFIASAAIAAAJQAIgLAOAAIAAASIgGAAQgEAAgFACQgGACgBAEIAAAtg");
	this.shape_35.setTransform(2.25,7.575);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#40474F").s().p("AgYAfQgIgHAAgLQAAgLAIgFQAHgFAKAAQAOAAAHAIIAAgJQAAgMgOAAQgMAAgJAIIgHgMQANgLARAAQAfAAAAAbIAAAsIgTAAIAAgHQgIAJgNAAQgKAAgHgGgAgNAOQAAAEAEADQAEADAFAAQAKAAAEgGIAAgJQgEgGgKAAQgNAAAAALg");
	this.shape_36.setTransform(-4.575,7.675);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#40474F").s().p("AgeAkQgPgOAAgWQAAgVAPgOQAOgOAVAAQAbAAAOAYIgSAIQgHgOgQAAQgMAAgIAJQgJAJAAANQAAAOAJAJQAIAJAMAAQAQAAAHgOIASAIQgOAYgbAAQgVAAgOgOg");
	this.shape_37.setTransform(-12.875,6.325);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#40474F").s().p("AAOAkIAAgpQABgOgNAAQgJAAgHAJIAAAuIgSAAIAAhFIASAAIAAAJQAKgLAOAAQAXAAAAAWIAAAxg");
	this.shape_38.setTransform(-24,7.575);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#40474F").s().p("AgaAaQgKgLAAgPQAAgPAKgKQAKgLAQAAQARAAAKALQAKAKAAAPQAAAPgKALQgKALgRAAQgQAAgKgLgAgNgOQgEAGAAAIQAAAIAEAGQAFAGAIAAQAIAAAFgGQAFgGAAgIQAAgIgFgGQgFgGgIAAQgIAAgFAGg");
	this.shape_39.setTransform(-31.775,7.675);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#40474F").s().p("AgeAaIAIgNQAKAJANAAQAMAAAAgHQAAgFgNgDQgNgCgFgDQgJgFAAgLQAAgJAHgGQAIgHAMAAQAQAAAMAKIgHAMQgHgIgOAAQgKAAAAAHQAAAFAMACQAOADAFADQAKAFAAALQAAAKgIAGQgIAHgPAAQgSAAgMgLg");
	this.shape_40.setTransform(-38.9,7.675);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#40474F").s().p("AALAwIgRgbIgJAJIAAASIgSAAIAAhfIASAAIAAA5IAagfIAXAAIgcAfIAcAmg");
	this.shape_41.setTransform(-45.425,6.325);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#40474F").s().p("AgVAaQgKgKAAgQQAAgPAKgLQALgKAPAAQATAAAIANIgMALQgFgIgJAAQgIAAgFAGQgFAGAAAIQAAAJAFAGQAFAFAIAAQAJAAAFgHIAMALQgJANgSAAQgPAAgLgLg");
	this.shape_42.setTransform(-52.775,7.675);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#40474F").s().p("AgYAfQgIgHAAgLQAAgLAIgFQAHgFAKAAQAOAAAHAIIAAgJQAAgMgOAAQgNAAgIAIIgHgMQANgLARAAQAeAAAAAbIAAAsIgSAAIAAgHQgIAJgNAAQgJAAgIgGgAgNAOQAAAEAEADQAEADAFAAQAJAAAFgGIAAgJQgFgGgJAAQgNAAAAALg");
	this.shape_43.setTransform(-59.9,7.675);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#40474F").s().p("AgdAoIAJgQQAHAHAIAAQAOAAAAgQIAAg/IAVAAIAABAQAAAQgJAJQgKAIgOAAQgRAAgJgJg");
	this.shape_44.setTransform(-66.875,6.425);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#08594C").s().p("AncgNQD9gdDhAAQDdAAD7AdQD1AcAfAbQifgXi8gMQjBgLjNAAQmkAAlOAvQAYgbD5gdg");
	this.shape_45.setTransform(0,-6.075);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#08594C").s().p("AhsBBIADgLIASgMIgOAAIAJgdIAOgJIgKAAIAPgwIAUBDIgPABIARAKIAUgOIgRAAIAMglIARgLIgNAAIATg+IANAqIgKgCIAMAKIAKAkIgTABIAZAOIAKAjIgVgEIAZAUIABACIAEgLIARgLIgOAAIAKgdIANgKIgKABIAPgwIAVBDIgQAAIATAMIARA4g");
	this.shape_46.setTransform(58.9,-12.875);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#08594C").s().p("Ag/AzIAYgTIgTAFIAJggIAXgMIgSgBIAJghIALgIIgJABIAMgmIASA4IgMAAIAPAKIAKAhIgPAAIATANIACAHIACgGIASgLIgPAAIATg8IAOAsIgKgBIAMAIIgBABIAIAZIgMAAIAPAKIAJAYIiVAUg");
	this.shape_47.setTransform(-63.275,-12.15);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#08594C").s().p("Ag1AfIAIgGIgIABIAFgRIAIgFIgGAAIAJgaIALAlIgJAAIALAHIABACIAKgGIgKAAIAGgUIAKgHIgIAAIALgjIAHAYIgFgBIAGAFIAGAUIgKAAIANAJIAEALIADgBIAAAAIAKgHIgIAAIAEgQIAHgFIgGAAIAHgbIAOAjIgJACIAMAFIAIAcIh1AHg");
	this.shape_48.setTransform(-40.525,-10.275);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#7B4C18").s().p("AkWgZIAYgEIAJgrIEQgFIAPAJIA7gBIANgKIBAgBIAMAyIAsAAIB4BUIgygBIhKhAIhpAAIAIgGQAMgIAWgDIgJgfIgoABIgMAKIhFABIgOgKIj0AFIgHAXQAsAAAuALQAWAFAOAFIiiADIgYAiQgYAlgDAKIgmAFQAMgZA/hRg");
	this.shape_49.setTransform(-20.35,-13.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CPCCOlogo, new cjs.Rectangle(-74.9,-22,149.9,49.3), null);


(lib.BKGD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#285C4D").s().p("A3bM5IAA5xMAu3AAAIAAZxg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGD2, new cjs.Rectangle(-150,-82.5,300,165), null);


// stage content:
(lib.JCC_StuckAtHome_160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_205 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(205).call(this.frame_205).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgMaguyIY1AAMAAABdlI41AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(206));

	// CPCCO logo
	this.instance = new lib.CPCCOlogo();
	this.instance.setTransform(82.2,538.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(206));

	// HEAD1
	this.instance_1 = new lib.HEAD1();
	this.instance_1.setTransform(75.75,80);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(90).to({alpha:0},5).to({_off:true},1).wait(110));

	// HEAD2
	this.instance_2 = new lib.HEAD2();
	this.instance_2.setTransform(82.5,80);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(48).to({_off:false},0).to({alpha:1},5).wait(37).to({alpha:0},5).to({_off:true},1).wait(110));

	// HEAD3
	this.instance_3 = new lib.HEAD3();
	this.instance_3.setTransform(80,128,1,1,0,0,0,0,49);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(95).to({_off:false},0).to({alpha:1},5).wait(53).to({alpha:0},5).to({_off:true},1).wait(47));

	// HEAD4
	this.instance_4 = new lib.HEAD4();
	this.instance_4.setTransform(80,97,1,1,0,0,0,0,49);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(158).to({_off:false},0).to({alpha:1},5).wait(43));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_201 = new cjs.Graphics().p("EgXbAkFIAA84MAu3AAAIAAc4g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(201).to({graphics:mask_graphics_201,x:80,y:230.9399}).wait(5));

	// CTA
	this.instance_5 = new lib.CTA();
	this.instance_5.setTransform(80,428.05);
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(201).to({_off:false},0).to({y:396.05},4,cjs.Ease.quadOut).wait(1));

	// bkgd2
	this.instance_6 = new lib.BKGD2();
	this.instance_6.setTransform(80,180.45,0.5333,2.1818,0,0,0,0,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(43).to({regY:0.3,scaleY:2.1817,y:181.15},0).to({regX:0.1,regY:0.5,scaleY:2.8004,x:80.05,y:232.05},5,cjs.Ease.quadOut).wait(158));

	// bkgd
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CAF2F4").s().p("EgMfAu4MAAAhdvIY/AAMAAABdvg");
	this.shape_1.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(206));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(79.5,299.5,81,301);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 160,
	height: 600,
	fps: 24,
	color: "#999999",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;